/**
 * Entry-level non-fetch delivery for effectful `Cloudflare.Website.Astro`
 * (the Astro analogue of the Next.js OpenNext artifact takeover and the
 * SvelteKit worker shim's effect arm).
 *
 * The fetchable wrapper (`fetchable-plugin.ts`) is a render-level seam:
 * astro core delegates `App.render` through it, so it can only ever
 * deliver `fetch`. The worker ENTRY, however, is the integration's own
 * vendored `@astrojs/cloudflare` server entrypoint (`main` is pinned to
 * `SERVER_ENTRYPOINT`) — a seam alchemy controls. When the construct
 * carries an Effect program, this `enforce: "pre"` plugin takes over the
 * `ssr` environment's resolution of that bare specifier and substitutes a
 * generated wrapper module:
 *
 * ```js
 * import { WorkerEntrypoint, DurableObject } from "cloudflare:workers";
 * import { makeWebsiteEntryExports, DurableObjectBridge } from "alchemy/Serve/Worker";
 * import __astroEntry from "/abs/path/to/vendored/server.js";
 * import Site from "/abs/path/to/site.ts";
 * export default makeWebsiteEntryExports(WorkerEntrypoint, {
 *   site: Site,
 *   fetch: (request, env, ctx) => __astroEntry.fetch(request, env, ctx),
 * });
 * const Bridge = DurableObjectBridge(DurableObject, { site: Site });
 * export class Counter extends Bridge("Counter") {}
 * ```
 *
 * - **fetch stays exactly as delivered today**: the wrapper's fetch
 *   delegates verbatim to the vendored astro entry, whose `App.render`
 *   runs through the pre-resolved fetchable (effect-first over
 *   `server.routes`, universal RPC path, env-marker guard). No double
 *   bridging, no route logic at the entry.
 * - **Non-fetch handlers** (queue/scheduled/email/tail) and workerd JS-RPC
 *   dispatch come from the Worker bridge inside
 *   `makeWebsiteEntryExports` — the impl's `consumeQueueMessages`
 *   listeners (etc.) finally have an entry to be dispatched through.
 * - **Durable Object classes** collected from the impl's exports are
 *   re-exported as bridge classes sharing the one-per-isolate layer build
 *   with the non-fetch dispatch.
 *
 * The takeover deliberately does NOT gate on `resolveOptions.isEntry`: in
 * the dev child the module runner's entry resolution reaches this plugin
 * with the flag already dropped by an intermediate `this.resolve` (astro's
 * own resolution plugins re-resolve without forwarding it), which would
 * silently stand the wrapper down. The vendored entry has exactly one
 * legitimate consumer in the `ssr` environment — being the entry — so every
 * bare-specifier resolution there gets the wrapper; the wrapper reaches the
 * real vendored module by re-resolving with `skipSelf` from `load`.
 *
 * The plugin applies to the `ssr` environment only — prod build and dev
 * (the dev entry environment is `ssr`, executing in workerd) — and
 * deliberately NOT to the `prerender` environment: the build-time
 * prerender worker keeps the plain vendored entry, so the effect graph
 * never loads there (mirroring the fetchable plugin's exclusion). Both
 * wrapper modules import the site module by the same resolved id, so vite
 * shares one module instance across the fetchable and the entry.
 */
import { fileURLToPath } from "node:url";
import type * as vite from "vite";

const RESOLVED_ENTRY_WRAPPER_ID = "\0virtual:alchemy:astro-entry";

export interface EffectEntryPluginOptions {
  /**
   * The user's effect-program module (`props.main`) — an absolute path or
   * `file://` URL. The generated wrapper imports its default export (the
   * Website class).
   */
  readonly mainPath: string;
  /**
   * Durable Object class names exported by the effect program
   * (`ctx.entry.exports` with `kind: "durableObject"`), re-exported from
   * the wrapper as bridge classes.
   */
  readonly doClasses?: ReadonlyArray<string> | undefined;
  /**
   * The vendored worker entry specifier the integration pins `main` to
   * (`SERVER_ENTRYPOINT`) — passed in to avoid a circular import with
   * `integration.ts`.
   */
  readonly serverEntrypoint: string;
}

/** Normalize a path or `file://` URL to a `/`-separated absolute path. */
const toPath = (value: string): string =>
  (value.startsWith("file:") ? fileURLToPath(value) : value).replaceAll(
    "\\",
    "/",
  );

/**
 * The generated wrapper module source (exported for unit tests).
 */
export const makeEntryWrapperSource = (options: {
  /** Resolved id of the real vendored server entry module. */
  readonly entryId: string;
  readonly mainPath: string;
  readonly doClasses: ReadonlyArray<string>;
}): string => {
  const hasDo = options.doClasses.length > 0;
  return [
    `// Generated by alchemy — Astro entry takeover: fetch delegates to the`,
    `// vendored astro entry (already effect-composed via the fetchable);`,
    `// non-fetch handlers + DO classes come from the Worker bridge.`,
    `globalThis.__ALCHEMY_RUNTIME__ = true;`,
    `import { WorkerEntrypoint${hasDo ? ", DurableObject" : ""} } from "cloudflare:workers";`,
    `import { makeWebsiteEntryExports${hasDo ? ", DurableObjectBridge" : ""} } from "alchemy/Serve/Worker";`,
    `import __astroEntry from ${JSON.stringify(options.entryId)};`,
    `import Site from ${JSON.stringify(options.mainPath)};`,
    `export default makeWebsiteEntryExports(WorkerEntrypoint, {`,
    `  site: Site,`,
    `  fetch: (request, env, ctx) => __astroEntry.fetch(request, env, ctx),`,
    `});`,
    ...(hasDo
      ? [
          `const __alchemyDurableObjectBridge = DurableObjectBridge(DurableObject, { site: Site });`,
          ...options.doClasses.map(
            (name) =>
              `export class ${name} extends __alchemyDurableObjectBridge(${JSON.stringify(name)}) {}`,
          ),
        ]
      : []),
    ``,
  ].join("\n");
};

export const createEffectEntryPlugin = (
  options: EffectEntryPluginOptions,
): vite.Plugin => {
  const mainPath = toPath(options.mainPath);
  const doClasses = options.doClasses ?? [];
  return {
    name: "@alchemy.run/frontend-frameworks/astro:effect-entry",
    enforce: "pre",
    resolveId: {
      filter: {
        id: [
          /entrypoints\/server/,
          // oxlint-disable-next-line no-control-regex
          /^\0virtual:alchemy:astro-entry$/,
        ],
      },
      handler(id) {
        // Self-resolution: the module runner re-requests the wrapper by its
        // resolved id raw (the generated worker-entry's import is written
        // with the `\0` id, not an `/@id/` URL), and vite's `fetchModule`
        // requires a plugin to claim it.
        if (id === RESOLVED_ENTRY_WRAPPER_ID) return RESOLVED_ENTRY_WRAPPER_ID;
        if (id !== options.serverEntrypoint) return null;
        // The `ssr` environment is the worker entry environment in BOTH
        // prod build and dev (workerd module runner). `prerender` keeps
        // the plain vendored entry so prerendering never loads the effect
        // graph.
        if (
          (this as unknown as { environment?: { name?: string } }).environment
            ?.name !== "ssr"
        ) {
          return null;
        }
        return RESOLVED_ENTRY_WRAPPER_ID;
      },
    },
    load: {
      filter: {
        id: new RegExp(`^${RESOLVED_ENTRY_WRAPPER_ID.replace("\0", "\\0")}$`),
      },
      handler() {
        // The wrapper reaches the REAL vendored entry by concrete file
        // path, resolved with node semantics from this package (the
        // specifier is our own subpath export). Deliberately NOT
        // `this.resolve` — `skipSelf` is not reliably honored across the
        // load→resolveId boundary, and a takeover re-entry would make the
        // wrapper import itself.
        const entryId = toPath(import.meta.resolve(options.serverEntrypoint));
        return {
          code: makeEntryWrapperSource({
            entryId,
            mainPath,
            doClasses,
          }),
        };
      },
    },
  };
};
