import * as Alchemy from "alchemy";
import * as Prisma from "alchemy/Prisma";
import * as Effect from "effect/Effect";
import * as Redacted from "effect/Redacted";

const serviceName =
  process.env.PRISMA_TANSTACK_SERVICE ?? "alchemy-prisma-tanstack-start";
const projectName = process.env.PRISMA_PROJECT ?? `${serviceName}-project`;
const message =
  process.env.TANSTACK_MESSAGE ?? "hello from TanStack Start on Prisma Compute";
const devPort = Number(process.env.PRISMA_TANSTACK_DEV_PORT ?? "3000");

export default Alchemy.Stack(
  "PrismaTanstackStart",
  {
    providers: Prisma.providers(),
    state: Alchemy.localState(),
  },
  Effect.gen(function* () {
    // Project is the Prisma Console container for everything else in this
    // stack: branches, databases, connections, env vars, and Compute services.
    // `createDatabase: false` keeps the example explicit so the database below
    // is visible as its own Alchemy resource.
    const project = yield* Prisma.Project("Project", {
      name: projectName,
      createDatabase: false,
      region: "us-east-1",
    });

    // Branch is optional for a minimal database-only app, but useful once
    // Compute is involved. It gives the database and Compute service the same
    // deployment lane, so later you can model `main`, preview branches, or prod
    // promotion without changing the app env contract.
    const branch = yield* Prisma.Branch("MainBranch", {
      project,
      gitName: "main",
      isDefault: true,
    });

    // Postgres is the product-shaped alias for Prisma.Database. In deploy it
    // creates a real Prisma Postgres database and attaches it to the branch
    // above. In `alchemy dev`, the `dev` block starts a local Prisma Postgres
    // via `@prisma/dev` and returns the same connection-string attributes.
    const postgres = yield* Prisma.Postgres("Postgres", {
      project,
      name: "main",
      region: "us-east-1",
      branchId: branch.branchId,
      isDefault: true,
      dev: {
        provider: "@prisma/dev",
        // Local dev should boot into a useful app, not an empty shell. This
        // command runs after @prisma/dev is ready, with DATABASE_URL pointed at
        // the direct local Postgres URL.
        migrate: "bun run db:setup",
      },
    });

    // Connection creates the app-facing database credentials. Its returned
    // strings are redacted in Alchemy state. In dev mode it mirrors the local
    // `@prisma/dev` URLs from Postgres, so the app keeps the same env names.
    const connection = yield* Prisma.Connection("Connection", {
      database: postgres,
      name: "web",
    });

    // EnvironmentVariable is for project-level config managed by Prisma. It is
    // separate from ComputeApp.env below: use this for shared config, and use
    // ComputeApp.env for values that should travel with a specific deployment.
    const sharedFlag = yield* Prisma.EnvironmentVariable("SharedFlag", {
      project,
      class: "production",
      key: "TANSTACK_SHARED_FLAG",
      value: Redacted.make("project-level"),
    });

    // Prisma Next's Postgres runtime uses the `pg` driver, so it wants a
    // direct postgres:// URL. The Prisma.Connection resource can also expose a
    // pooled prisma+postgres:// URL, but that is for Prisma Postgres clients
    // that understand the Data Proxy protocol, not this runtime.
    const databaseUrl =
      connection.directConnectionString ?? connection.connectionString;

    // ComputeApp builds the TanStack Start app, uploads the `.output` artifact
    // to Prisma Compute, and promotes a version. The env block is the runtime
    // contract for deploy; the dev block runs Vite locally while reusing the
    // same database/project IDs generated by the resources above.
    const app = yield* Prisma.ComputeApp("App", {
      project,
      serviceName,
      regionId: "us-east-1",
      branchId: branch.branchId,
      path: ".",
      build: {
        // Run Prisma Next setup before the deploy artifact is built. The seed
        // script is idempotent, so repeated deploys refresh the demo data.
        command: "bun run db:setup && bun run build",
        outdir: ".output",
        entrypoint: "server/index.mjs",
        env: {
          DATABASE_URL: databaseUrl,
          DIRECT_URL: databaseUrl,
        },
      },
      port: 3000,
      env: {
        DATABASE_URL: databaseUrl,
        DIRECT_URL: databaseUrl,
        TANSTACK_MESSAGE: message,
        PRISMA_PROJECT_ID: project.projectId,
        PRISMA_BRANCH_ID: branch.branchId,
        PRISMA_DATABASE_ID: postgres.databaseId,
        PRISMA_CONNECTION_ID: connection.connectionId,
      },
      dev: {
        command: "bun run dev:start",
        port: devPort,
        env: {
          TANSTACK_MESSAGE:
            process.env.TANSTACK_MESSAGE ?? "hello from local alchemy dev",
          TANSTACK_SHARED_FLAG: "local-project-level",
          PRISMA_TANSTACK_PG_POOL_MAX: "1",
        },
      },
      destroyOldVersion: true,
    });

    return {
      projectId: project.projectId,
      branchId: branch.branchId,
      databaseId: postgres.databaseId,
      connectionId: connection.connectionId,
      sharedFlagId: sharedFlag.environmentVariableId,
      computeServiceId: app.computeServiceId,
      computeVersionId: app.computeVersionId,
      url: app.url,
    };
  }),
);
