import * as Alchemy from "alchemy";
import * as Prisma from "alchemy/Prisma";
import * as Config from "effect/Config";
import * as Effect from "effect/Effect";
import * as Redacted from "effect/Redacted";

const tanstackMessageConfig = (fallback: string) =>
  Config.string("TANSTACK_MESSAGE").pipe(Effect.orElseSucceed(() => fallback));

export default Alchemy.Stack(
  "PrismaTanstackStart",
  {
    providers: Prisma.providers(),
    state: Alchemy.localState(),
  },
  Effect.gen(function* () {
    const appName = yield* Config.string("PRISMA_TANSTACK_APP").pipe(
      Effect.orElseSucceed(() => "alchemy-prisma-tanstack-start"),
    );
    const customDomainHostname = yield* Config.string(
      "PRISMA_TANSTACK_DOMAIN",
    ).pipe(Effect.orElseSucceed(() => undefined));

    // Project is the Prisma Console container for everything else in this
    // stack: branches, databases, connections, env vars, and Apps.
    // `createDatabase: false` keeps the example explicit so the database below
    // is visible as its own Alchemy resource.
    const project = yield* Prisma.Project("Project", {
      name: yield* Config.string("PRISMA_PROJECT").pipe(
        Effect.orElseSucceed(() => `${appName}-project`),
      ),
      createDatabase: false,
      region: "eu-west-3",
    });

    // Branch is optional for a minimal database-only app, but useful once
    // Compute is involved. It gives the database and App the same
    // deployment lane, so later you can model `main`, preview branches, or prod
    // promotion without changing the app env contract.
    const branch = yield* Prisma.Branch("MainBranch", {
      project,
      gitName: "main",
      isDefault: true,
    });

    // Postgres is the product-shaped alias for Prisma.Database. In deploy it
    // creates a real Prisma Postgres database and attaches it to the branch
    // above. In `alchemy dev`, the `dev` block starts a local Prisma Postgres
    // via `@prisma/dev` and returns the same connection-string attributes.
    const postgres = yield* Prisma.Postgres("Postgres", {
      project,
      region: "eu-west-3",
      branchId: branch.branchId,
      dev: {
        provider: "@prisma/dev",
        // Local dev should boot into a useful app, not an empty shell. This
        // command runs after @prisma/dev is ready, with DATABASE_URL pointed at
        // the direct local Postgres URL.
        migrate: "bun run db:setup",
      },
    });

    // Connection creates the app-facing database credentials. Its returned
    // strings are redacted in Alchemy state. In dev mode it mirrors the local
    // `@prisma/dev` URLs from Postgres, so the app keeps the same env names.
    const connection = yield* Prisma.Connection("Connection", {
      database: postgres,
      name: "web",
    });

    // EnvironmentVariable is for project-level config managed by Prisma. Both
    // it and Compute.env below reconcile branch-scoped Management API values;
    // use a standalone resource when ownership should remain independent.
    const sharedFlag = yield* Prisma.EnvironmentVariable("SharedFlag", {
      project,
      class: "production",
      key: "TANSTACK_SHARED_FLAG",
      value: Redacted.make("project-level"),
    });

    // The application uses the pooled URL for normal traffic and the direct
    // URL for migrations. `connectionEnv` supplies those canonical choices as
    // DATABASE_URL and DIRECT_URL respectively.
    const databaseEnv = Prisma.connectionEnv(connection);

    // Compute builds the TanStack Start app, uploads the `.output` artifact
    // to Prisma Compute, and promotes a Deployment. The env block is the runtime
    // contract for deploy; the dev block runs Vite locally while reusing the
    // same database/project IDs generated by the resources above.
    const app = yield* Prisma.Compute("App", {
      project,
      appName,
      regionId: "eu-west-3",
      branchId: branch.branchId,
      path: ".",
      build: {
        // Run Prisma Next setup before the deploy artifact is built. The seed
        // script is idempotent, so repeated deploys refresh the demo data.
        command: "bun run db:setup && bun run build",
        outdir: ".output",
        entrypoint: "server/index.mjs",
        env: {
          // Contract application and seeding must use the direct endpoint;
          // the runtime env below keeps DATABASE_URL pooled for app traffic.
          DATABASE_URL: databaseEnv.DIRECT_URL,
          DIRECT_URL: databaseEnv.DIRECT_URL,
        },
      },
      port: 3000,
      env: {
        ...databaseEnv,
        TANSTACK_MESSAGE: yield* tanstackMessageConfig(
          "hello from TanStack Start on Prisma Compute",
        ),
        PRISMA_PROJECT_ID: project.projectId,
        PRISMA_BRANCH_ID: branch.branchId,
      },
      dev: {
        command: "bun run dev:start",
        env: {
          TANSTACK_MESSAGE: yield* tanstackMessageConfig(
            "hello from local alchemy dev",
          ),
          TANSTACK_SHARED_FLAG: "local-project-level",
          PRISMA_TANSTACK_PG_POOL_MAX: "1",
        },
      },
      destroyOldDeployment: true,
    });

    const customDomain = customDomainHostname
      ? yield* Prisma.CustomDomain("CustomDomain", {
          app: app.appId,
          hostname: customDomainHostname,
        })
      : undefined;

    return {
      projectId: project.projectId,
      branchId: branch.branchId,
      databaseId: postgres.databaseId,
      connectionId: connection.connectionId,
      sharedFlagId: sharedFlag.environmentVariableId,
      appId: app.appId,
      deploymentId: app.deploymentId,
      url: app.url,
      customDomainId: customDomain?.customDomainId,
      customDomainHostname: customDomain?.hostname,
      customDomainStatus: customDomain?.status,
      customDomainDnsRecords: customDomain?.dnsRecords,
    };
  }),
);
