import * as dps from "@distilled.cloud/azure/deviceprovisioningservices";
import * as Effect from "effect/Effect";
import * as Redacted from "effect/Redacted";
import { Unowned } from "../../AdoptPolicy.ts";
import { isResolved } from "../../Diff.ts";
import * as Provider from "../../Provider.ts";
import { Resource } from "../../Resource.ts";
import {
  desiredTags,
  ensureRegistered,
  hasAnyAlchemyTag,
  ignoreNotFound,
  isOwned,
  requireSinglePage,
  resourceGroupOf,
  tagsDiffer,
  userTags,
  waitForProvisioned,
  waitUntilGone,
} from "../Arm.ts";
import { AzureEnvironment } from "../Environment.ts";
import type { Providers } from "../Providers.ts";
import {
  createProvisioningServiceName,
  getProvisioningService,
  retryWhileTransitioning,
  sameName,
} from "./Common.ts";

/** Rights of a provisioning service shared access policy. */
export type ProvisioningServiceAccessRights =
  | "ServiceConfig"
  | "EnrollmentRead"
  | "EnrollmentWrite"
  | "DeviceConnect"
  | "RegistrationStatusRead"
  | "RegistrationStatusWrite"
  | (string & {});

/** An IoT hub linked to a provisioning service. */
export interface ProvisioningServiceIotHub {
  /**
   * Service connection string of the hub, e.g.
   * `Azure.IoTHub.IotHub(...).primaryConnectionString`. Required for
   * `KeyBased` authentication.
   */
  connectionString?: string | Redacted.Redacted<string>;
  /**
   * Host name of the hub (`{name}.azure-devices.net`). Required when
   * `connectionString` is omitted (identity-based linking).
   */
  hostName?: string;
  /** Azure location of the hub. */
  location: string;
  /** Whether the service's allocation policy applies to this hub. */
  applyAllocationPolicy?: boolean;
  /** Weight of this hub for the `Hashed` allocation policy. */
  allocationWeight?: number;
  /**
   * How the service authenticates to the hub.
   * @default "KeyBased"
   */
  authenticationType?: "KeyBased" | "UserAssigned" | "SystemAssigned";
  /**
   * ARM ID of the user-assigned identity used to reach the hub; required
   * when `authenticationType` is `UserAssigned`.
   */
  selectedUserAssignedIdentityResourceId?: string;
}

export interface ProvisioningServiceProps {
  /** Resource group the service is created in. Changing it replaces the service. */
  resourceGroup: string;
  /**
   * Globally unique service name (`{name}.azure-devices-provisioning.net`):
   * 3-50 letters, digits, and hyphens. If omitted, a unique name is
   * generated from the app, stage, and logical ID. Changing it replaces the
   * service.
   */
  name?: string;
  /**
   * Azure location of the service. Changing it replaces the service.
   * @default the `Azure.Location` layer, else the profile location, else `eastus`
   */
  location?: string;
  /**
   * Number of `S1` units (the only SKU; billed per operation).
   * @default 1
   */
  capacity?: number;
  /**
   * How devices are assigned to linked hubs: `Hashed` (evenly weighted),
   * `GeoLatency` (lowest latency), or `Static` (enrollment decides).
   * @default "Hashed"
   */
  allocationPolicy?: "Hashed" | "GeoLatency" | "Static";
  /**
   * IoT hubs devices can be provisioned to. When omitted the service keeps
   * its currently linked hubs.
   */
  iotHubs?: ProvisioningServiceIotHub[];
  /** Whether the public endpoint accepts traffic. */
  publicNetworkAccess?: "Enabled" | "Disabled";
  /** IP filter rules. */
  ipFilterRules?: {
    /** Rule name. */
    filterName: string;
    /** `Accept` or `Reject`. */
    action: "Accept" | "Reject";
    /** Address range in CIDR notation. */
    ipMask: string;
    /** Endpoint the rule applies to. @default "all" */
    target?: "all" | "serviceApi" | "deviceApi";
  }[];
  /**
   * Shared access policies. When omitted the service keeps its current
   * policies (by default only `provisioningserviceowner`). Existing keys
   * are preserved for policies whose keys are not given.
   */
  authorizationPolicies?: {
    /** Policy name. */
    keyName: string;
    /** Rights, e.g. `"ServiceConfig, EnrollmentRead"`. */
    rights: ProvisioningServiceAccessRights;
    /** Primary key. Generated by Azure when omitted. */
    primaryKey?: string;
    /** Secondary key. Generated by Azure when omitted. */
    secondaryKey?: string;
  }[];
  /**
   * Keep data in the service's region (disables cross-geo disaster
   * recovery). Set only at creation; changing it replaces the service.
   */
  enableDataResidency?: boolean;
  /** Reject SAS authentication (Entra ID only). */
  disableLocalAuth?: boolean;
  /** Managed identities of the service (for identity-based hub linking). */
  identity?: {
    /** Identity type. */
    type:
      | "None"
      | "SystemAssigned"
      | "UserAssigned"
      | "SystemAssigned,UserAssigned";
    /** ARM IDs of user-assigned identities. */
    userAssignedIdentities?: string[];
  };
  /**
   * User tags. Alchemy ownership tags (`alchemy::stack`, `alchemy::stage`,
   * `alchemy::id`) are merged in automatically.
   */
  tags?: Record<string, string>;
}

export interface ProvisioningService extends Resource<
  "Azure.IoT.ProvisioningService",
  ProvisioningServiceProps,
  {
    /** Name of the service. */
    provisioningServiceName: string;
    /** ARM resource ID of the service; use it as a role-assignment scope. */
    provisioningServiceId: string;
    /** Resource group that holds the service. */
    resourceGroup: string;
    /** Location of the service. */
    location: string;
    /** Number of `S1` units. */
    capacity: number | undefined;
    /** ID scope devices use to register, e.g. `0ne00A1B2C3`. */
    idScope: string | undefined;
    /** Service API host name (enrollment management). */
    serviceOperationsHostName: string | undefined;
    /** Global device endpoint, e.g. `global.azure-devices-provisioning.net`. */
    deviceProvisioningHostName: string | undefined;
    /** Service state, e.g. `Active`. */
    state: string | undefined;
    /** Allocation policy in effect. */
    allocationPolicy: string | undefined;
    /** Host names of the linked IoT hubs. */
    iotHubHostNames: string[];
    /** Principal ID of the system-assigned identity, if enabled. */
    principalId: string | undefined;
    /** Primary key of the `provisioningserviceowner` policy. */
    primaryKey: Redacted.Redacted<string> | undefined;
    /**
     * Service connection string of the `provisioningserviceowner` policy
     * (`HostName=…;SharedAccessKeyName=provisioningserviceowner;SharedAccessKey=…`).
     */
    primaryConnectionString: Redacted.Redacted<string> | undefined;
    /** User tags (Alchemy ownership tags stripped). */
    tags: Record<string, string>;
  },
  never,
  Providers
> {}

/**
 * An Azure IoT Hub Device Provisioning Service (DPS) — zero-touch,
 * just-in-time provisioning of devices to one or more linked IoT hubs. The
 * only SKU (`S1`) has no fixed fee; it is billed per 1,000 operations.
 *
 * @see https://learn.microsoft.com/azure/iot-dps/about-iot-dps
 *
 * ### Creating a Provisioning Service
 * **Example:** Standalone service
 * ```typescript
 * const group = yield* Azure.Resources.ResourceGroup("app");
 * const dps = yield* Azure.IoT.ProvisioningService("dps", {
 *   resourceGroup: group.resourceGroupName,
 * });
 * // devices register with dps.idScope at dps.deviceProvisioningHostName
 * ```
 *
 * ### Linking IoT Hubs
 * **Example:** Provision devices to a hub
 * ```typescript
 * const hub = yield* Azure.IoTHub.IotHub("devices", {
 *   resourceGroup: group.resourceGroupName,
 * });
 * const dps = yield* Azure.IoT.ProvisioningService("dps", {
 *   resourceGroup: group.resourceGroupName,
 *   allocationPolicy: "Hashed",
 *   iotHubs: [
 *     {
 *       connectionString: hub.primaryConnectionString,
 *       location: hub.location,
 *     },
 *   ],
 * });
 * ```
 *
 * ### Network Restrictions
 * **Example:** Only accept device traffic from one range
 * ```typescript
 * const dps = yield* Azure.IoT.ProvisioningService("dps", {
 *   resourceGroup: group.resourceGroupName,
 *   ipFilterRules: [
 *     { filterName: "office", action: "Accept", ipMask: "203.0.113.0/24" },
 *   ],
 * });
 * ```
 *
 * @resource
 */
export const ProvisioningService = Resource<ProvisioningService>(
  "Azure.IoT.ProvisioningService",
);

type Observed = dps.GetIotDpsResourceResponse;
type Rule = dps.SharedAccessSignatureAuthorizationRuleAccessRightsDescription;

const OWNER_KEY = "provisioningserviceowner";

const lower = (value: string | undefined) =>
  value?.toLowerCase().replace(/\s/g, "");

const reveal = (value: string | Redacted.Redacted<string> | undefined) =>
  value === undefined
    ? undefined
    : Redacted.isRedacted(value)
      ? Redacted.value(value)
      : value;

/** Host name of a linked hub: explicit, else parsed from its connection string. */
const hubHostName = (hub: ProvisioningServiceIotHub) =>
  hub.hostName ?? reveal(hub.connectionString)?.match(/HostName=([^;]+)/i)?.[1];

/**
 * Ready once ARM reports `Succeeded` and the service itself is `Active`;
 * updates are rejected while it is still activating.
 */
const readiness = (service: Observed) => {
  const provisioning = service.properties?.provisioningState;
  const state = service.properties?.state;
  if (state === "ActivationFailed" || state === "FailingOver") return "Failed";
  if (
    (provisioning === undefined || provisioning === "Succeeded") &&
    state !== undefined &&
    state !== "Active"
  ) {
    return state;
  }
  return provisioning;
};

const toAttrs = (
  resourceGroup: string,
  name: string,
  service: Observed | dps.ProvisioningServiceDescription,
  keys: Rule[] = [],
): ProvisioningService["Attributes"] => {
  const props = service.properties;
  const host = props?.serviceOperationsHostName;
  const key = keys.find((rule) => rule.keyName === OWNER_KEY)?.primaryKey;
  return {
    provisioningServiceName: name,
    provisioningServiceId: service.id ?? "",
    resourceGroup,
    location: service.location,
    capacity: service.sku?.capacity,
    idScope: props?.idScope,
    serviceOperationsHostName: host,
    deviceProvisioningHostName: props?.deviceProvisioningHostName,
    state: props?.state,
    allocationPolicy: props?.allocationPolicy,
    iotHubHostNames: (props?.iotHubs ?? []).flatMap((hub) =>
      (hub.name ?? hub.hostName) ? [(hub.name ?? hub.hostName)!] : [],
    ),
    principalId: service.identity?.principalId,
    primaryKey: key ? Redacted.make(key) : undefined,
    primaryConnectionString:
      key && host
        ? Redacted.make(
            `HostName=${host};SharedAccessKeyName=${OWNER_KEY};SharedAccessKey=${key}`,
          )
        : undefined,
    tags: userTags(service.tags),
  };
};

const listKeys = (
  subscriptionId: string,
  resourceGroupName: string,
  provisioningServiceName: string,
) =>
  dps
    .ListIotDpsResourceKeys({
      subscriptionId,
      resourceGroupName,
      provisioningServiceName,
    })
    .pipe(
      Effect.flatMap((page) =>
        requireSinglePage("ListIotDpsResourceKeys", page),
      ),
      Effect.map((page) => [...(page.value ?? [])]),
    );

const identityInput = (
  identity: ProvisioningServiceProps["identity"],
): dps.IotDpsResourceCreateOrUpdateRequestIdentity | undefined =>
  identity === undefined
    ? undefined
    : {
        type: identity.type,
        userAssignedIdentities: identity.userAssignedIdentities?.length
          ? Object.fromEntries(
              identity.userAssignedIdentities.map((id) => [id, {}]),
            )
          : undefined,
      };

const observedIdentityInput = (
  identity: Observed["identity"],
): dps.IotDpsResourceCreateOrUpdateRequestIdentity | undefined =>
  identity?.type
    ? {
        type: identity.type,
        userAssignedIdentities: identity.userAssignedIdentities
          ? Object.fromEntries(
              Object.keys(identity.userAssignedIdentities).map((key) => [
                key,
                {},
              ]),
            )
          : undefined,
      }
    : undefined;

const identityMatches = (
  desired: ProvisioningServiceProps["identity"],
  observed: Observed["identity"],
) => {
  if (desired === undefined) return true;
  if (lower(desired.type) !== lower(observed?.type ?? "None")) return false;
  const want = (desired.userAssignedIdentities ?? []).map((id) =>
    id.toLowerCase(),
  );
  const have = Object.keys(observed?.userAssignedIdentities ?? {}).map((id) =>
    id.toLowerCase(),
  );
  return want.length === have.length && want.every((id) => have.includes(id));
};

const hubsInput = (
  hubs: ProvisioningServiceIotHub[],
): dps.IotHubDefinitionDescriptionInput[] =>
  hubs.map((hub) => ({
    connectionString: reveal(hub.connectionString),
    hostName: hub.connectionString === undefined ? hub.hostName : undefined,
    location: hub.location,
    applyAllocationPolicy: hub.applyAllocationPolicy,
    allocationWeight: hub.allocationWeight,
    authenticationType: hub.authenticationType,
    selectedUserAssignedIdentityResourceId:
      hub.selectedUserAssignedIdentityResourceId,
  }));

/** Linked hubs as observed (connection strings come back masked). */
const observedHubsInput = (
  hubs: dps.IotHubDefinitionDescription[] | undefined,
): dps.IotHubDefinitionDescriptionInput[] | undefined =>
  hubs?.map((hub) => ({
    connectionString: hub.connectionString,
    hostName: hub.connectionString === undefined ? hub.hostName : undefined,
    location: hub.location,
    applyAllocationPolicy: hub.applyAllocationPolicy,
    allocationWeight: hub.allocationWeight,
    authenticationType: hub.authenticationType,
    selectedUserAssignedIdentityResourceId:
      hub.selectedUserAssignedIdentityResourceId,
  }));

const hubsMatch = (
  desired: ProvisioningServiceIotHub[] | undefined,
  observed: dps.IotHubDefinitionDescription[] | undefined,
) => {
  if (desired === undefined) return true;
  const have = observed ?? [];
  return (
    desired.length === have.length &&
    desired.every((hub) => {
      const host = hubHostName(hub);
      const current = have.find((o) => sameName(o.name ?? o.hostName, host));
      return (
        current !== undefined &&
        sameName(current.location, hub.location) &&
        (hub.applyAllocationPolicy === undefined ||
          hub.applyAllocationPolicy ===
            (current.applyAllocationPolicy ?? false)) &&
        (hub.allocationWeight === undefined ||
          hub.allocationWeight === current.allocationWeight) &&
        (hub.authenticationType === undefined ||
          sameName(
            hub.authenticationType,
            current.authenticationType ?? "KeyBased",
          ))
      );
    })
  );
};

const ipRulesMatch = (
  desired: ProvisioningServiceProps["ipFilterRules"],
  observed: dps.IpFilterRule[] | undefined,
) => {
  if (desired === undefined) return true;
  const have = observed ?? [];
  return (
    desired.length === have.length &&
    desired.every((rule) => {
      const current = have.find((o) => o.filterName === rule.filterName);
      return (
        current !== undefined &&
        current.action === rule.action &&
        current.ipMask === rule.ipMask &&
        sameName(current.target ?? "all", rule.target ?? "all")
      );
    })
  );
};

/**
 * Desired authorization policies with keys filled in from the observed
 * policies, so a PUT never rotates keys the user did not set.
 */
const desiredPolicies = (
  desired: ProvisioningServiceProps["authorizationPolicies"],
  observed: Rule[],
): Rule[] =>
  desired === undefined
    ? observed
    : desired.map((policy) => {
        const current = observed.find((o) => o.keyName === policy.keyName);
        return {
          keyName: policy.keyName,
          rights: policy.rights,
          primaryKey: policy.primaryKey ?? current?.primaryKey,
          secondaryKey: policy.secondaryKey ?? current?.secondaryKey,
        };
      });

const policiesMatch = (
  desired: ProvisioningServiceProps["authorizationPolicies"],
  observed: Rule[],
) =>
  desired === undefined ||
  (desired.length === observed.length &&
    desired.every((policy) => {
      const current = observed.find((o) => o.keyName === policy.keyName);
      return (
        current !== undefined &&
        lower(current.rights) === lower(policy.rights) &&
        (policy.primaryKey === undefined ||
          policy.primaryKey === current.primaryKey) &&
        (policy.secondaryKey === undefined ||
          policy.secondaryKey === current.secondaryKey)
      );
    }));

export const ProvisioningServiceProvider = () =>
  Provider.succeed(ProvisioningService, {
    stables: [
      "provisioningServiceName",
      "provisioningServiceId",
      "resourceGroup",
      "location",
      "idScope",
      "serviceOperationsHostName",
      "deviceProvisioningHostName",
    ],

    list: Effect.fn(function* () {
      const { subscriptionId } = yield* AzureEnvironment.current;
      const page = yield* dps
        .ListIotDpsResourceBySubscription({ subscriptionId })
        .pipe(
          Effect.flatMap((page) =>
            requireSinglePage("ListIotDpsResourceBySubscription", page),
          ),
        );
      return (page.value ?? []).flatMap((service) => {
        const group = resourceGroupOf(service.id);
        return hasAnyAlchemyTag(service.tags) &&
          group !== undefined &&
          service.name !== undefined
          ? [toAttrs(group, service.name, service)]
          : [];
      });
    }),

    diff: Effect.fn(function* ({ news, olds, output }) {
      if (!isResolved(news) || output === undefined) return undefined;
      const replace =
        !sameName(news.resourceGroup, output.resourceGroup) ||
        (news.name !== undefined &&
          !sameName(news.name, output.provisioningServiceName)) ||
        (news.location !== undefined &&
          !sameName(news.location, output.location)) ||
        (olds !== undefined &&
          (news.enableDataResidency ?? false) !==
            (olds.enableDataResidency ?? false));
      if (!replace) return undefined;
      // An explicit name is globally unique: the old service must go before
      // its replacement can take the name.
      const deleteFirst =
        news.name !== undefined &&
        sameName(news.name, output.provisioningServiceName);
      return { action: "replace", deleteFirst } as const;
    }),

    read: Effect.fn(function* ({ id, olds, output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      const resourceGroup = output?.resourceGroup ?? olds?.resourceGroup;
      // An interrupted create can persist props with unresolved holes;
      // nothing can exist without its resource group.
      if (resourceGroup === undefined) return undefined;
      const name =
        output?.provisioningServiceName ??
        olds?.name ??
        (yield* createProvisioningServiceName(id));
      const observed = yield* getProvisioningService(
        subscriptionId,
        resourceGroup,
        name,
      );
      if (observed === undefined) return undefined;
      const attrs = toAttrs(resourceGroup, name, observed);
      return (yield* isOwned(id, observed.tags)) ? attrs : Unowned(attrs);
    }),

    reconcile: Effect.fn(function* ({ id, news, output }) {
      const env = yield* AzureEnvironment.current;
      const { subscriptionId } = env;
      yield* ensureRegistered(subscriptionId, "Microsoft.Devices");
      const resourceGroup = news.resourceGroup;
      const name =
        news.name ??
        output?.provisioningServiceName ??
        (yield* createProvisioningServiceName(id));
      const location = news.location ?? output?.location ?? env.location;
      const tags = yield* desiredTags(id, news.tags);
      const sku = { name: "S1", capacity: news.capacity ?? 1 };
      const where = {
        subscriptionId,
        resourceGroupName: resourceGroup,
        provisioningServiceName: name,
      };
      const get = getProvisioningService(subscriptionId, resourceGroup, name);
      const waitReady = waitForProvisioned(
        `provisioning service ${name}`,
        get,
        readiness,
        { interval: "5 seconds", times: 60 },
      );

      // Observe.
      let observed = yield* get;

      // Ensure. Creation is a long-running operation (~1 minute).
      if (observed === undefined) {
        yield* dps.IotDpsResourceCreateOrUpdate({
          ...where,
          location,
          sku,
          tags,
          identity: identityInput(news.identity),
          properties: {
            allocationPolicy: news.allocationPolicy,
            iotHubs: news.iotHubs ? hubsInput(news.iotHubs) : undefined,
            publicNetworkAccess: news.publicNetworkAccess,
            ipFilterRules: news.ipFilterRules,
            authorizationPolicies: news.authorizationPolicies,
            enableDataResidency: news.enableDataResidency,
            disableLocalAuth: news.disableLocalAuth,
          },
        });
      }
      observed = yield* waitReady;

      // Sync SKU, identity, and properties against observed state. PATCH is
      // tags-only, so any other delta re-sends the full document: observed
      // values with the desired values merged in.
      const props = observed.properties ?? {};
      const keys = yield* listKeys(subscriptionId, resourceGroup, name);
      const propsChanged =
        (news.allocationPolicy !== undefined &&
          news.allocationPolicy !== props.allocationPolicy) ||
        (news.publicNetworkAccess !== undefined &&
          news.publicNetworkAccess !==
            (props.publicNetworkAccess ?? "Enabled")) ||
        (news.disableLocalAuth !== undefined &&
          news.disableLocalAuth !== (props.disableLocalAuth ?? false)) ||
        !ipRulesMatch(news.ipFilterRules, props.ipFilterRules) ||
        !hubsMatch(news.iotHubs, props.iotHubs) ||
        !policiesMatch(news.authorizationPolicies, keys);
      const skuChanged = (observed.sku.capacity ?? 1) !== sku.capacity;
      const identityChanged = !identityMatches(
        news.identity,
        observed.identity,
      );

      if (propsChanged || skuChanged || identityChanged) {
        yield* retryWhileTransitioning(
          dps.IotDpsResourceCreateOrUpdate({
            ...where,
            etag: observed.etag,
            location: observed.location,
            sku,
            tags,
            identity:
              news.identity !== undefined
                ? identityInput(news.identity)
                : observedIdentityInput(observed.identity),
            properties: {
              allocationPolicy: news.allocationPolicy ?? props.allocationPolicy,
              iotHubs: news.iotHubs
                ? hubsInput(news.iotHubs)
                : observedHubsInput(props.iotHubs),
              publicNetworkAccess:
                news.publicNetworkAccess ?? props.publicNetworkAccess,
              ipFilterRules: news.ipFilterRules ?? props.ipFilterRules,
              authorizationPolicies: desiredPolicies(
                news.authorizationPolicies,
                keys,
              ),
              enableDataResidency: props.enableDataResidency,
              disableLocalAuth: news.disableLocalAuth ?? props.disableLocalAuth,
            },
          }),
        );
        observed = yield* waitReady;
      } else if (tagsDiffer(observed.tags, tags)) {
        yield* retryWhileTransitioning(
          dps.UpdateIotDpsResource({ ...where, tags }),
        );
        observed = yield* waitReady;
      }

      const finalKeys =
        news.authorizationPolicies === undefined
          ? keys
          : yield* listKeys(subscriptionId, resourceGroup, name);
      return toAttrs(resourceGroup, name, observed, finalKeys);
    }),

    delete: Effect.fn(function* ({ output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      yield* ignoreNotFound(
        retryWhileTransitioning(
          dps.DeleteIotDpsResource({
            subscriptionId,
            resourceGroupName: output.resourceGroup,
            provisioningServiceName: output.provisioningServiceName,
          }),
        ),
      );
      yield* waitUntilGone(
        `provisioning service ${output.provisioningServiceName}`,
        getProvisioningService(
          subscriptionId,
          output.resourceGroup,
          output.provisioningServiceName,
        ),
        { interval: "5 seconds", times: 60 },
      );
    }),

    nuke: {
      dependsOn: ["Azure.Resources.ResourceGroup"],
    },
  });
