import {
  DeleteProductsId,
  GetProducts,
  GetProductsId,
  PostProducts,
  PostProductsId,
  type PostProductsIdRequest,
  type Product as StripeProduct,
} from "@distilled.cloud/stripe/stripe";
import * as Effect from "effect/Effect";
import { Unowned } from "../AdoptPolicy.ts";
import { isResolved } from "../Diff.ts";
import * as Provider from "../Provider.ts";
import { Resource } from "../Resource.ts";
import {
  brandMetadata,
  isOwned,
  type Metadata,
  metadataEqual,
  metadataUpdate,
  stripInternalMetadata,
} from "./Metadata.ts";
import type { Providers } from "./Providers.ts";

/**
 * Physical dimensions of a shippable product, used by Stripe to compute
 * shipping rates. All measurements are imperial (inches / ounces) with a
 * maximum precision of two decimal places.
 */
export type ProductPackageDimensions = {
  /** Height, in inches. */
  height: number;
  /** Length, in inches. */
  length: number;
  /** Weight, in ounces. */
  weight: number;
  /** Width, in inches. */
  width: number;
};

/** A single marketing feature bullet displayed in Stripe pricing tables. */
export type ProductMarketingFeature = {
  /** The marketing feature name. Up to 80 characters long. */
  name: string;
};

/**
 * The type of the product. `service` products work with Subscriptions and
 * Plans; `good` products work with Orders and SKUs.
 */
export type ProductType = "good" | "service";

export type ProductProps = {
  /**
   * The Stripe object ID to create the product under (e.g. `prod_basic`).
   * Must be unique across every product in the Stripe account.
   *
   * When omitted, Stripe generates a random `prod_…` ID. Changing this to a
   * different explicit ID **replaces** the product. Removing it after
   * creation keeps the existing product — Alchemy will not throw the object
   * away just because you stopped pinning its ID.
   *
   * @default - generated by Stripe
   */
  id?: string;
  /**
   * The product's name, displayed to customers on invoices, receipts,
   * Checkout and the customer portal.
   *
   * @default - the resource's logical ID
   */
  name?: string;
  /**
   * A long-form description of the product, displayable to the customer.
   * Setting this to `undefined` after it was set unsets it in Stripe.
   */
  description?: string;
  /**
   * Whether the product is available for purchase. Archived (`false`)
   * products remain visible in the dashboard but cannot be purchased.
   *
   * @default true
   */
  active?: boolean;
  /**
   * Up to 8 URLs of images for this product, displayable to the customer.
   *
   * @default []
   */
  images?: string[];
  /**
   * Up to 15 marketing features for this product, displayed in
   * [pricing tables](https://docs.stripe.com/payments/checkout/pricing-table).
   *
   * @default []
   */
  marketingFeatures?: ProductMarketingFeature[];
  /**
   * The dimensions of this product for shipping purposes.
   */
  packageDimensions?: ProductPackageDimensions;
  /**
   * Whether this product is shipped (i.e. represents physical goods).
   */
  shippable?: boolean;
  /**
   * An arbitrary string (up to 22 characters) displayed on the customer's
   * credit card or bank statement. Only used for subscription payments, and
   * may only be set when `type` is `"service"`.
   */
  statementDescriptor?: string;
  /**
   * A [tax code](https://docs.stripe.com/tax/tax-categories) ID
   * (e.g. `txcd_10000000`) used by Stripe Tax to categorise this product.
   */
  taxCode?: string;
  /**
   * A label representing units of this product (e.g. `"seat"`). Included in
   * receipts, invoices, Checkout and the customer portal. May only be set
   * when `type` is `"service"`.
   */
  unitLabel?: string;
  /**
   * A URL of a publicly-accessible webpage for this product.
   */
  url?: string;
  /**
   * The type of the product. Stripe does not allow changing the type after
   * creation, so a change here **replaces** the product.
   *
   * @default "service"
   */
  type?: ProductType;
  /**
   * Arbitrary key-value pairs attached to the product. Alchemy additionally
   * writes three reserved `alchemy_*` keys used to identify the objects it
   * owns; those are stripped from the `metadata` attribute so a no-op deploy
   * never reports phantom drift.
   */
  metadata?: Record<string, string>;
};

export type Product = Resource<
  "Stripe.Product",
  ProductProps,
  {
    /** The Stripe object ID of the product (e.g. `prod_NWjs8kKbJWmuuc`). */
    productId: string;
    /** The product's customer-facing name. */
    name: string;
    /** The product's long-form description, or `undefined` when unset. */
    description: string | undefined;
    /** Whether the product is currently available for purchase. */
    active: boolean;
    /** URLs of the product's images. */
    images: string[];
    /** Marketing feature bullets shown in pricing tables. */
    marketingFeatures: ProductMarketingFeature[];
    /** Shipping dimensions, or `undefined` when unset. */
    packageDimensions: ProductPackageDimensions | undefined;
    /** Whether the product is shipped, or `undefined` when unset. */
    shippable: boolean | undefined;
    /** The statement descriptor, or `undefined` when unset. */
    statementDescriptor: string | undefined;
    /** The Stripe Tax tax code ID, or `undefined` when unset. */
    taxCode: string | undefined;
    /** The type of the product. Immutable after creation. */
    type: ProductType;
    /** The unit label, or `undefined` when unset. */
    unitLabel: string | undefined;
    /** The product's public webpage URL, or `undefined` when unset. */
    url: string | undefined;
    /**
     * The ID of the {@link Price} currently set as this product's default
     * price, or `undefined` when none is set. Read-only — Alchemy never
     * writes `default_price`; manage prices with `Stripe.Price`.
     */
    defaultPriceId: string | undefined;
    /** The user-facing metadata, with alchemy's reserved keys stripped. */
    metadata: Record<string, string>;
    /** `true` when the object lives in the account's live mode. */
    livemode: boolean;
    /** Creation time, in seconds since the Unix epoch. */
    created: number;
  },
  never,
  Providers
>;

type ProductAttributes = Product["Attributes"];

/**
 * A Stripe Product — the specific good or service you offer to customers.
 * Products are combined with one or more `Stripe.Price` objects to configure
 * pricing in Payment Links, Checkout and Subscriptions.
 *
 * Alchemy brands every product it creates with reserved `alchemy_*`
 * `metadata` keys (Stripe has no tagging API). That branding is how a lost
 * state row re-discovers its product instead of creating a duplicate, and how
 * adoption decides whether a pre-existing product belongs to this stack.
 *
 * :::caution
 * `DELETE /v1/products/{id}` only succeeds while the product has **no prices
 * attached**. Once a price exists, Stripe rejects the delete with an
 * `invalid_request_error`. Destroying this resource therefore deletes the
 * product when it can, and otherwise falls back to **archiving** it
 * (`active: false`) — the product stays visible in the dashboard and in list
 * calls, but cannot be purchased.
 * :::
 *
 * :::caution
 * `type` and an explicitly pinned `id` are immutable in Stripe. Changing
 * either **replaces** the product: a new object is created and the old one is
 * deleted (or archived, per the note above).
 * :::
 *
 * ### Creating a Product
 * **Example:** Minimal product
 * ```typescript
 * const product = yield* Stripe.Product("pro-plan");
 * ```
 *
 * **Example:** Product with a stable, human-readable Stripe ID
 * ```typescript
 * const product = yield* Stripe.Product("pro-plan", {
 *   id: "prod_pro_plan",
 *   name: "Pro Plan",
 *   description: "Everything in Free, plus unlimited seats.",
 * });
 * ```
 *
 * ### Configuring a Product
 * **Example:** Fully-configured physical good
 * ```typescript
 * const widget = yield* Stripe.Product("deluxe-widget", {
 *   name: "Deluxe Widget",
 *   description: "A widget, but deluxe.",
 *   type: "good",
 *   shippable: true,
 *   images: ["https://example.com/widget.png"],
 *   packageDimensions: { height: 2, length: 6, weight: 12, width: 4 },
 *   url: "https://example.com/widgets/deluxe",
 *   taxCode: "txcd_99999999",
 *   metadata: { sku: "WGT-DLX-001" },
 * });
 * ```
 *
 * **Example:** Subscription service with marketing features
 * ```typescript
 * const plan = yield* Stripe.Product("team-plan", {
 *   name: "Team Plan",
 *   type: "service",
 *   unitLabel: "seat",
 *   statementDescriptor: "ACME TEAM",
 *   marketingFeatures: [
 *     { name: "Unlimited projects" },
 *     { name: "Priority support" },
 *   ],
 * });
 * ```
 *
 * ### Archiving a Product
 * **Example:** Take a product off sale without destroying it
 * ```typescript
 * const legacy = yield* Stripe.Product("legacy-plan", {
 *   name: "Legacy Plan",
 *   active: false,
 * });
 * ```
 *
 * ### Composing with Prices
 * **Example:** Attach a recurring price to the product
 * ```typescript
 * const product = yield* Stripe.Product("pro-plan", { name: "Pro Plan" });
 *
 * const price = yield* Stripe.Price("pro-plan-monthly", {
 *   productId: product.productId,
 *   currency: "usd",
 *   unitAmount: 2000,
 *   recurring: { interval: "month" },
 * });
 * ```
 *
 * @see https://docs.stripe.com/api/products
 *
 * @resource
 */
export const Product = Resource<Product>("Stripe.Product");

export const ProductProvider = () =>
  Provider.succeed(Product, {
    stables: ["productId", "type", "livemode", "created"],
    list: Effect.fn(function* () {
      const products = yield* listAllProducts;
      return products.map(productAttributes);
    }),
    diff: Effect.fn(function* ({ news, output }) {
      if (!isResolved(news)) return undefined;
      // `id` and `type` are the only immutable aspects of a Stripe Product;
      // every other field in `PostProductsIdRequest` updates in place.
      //
      // A pinned `id` that no longer matches the deployed object forces a
      // replacement. Dropping the pin entirely does NOT — the deployed
      // product is still a perfectly good "Stripe-generated id" product, and
      // throwing it away (deleting/archiving a live catalog entry) to satisfy
      // a cosmetic prop removal would be far more destructive than useful.
      if (news.id !== undefined && news.id !== output?.productId) {
        return { action: "replace" } as const;
      }
      if ((news.type ?? "service") !== (output?.type ?? "service")) {
        return { action: "replace" } as const;
      }
      return undefined;
    }),
    read: Effect.fn(function* ({ id, olds, output }) {
      const pinned = output?.productId ?? olds?.id;
      if (pinned !== undefined) {
        const product = yield* getProduct(pinned);
        if (!product) return undefined;
        return (yield* isOwned(id, observedMetadata(product.metadata)))
          ? productAttributes(product)
          : Unowned(productAttributes(product));
      }
      // State loss with no pinned id: re-discover the product by its alchemy
      // branding so a lost state row adopts rather than duplicating.
      const products = yield* listAllProducts;
      for (const product of products) {
        if (yield* isOwned(id, observedMetadata(product.metadata))) {
          return productAttributes(product);
        }
      }
      return undefined;
    }),
    reconcile: Effect.fn(function* ({ id, news, output }) {
      const desiredMetadata = yield* brandMetadata(id, news.metadata);
      const name = news.name ?? id;

      // 1. Observe — the deployed identifier is a cache, never proof the
      //    object still exists.
      const identifier = output?.productId ?? news.id;
      const observed = identifier ? yield* getProduct(identifier) : undefined;

      // 2. Ensure — create when nothing is out there.
      const pinnedId = news.id;
      const current =
        observed ??
        (yield* PostProducts({
          name,
          ...(pinnedId !== undefined ? { id: pinnedId } : {}),
          active: news.active ?? true,
          type: news.type ?? "service",
          metadata: desiredMetadata,
          ...(news.description !== undefined
            ? { description: news.description }
            : {}),
          ...(news.images !== undefined ? { images: [...news.images] } : {}),
          ...(news.marketingFeatures !== undefined
            ? {
                marketing_features: news.marketingFeatures.map((f) => ({
                  name: f.name,
                })),
              }
            : {}),
          ...(news.packageDimensions !== undefined
            ? { package_dimensions: { ...news.packageDimensions } }
            : {}),
          ...(news.shippable !== undefined
            ? { shippable: news.shippable }
            : {}),
          ...(news.statementDescriptor !== undefined
            ? { statement_descriptor: news.statementDescriptor }
            : {}),
          ...(news.taxCode !== undefined ? { tax_code: news.taxCode } : {}),
          ...(news.unitLabel !== undefined
            ? { unit_label: news.unitLabel }
            : {}),
          ...(news.url !== undefined ? { url: news.url } : {}),
        }).pipe(
          Effect.catchTag("InvalidRequestError", (e) =>
            // Lost a create/create race on an explicitly-pinned id: the
            // object is already there, so pick it up and let the sync step
            // below converge it. Not a failure.
            e.code === "resource_already_exists" && pinnedId !== undefined
              ? GetProductsId({ id: pinnedId })
              : Effect.fail(e),
          ),
        ));

      // 3. Sync — diff desired against OBSERVED cloud state and apply only
      //    the delta. On a fresh create the delta is empty, so no second
      //    API call is made.
      const update = buildProductUpdate(news, name, desiredMetadata, current);
      const final =
        Object.keys(update).length === 0
          ? current
          : yield* PostProductsId({ id: current.id, ...update });

      return productAttributes(final);
    }),
    delete: Effect.fn(function* ({ output }) {
      const productId = output.productId;
      yield* DeleteProductsId({ id: productId }).pipe(
        Effect.asVoid,
        Effect.catchTag("NotFound", () => Effect.void),
        Effect.catchTag("InvalidRequestError", (e) =>
          // `resource_missing` — already gone, deletion is idempotent.
          // Anything else here is Stripe refusing to delete a product that
          // still has prices attached; archive instead.
          e.code === "resource_missing"
            ? Effect.void
            : archiveProduct(productId),
        ),
        Effect.catchTag("BadRequest", () => archiveProduct(productId)),
      );
    }),
  });

/**
 * The maximum number of 100-item pages walked when enumerating products.
 * Bounded so a pathological account can never spin the loop forever.
 */
const MAX_PRODUCT_PAGES = 100;

/** Exhaustively enumerate every product (active and archived). */
const listAllProducts = Effect.gen(function* () {
  const products: StripeProduct[] = [];
  let startingAfter: string | undefined;
  for (let page = 0; page < MAX_PRODUCT_PAGES; page++) {
    const response = yield* GetProducts({
      limit: 100,
      ...(startingAfter !== undefined ? { starting_after: startingAfter } : {}),
    });
    products.push(...response.data);
    const last = response.data[response.data.length - 1];
    if (!response.has_more || last === undefined) break;
    startingAfter = last.id;
  }
  return products;
});

/**
 * Fetch a product, mapping "missing" to `undefined`.
 *
 * Stripe answers a lookup for a deleted object with HTTP 404 and an envelope
 * whose `type` is `invalid_request_error`; distilled dispatches on `type`
 * before status, so the failure surfaces as `InvalidRequestError` (with
 * `code === "resource_missing"`) rather than `NotFound`. Both are handled.
 */
const getProduct = (productId: string) =>
  GetProductsId({ id: productId }).pipe(
    Effect.map((product): StripeProduct | undefined => product),
    Effect.catchTag("NotFound", () => Effect.succeed(undefined)),
    Effect.catchTag("InvalidRequestError", (e) =>
      e.code === "resource_missing"
        ? Effect.succeed(undefined)
        : Effect.fail(e),
    ),
  );

/** Archive a product (`active: false`). Idempotent — missing is success. */
const archiveProduct = (productId: string) =>
  PostProductsId({ id: productId, active: false }).pipe(
    Effect.asVoid,
    Effect.catchTag("NotFound", () => Effect.void),
    Effect.catchTag("InvalidRequestError", (e) =>
      e.code === "resource_missing" ? Effect.void : Effect.fail(e),
    ),
  );

/** Stripe returns expandable references as either an ID string or an object. */
const referenceId = (
  value: string | { id: string } | null | undefined,
): string | undefined =>
  value == null ? undefined : typeof value === "string" ? value : value.id;

const nullToUndefined = <T>(value: T | null | undefined): T | undefined =>
  value ?? undefined;

/**
 * Stripe's metadata maps are typed with `string | undefined` values; narrow
 * them to the plain `Record<string, string>` the `Metadata` helpers expect.
 */
const observedMetadata = (
  metadata: { readonly [key: string]: string | undefined } | null | undefined,
): Metadata =>
  Object.fromEntries(
    Object.entries(metadata ?? {}).filter(
      (entry): entry is [string, string] => entry[1] !== undefined,
    ),
  );

const stringsEqual = (
  a: readonly string[],
  b: readonly string[] | undefined,
): boolean =>
  b !== undefined && a.length === b.length && a.every((v, i) => v === b[i]);

const featuresEqual = (
  a: readonly ProductMarketingFeature[],
  b: readonly { name?: string }[] | undefined,
): boolean =>
  b !== undefined &&
  a.length === b.length &&
  a.every((v, i) => v.name === (b[i]?.name ?? ""));

const dimensionsEqual = (
  a: ProductPackageDimensions | undefined,
  b: ProductPackageDimensions | null | undefined,
): boolean => {
  if (a === undefined) return b == null;
  if (b == null) return false;
  return (
    a.height === b.height &&
    a.length === b.length &&
    a.weight === b.weight &&
    a.width === b.width
  );
};

/** The mutable half of `POST /v1/products/{id}`. */
type ProductUpdate = Omit<PostProductsIdRequest, "id">;

/**
 * Compute the delta between the desired props and the **observed** product.
 * Only the changed fields appear in the result, so a converged product costs
 * zero write calls.
 *
 * Stripe unsets an optional field when it is posted as an empty string, so a
 * prop the user removed is sent as `""` rather than simply omitted.
 */
const buildProductUpdate = (
  news: ProductProps,
  name: string,
  desiredMetadata: Metadata,
  observed: StripeProduct,
): ProductUpdate => {
  const update: ProductUpdate = {};

  if (name !== observed.name) update.name = name;

  const active = news.active ?? true;
  if (active !== observed.active) update.active = active;

  const description = news.description ?? "";
  if (description !== (observed.description ?? "")) {
    update.description = description;
  }

  const statementDescriptor = news.statementDescriptor ?? "";
  if (statementDescriptor !== (observed.statement_descriptor ?? "")) {
    update.statement_descriptor = statementDescriptor;
  }

  const unitLabel = news.unitLabel ?? "";
  if (unitLabel !== (observed.unit_label ?? "")) {
    update.unit_label = unitLabel;
  }

  const url = news.url ?? "";
  if (url !== (observed.url ?? "")) update.url = url;

  const taxCode = news.taxCode ?? "";
  if (taxCode !== (referenceId(observed.tax_code) ?? "")) {
    update.tax_code = taxCode;
  }

  const images = news.images ?? [];
  if (!stringsEqual(images, observed.images)) {
    // An empty array form-encodes to nothing at all, which Stripe reads as
    // "leave unchanged" — post `""` to actually clear the list.
    update.images = images.length === 0 ? "" : [...images];
  }

  const features = news.marketingFeatures ?? [];
  if (!featuresEqual(features, observed.marketing_features)) {
    update.marketing_features =
      features.length === 0 ? "" : features.map((f) => ({ name: f.name }));
  }

  if (!dimensionsEqual(news.packageDimensions, observed.package_dimensions)) {
    update.package_dimensions =
      news.packageDimensions === undefined ? "" : { ...news.packageDimensions };
  }

  if (news.shippable === undefined) {
    if (observed.shippable != null) update.shippable = "";
  } else if (news.shippable !== observed.shippable) {
    update.shippable = news.shippable;
  }

  // Metadata is diffed against OBSERVED cloud state (adoption can hand us a
  // product whose metadata doesn't match anything we persisted), and applied
  // through `metadataUpdate` so keys the user removed are actually unset.
  const currentMetadata = observedMetadata(observed.metadata);
  if (!metadataEqual(currentMetadata, desiredMetadata)) {
    update.metadata = metadataUpdate(currentMetadata, desiredMetadata);
  }

  return update;
};

/** Project a Stripe product onto the resource's Attributes shape. */
const productAttributes = (product: StripeProduct): ProductAttributes => ({
  productId: product.id,
  name: product.name,
  description: nullToUndefined(product.description),
  active: product.active,
  images: [...product.images],
  marketingFeatures: product.marketing_features.map((f) => ({
    name: f.name ?? "",
  })),
  packageDimensions: nullToUndefined(product.package_dimensions),
  shippable: nullToUndefined(product.shippable),
  statementDescriptor: nullToUndefined(product.statement_descriptor),
  taxCode: referenceId(product.tax_code),
  type: product.type,
  unitLabel: nullToUndefined(product.unit_label),
  url: nullToUndefined(product.url),
  defaultPriceId: referenceId(product.default_price),
  metadata: stripInternalMetadata(observedMetadata(product.metadata)),
  livemode: product.livemode,
  created: product.created,
});
