/**
 * Effectful (mount-design) worker-entry delivery for
 * `Cloudflare.Website.Waku` — Serve/DESIGN.md tier A, the waku analogue of
 * alchemy's `virtual:alchemy:website-entry` plugin for the generic vite
 * integration (and of the Astro entry takeover in `../astro/entry-plugin.ts`).
 *
 * Waku's mount idiom is the **framework hook**: a waku middleware module
 * (`src/middleware/*.ts` in managed mode) owns HTTP composition —
 * `site.fetch(request) ?? next()` — and runs natively in dev and prod on
 * every platform. The worker ENTRY therefore only needs what the hook
 * cannot provide: the non-fetch dispatch (queue consumers, schedules,
 * workerd JS-RPC) and the DO/Workflow class exports the program registered.
 * This plugin serves a generated virtual module as the Cloudflare vite
 * plugin's `main`:
 *
 * ```js
 * import { makeWebsiteEntryExports, DurableObjectBridge } from "alchemy/Cloudflare/Serve";
 * import { WorkerEntrypoint, DurableObject } from "cloudflare:workers";
 * import __wakuEntry from "virtual:waku/server-entry";
 * import Site from "/abs/path/to/src/backend.ts";
 * export default makeWebsiteEntryExports(WorkerEntrypoint, {
 *   site: Site,
 *   fetch: (request, env, ctx) => __wakuEntry.fetch(request, env, ctx),
 * });
 * const Bridge = DurableObjectBridge(DurableObject, { site: Site });
 * export class Counter extends Bridge("Counter") {}
 * ```
 *
 * The framework's fetch is grafted VERBATIM — waku's own handler pipeline
 * (with the user's mount middleware inside it) serves every request; the
 * wrapper never gates or re-bridges HTTP. Content is a pure function of the
 * plan-time registration data ({@link WakuEffectOptions}); nothing is ever
 * decided by inspecting build output.
 *
 * This module deliberately has no alchemy import (the generated code's bare
 * `alchemy/Cloudflare/Serve` specifier resolves from the *project's* install,
 * inside the one worker bundle waku produces).
 */
import type * as ViteModule from "vite";
import { WAKU_SERVER_ENTRY_ID } from "./Waku.ts";

/**
 * The virtual module id of the generated effectful-Website worker entry.
 * Set as the Cloudflare vite plugin's `main`; the plugin passes virtual ids
 * through untouched and wraps them in its `\0distilled:worker-entry:`
 * module, so unenv injection and the dev HMR handshake apply to the wrapper
 * exactly as to a file entry.
 */
export const WEBSITE_ENTRY_ID = "virtual:alchemy:website-entry";
const RESOLVED_WEBSITE_ENTRY_ID = `\0${WEBSITE_ENTRY_ID}`;

/**
 * Plain-data description of the effectful delivery — everything the
 * generated wrapper needs, kept JSON-serializable so it can cross the
 * engine → build-child process boundary: module *paths* and class *names*
 * only, never Effects or closures.
 */
export interface WakuEffectOptions {
  /**
   * Absolute filesystem path of the user's site module (the impl anchor,
   * `main: import.meta.url` converted from a `file://` URL). The generated
   * wrapper re-imports the Website class from here inside workerd.
   */
  readonly main: string;
  /** Durable Object class names registered by the program. */
  readonly durableObjects?: ReadonlyArray<string> | undefined;
  /** Workflow class names registered by the program. */
  readonly workflows?: ReadonlyArray<string> | undefined;
}

/**
 * Node-only packages reachable from alchemy's construct slice that crash at
 * module evaluation inside workerd. The production build tree-shakes them
 * away, but the dev module runner evaluates every module in the graph — so
 * they are aliased to inert stubs. Mirrors alchemy's own vite source.
 */
const NODE_STUBS: Record<string, string> = {
  workerd: [
    `export default "";`,
    `export const compatibilityDate = "";`,
    `export const version = "";`,
  ].join("\n"),
};
const STUB_PREFIX = "\0virtual:alchemy:node-stub:";

/** POSIX-normalize a path for use as a vite module specifier. */
const toSpecifier = (p: string) => p.replaceAll("\\", "/");

/**
 * Generate the wrapper module source (exported for unit tests). Import
 * order is load-bearing: `alchemy/Cloudflare/Serve` must evaluate before the
 * user's site module so `globalThis.__ALCHEMY_RUNTIME__` is stamped before
 * any user code can observe it.
 */
export const makeWakuEffectEntrySource = (
  options: WakuEffectOptions,
): string => {
  const doClasses = options.durableObjects ?? [];
  const wfClasses = options.workflows ?? [];
  const cfImports = [
    "WorkerEntrypoint",
    ...(doClasses.length > 0 ? ["DurableObject"] : []),
    ...(wfClasses.length > 0 ? ["WorkflowEntrypoint"] : []),
  ];
  const serveImports = [
    "makeWebsiteEntryExports",
    ...(doClasses.length > 0 ? ["DurableObjectBridge"] : []),
    ...(wfClasses.length > 0 ? ["WorkflowBridge"] : []),
  ];
  return [
    `// Generated by alchemy — waku effectful worker entry (Serve/DESIGN.md):`,
    `// fetch delegates verbatim to waku's handler (the user's mount middleware`,
    `// runs inside it); non-fetch dispatch + DO/Workflow classes come from the`,
    `// Worker bridge, printed from plan-time registration.`,
    `import { ${serveImports.join(", ")} } from "alchemy/Cloudflare/Serve";`,
    `import { ${cfImports.join(", ")} } from "cloudflare:workers";`,
    `import __wakuEntry from ${JSON.stringify(WAKU_SERVER_ENTRY_ID)};`,
    `import Site from ${JSON.stringify(toSpecifier(options.main))};`,
    `export default makeWebsiteEntryExports(WorkerEntrypoint, {`,
    `  site: Site,`,
    `  fetch: (request, env, ctx) => __wakuEntry.fetch(request, env, ctx),`,
    `});`,
    ...(doClasses.length > 0
      ? [
          `const __alchemyDurableObjectBridge = DurableObjectBridge(DurableObject, { site: Site });`,
          ...doClasses.map(
            (name) =>
              `export class ${name} extends __alchemyDurableObjectBridge(${JSON.stringify(name)}) {}`,
          ),
        ]
      : []),
    ...(wfClasses.length > 0
      ? [
          `const __alchemyWorkflowBridge = WorkflowBridge(WorkflowEntrypoint, { site: Site });`,
          ...wfClasses.map(
            (name) =>
              `export class ${name} extends __alchemyWorkflowBridge(${JSON.stringify(name)}) {}`,
          ),
        ]
      : []),
    "",
  ].join("\n");
};

export interface WakuEffectEntryPluginOptions {
  readonly effect: WakuEffectOptions;
  /**
   * Worker environment names, entry environment first (waku's topology:
   * `["rsc", "ssr"]`). These get the `__ALCHEMY_RUNTIME__` define and the
   * dev-time `optimizeDeps` exclusions.
   */
  readonly environments: readonly [string, ...string[]];
}

/**
 * The alchemy-injected vite plugin for effectful waku Websites:
 *
 * 1. resolves and loads {@link WEBSITE_ENTRY_ID} with the generated wrapper;
 * 2. defines `globalThis.__ALCHEMY_RUNTIME__` as `true` in every *worker*
 *    environment (never the client env) so plan-only `host.bind` branches
 *    fold at build time — the wrapper's `alchemy/Cloudflare/Serve` import also
 *    stamps the flag at module evaluation, so correctness holds even where
 *    the define can't reach;
 * 3. excludes the alchemy graph from dep optimization (the worker entry is
 *    virtual, so vite's scanner finds none of the wrapper graph up front —
 *    a lazy mid-request re-optimize breaks the workerd module runner) and
 *    aliases Node-only packages to inert stubs.
 */
export const wakuEffectEntryPlugin = (
  options: WakuEffectEntryPluginOptions,
): ViteModule.Plugin => ({
  name: "alchemy:waku-website-entry",
  config() {
    return {
      resolve: {
        // Top-level so every environment (and the dep optimizer) sees it;
        // no client module imports these packages, so the reach is safe.
        alias: Object.keys(NODE_STUBS).map((find) => ({
          find,
          replacement: `${STUB_PREFIX}${find}`,
        })),
      },
    };
  },
  configEnvironment(name) {
    if (options.environments.includes(name)) {
      return {
        define: { "globalThis.__ALCHEMY_RUNTIME__": "true" },
        optimizeDeps: {
          exclude: [
            "effect",
            "alchemy",
            "@effect/platform-node",
            "@effect/platform-bun",
            "@alchemy.run/cloudflare-runtime",
            "@distilled.cloud/cloudflare",
            "@distilled.cloud/core",
            ...Object.keys(NODE_STUBS),
          ],
        },
      };
    }
    return undefined;
  },
  resolveId(id) {
    if (id === WEBSITE_ENTRY_ID || id === RESOLVED_WEBSITE_ENTRY_ID) {
      return RESOLVED_WEBSITE_ENTRY_ID;
    }
    if (id.startsWith(STUB_PREFIX)) {
      return id;
    }
    return undefined;
  },
  load(id) {
    if (id === RESOLVED_WEBSITE_ENTRY_ID) {
      return makeWakuEffectEntrySource(options.effect);
    }
    if (id.startsWith(STUB_PREFIX)) {
      return NODE_STUBS[id.slice(STUB_PREFIX.length)];
    }
    return undefined;
  },
});
