// Generated by alchemy-prisma-effect. Do not edit.
//
// effect/Schema definitions for every Prisma model and enum — decode
// rows read outside the Prisma client (raw SQL, sync engines, queues)
// or reuse the shapes in RPC and HTTP contracts.
import * as Schema from "effect/Schema";

export const Widget = Schema.Struct({
  id: Schema.Int,
  name: Schema.String,
  createdAt: Schema.Date,
});
export type Widget = typeof Widget.Type;
