import * as Layer from "effect/Layer";
import * as ACMUI from "./ACM/ui.ts";
import * as ApiGatewayUI from "./ApiGateway/ui.ts";
import * as AutoScalingUI from "./AutoScaling/ui.ts";
import * as CloudFrontUI from "./CloudFront/ui.ts";
import * as CloudWatchUI from "./CloudWatch/ui.ts";
import * as DynamoDBUI from "./DynamoDB/ui.ts";
import * as EC2UI from "./EC2/ui.ts";
import * as ECRUI from "./ECR/ui.ts";
import * as ECSUI from "./ECS/ui.ts";
import * as EKSUI from "./EKS/ui.ts";
import * as ELBv2UI from "./ELBv2/ui.ts";
import * as EventBridgeUI from "./EventBridge/ui.ts";
import * as IAMUI from "./IAM/ui.ts";
import * as IdentityCenterUI from "./IdentityCenter/ui.ts";
import * as KMSUI from "./KMS/ui.ts";
import * as KinesisUI from "./Kinesis/ui.ts";
import * as LambdaUI from "./Lambda/ui.ts";
import * as LogsUI from "./Logs/ui.ts";
import * as OrganizationsUI from "./Organizations/ui.ts";
import * as RDSUI from "./RDS/ui.ts";
import * as Route53UI from "./Route53/ui.ts";
import * as S3UI from "./S3/ui.ts";
import * as SNSUI from "./SNS/ui.ts";
import * as SQSUI from "./SQS/ui.ts";
import * as SchedulerUI from "./Scheduler/ui.ts";
import * as SecretsManagerUI from "./SecretsManager/ui.ts";
import * as WebsiteUI from "./Website/ui.ts";

/**
 * Aggregated dashboard UI providers for every AWS service.
 *
 * Generated by scripts (see processes/Dashboard.md). Per-service providers
 * live in `AWS/{Service}/ui.ts`; keep merge groups nested (≤ 40
 * entries) to stay under tsc's variadic-inference ceiling.
 */
export const ui = () =>
  Layer.mergeAll(
    ACMUI.ui(),
    ApiGatewayUI.ui(),
    AutoScalingUI.ui(),
    CloudFrontUI.ui(),
    CloudWatchUI.ui(),
    DynamoDBUI.ui(),
    EC2UI.ui(),
    ECRUI.ui(),
    ECSUI.ui(),
    EKSUI.ui(),
    ELBv2UI.ui(),
    EventBridgeUI.ui(),
    IAMUI.ui(),
    IdentityCenterUI.ui(),
    KMSUI.ui(),
    KinesisUI.ui(),
    LambdaUI.ui(),
    LogsUI.ui(),
    OrganizationsUI.ui(),
    RDSUI.ui(),
    Route53UI.ui(),
    S3UI.ui(),
    SNSUI.ui(),
    SQSUI.ui(),
    SchedulerUI.ui(),
    SecretsManagerUI.ui(),
    WebsiteUI.ui(),
  );
