// Generated by @alchemy.run/frontend-frameworks/nextjs/aws.
// Synthesized from alchemy props (openNext) — do not edit, this file is
// regenerated on every build. Delete the marker line above (or replace the
// file) to take ownership; keep the streaming wrapper — the Function URL is
// created with invokeMode: RESPONSE_STREAM.
const config = {
  "default": {
    "override": {
      "wrapper": "aws-lambda-streaming"
    }
  }
};

export default config;
