import * as hybridnetwork from "@distilled.cloud/azure/hybridnetwork";
import * as Effect from "effect/Effect";
import { Unowned } from "../../AdoptPolicy.ts";
import { isResolved } from "../../Diff.ts";
import * as Provider from "../../Provider.ts";
import { Resource } from "../../Resource.ts";
import {
  desiredTags,
  ensureRegistered,
  hasAnyAlchemyTag,
  ignoreNotFound,
  isOwned,
  orUndefinedIfNotFound,
  requireSinglePage,
  resourceGroupOf,
  tagsDiffer,
  userTags,
  waitForProvisioned,
  waitUntilGone,
} from "../Arm.ts";
import { AzureEnvironment } from "../Environment.ts";
import type { Providers } from "../Providers.ts";
import {
  createHybridNetworkName,
  type HybridNetworkIdentity,
  identityDiffers,
  identityRequest,
  NAMESPACE,
  retryInProgress,
  sameArm,
  sameIdMap,
  STORE_BUDGET,
} from "./Common.ts";

export type SiteNetworkServiceSku = "Basic" | "Standard";

export interface SiteNetworkServiceProps {
  /** Resource group the service is created in. Changing it replaces the service. */
  resourceGroup: string;
  /**
   * Service name: 1-64 letters, digits, `_`, and `-`. If omitted, a unique
   * name is generated from the app, stage, and logical ID. Changing it
   * replaces the service.
   */
  name?: string;
  /**
   * Azure location; must be an Azure Operator Service Manager region.
   * Changing it replaces the service.
   * @default the `Azure.Location` layer, else the profile location, else `eastus`
   */
  location?: string;
  /**
   * SKU of the site network service. Changing it replaces the service.
   * @default "Standard"
   */
  sku?: SiteNetworkServiceSku;
  /** ARM ID of the `Site` to deploy onto. Changing it replaces the service. */
  siteId: string;
  /**
   * ARM ID of the `NetworkServiceDesignVersion` to deploy. Changing it
   * redeploys the service in place (upgrade/downgrade).
   */
  networkServiceDesignVersionId: string;
  /**
   * Desired configuration, as `{ referenceName: configurationGroupValueId }`
   * keyed by the design's configuration group schema reference names.
   * Changing it redeploys the service in place.
   */
  configurationGroupValues?: Record<string, string>;
  /**
   * Managed resource group AOSM deploys the service's resources into.
   * Changing it replaces the service.
   * @default generated by Azure
   */
  managedResourceGroupConfiguration?: {
    /** Managed resource group name. */
    name?: string;
    /** Managed resource group location. */
    location?: string;
  };
  /** Managed identity the service deploys with. */
  identity?: HybridNetworkIdentity;
  /**
   * User tags. Alchemy ownership tags (`alchemy::stack`, `alchemy::stage`,
   * `alchemy::id`) are merged in automatically.
   */
  tags?: Record<string, string>;
}

export interface SiteNetworkService extends Resource<
  "Azure.HybridNetwork.SiteNetworkService",
  SiteNetworkServiceProps,
  {
    /** Name of the site network service. */
    siteNetworkServiceName: string;
    /** ARM resource ID of the site network service. */
    siteNetworkServiceId: string;
    /** Resource group that holds the service. */
    resourceGroup: string;
    /** Location of the service. */
    location: string;
    /** SKU of the service. */
    sku: string | undefined;
    /** ARM ID of the site. */
    siteId: string;
    /** ARM ID of the deployed network service design version. */
    networkServiceDesignVersionId: string;
    /** Name of the managed resource group. */
    managedResourceGroupName: string | undefined;
    /** Last successfully deployed network service design version name. */
    lastStateNetworkServiceDesignVersionName: string | undefined;
    /** Principal ID of the system-assigned identity, if any. */
    principalId: string | undefined;
    /** User tags (Alchemy ownership tags stripped). */
    tags: Record<string, string>;
  },
  never,
  Providers
> {}

/**
 * An Azure Operator Service Manager site network service — the deployment
 * of a published `NetworkServiceDesignVersion` onto an operator `Site`,
 * configured by `ConfigurationGroupValue`s.
 *
 * Changing the design version or configuration values redeploys the
 * service in place; AOSM drives the underlying network functions and ARM
 * resources to the new desired state.
 *
 * @see https://learn.microsoft.com/azure/operator-service-manager/site-network-service-overview
 *
 * ### Deploying a Network Service
 * **Example:** Site network service
 * ```typescript
 * const sns = yield* Azure.HybridNetwork.SiteNetworkService("service", {
 *   resourceGroup: group.resourceGroupName,
 *   siteId: site.siteId,
 *   networkServiceDesignVersionId: nsdv.networkServiceDesignVersionId,
 *   configurationGroupValues: {
 *     config: values.configurationGroupValueId,
 *   },
 * });
 * ```
 *
 * ### Upgrading
 * **Example:** Roll out a new design version
 * ```typescript
 * const sns = yield* Azure.HybridNetwork.SiteNetworkService("service", {
 *   resourceGroup: group.resourceGroupName,
 *   siteId: site.siteId,
 *   networkServiceDesignVersionId: nsdv2.networkServiceDesignVersionId,
 *   configurationGroupValues: { config: values2.configurationGroupValueId },
 * });
 * ```
 *
 * @resource
 */
export const SiteNetworkService = Resource<SiteNetworkService>(
  "Azure.HybridNetwork.SiteNetworkService",
);

const getService = (
  subscriptionId: string,
  resourceGroupName: string,
  siteNetworkServiceName: string,
) =>
  orUndefinedIfNotFound(
    hybridnetwork.GetSiteNetworkService({
      subscriptionId,
      resourceGroupName,
      siteNetworkServiceName,
    }),
  );

const valueRefs = (
  refs:
    | Record<string, { readonly id?: string } | undefined>
    | null
    | undefined,
) =>
  Object.fromEntries(
    Object.entries(refs ?? {}).flatMap(([k, v]) =>
      v?.id === undefined ? [] : [[k, v.id] as const],
    ),
  );

const toAttrs = (
  resourceGroup: string,
  name: string,
  service:
    | hybridnetwork.GetSiteNetworkServiceResponse
    | hybridnetwork.SiteNetworkService,
): SiteNetworkService["Attributes"] => ({
  siteNetworkServiceName: name,
  siteNetworkServiceId: service.id ?? "",
  resourceGroup,
  location: service.location,
  sku: service.sku?.name,
  siteId: service.properties?.siteReference?.id ?? "",
  networkServiceDesignVersionId:
    service.properties?.networkServiceDesignVersionResourceReference?.id ?? "",
  managedResourceGroupName:
    service.properties?.managedResourceGroupConfiguration?.name,
  lastStateNetworkServiceDesignVersionName:
    service.properties?.lastStateNetworkServiceDesignVersionName,
  principalId: service.identity?.principalId,
  tags: userTags(service.tags),
});

export const SiteNetworkServiceProvider = () =>
  Provider.succeed(SiteNetworkService, {
    stables: [
      "siteNetworkServiceName",
      "siteNetworkServiceId",
      "resourceGroup",
      "location",
      "sku",
      "siteId",
      "managedResourceGroupName",
    ],

    list: Effect.fn(function* () {
      const { subscriptionId } = yield* AzureEnvironment.current;
      const page = yield* hybridnetwork
        .ListSiteNetworkServiceBySubscription({ subscriptionId })
        .pipe(
          Effect.flatMap((page) =>
            requireSinglePage("ListSiteNetworkServiceBySubscription", page),
          ),
        );
      return (page.value ?? []).flatMap((service) => {
        const group = resourceGroupOf(service.id);
        return hasAnyAlchemyTag(service.tags) &&
          group !== undefined &&
          service.name !== undefined
          ? [toAttrs(group, service.name, service)]
          : [];
      });
    }),

    diff: Effect.fn(function* ({ news, output }) {
      if (!isResolved(news) || output === undefined) return undefined;
      const sameName =
        news.name === undefined || news.name === output.siteNetworkServiceName;
      const mrg = news.managedResourceGroupConfiguration?.name;
      if (
        !sameArm(news.resourceGroup, output.resourceGroup) ||
        !sameName ||
        (news.location !== undefined &&
          !sameArm(news.location, output.location)) ||
        (news.sku ?? "Standard") !== (output.sku ?? "Standard") ||
        !sameArm(news.siteId, output.siteId) ||
        (mrg !== undefined && !sameArm(mrg, output.managedResourceGroupName))
      ) {
        return {
          action: "replace",
          deleteFirst: news.name !== undefined && sameName,
        } as const;
      }
      return undefined;
    }),

    read: Effect.fn(function* ({ id, olds, output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      const resourceGroup = output?.resourceGroup ?? olds?.resourceGroup;
      if (resourceGroup === undefined) return undefined;
      const name =
        output?.siteNetworkServiceName ??
        olds?.name ??
        (yield* createHybridNetworkName(id));
      const observed = yield* getService(subscriptionId, resourceGroup, name);
      if (observed === undefined) return undefined;
      const attrs = toAttrs(resourceGroup, name, observed);
      return (yield* isOwned(id, observed.tags)) ? attrs : Unowned(attrs);
    }),

    reconcile: Effect.fn(function* ({ id, news, output }) {
      const env = yield* AzureEnvironment.current;
      const { subscriptionId } = env;
      yield* ensureRegistered(subscriptionId, NAMESPACE);
      const resourceGroup = news.resourceGroup;
      const name =
        news.name ??
        output?.siteNetworkServiceName ??
        (yield* createHybridNetworkName(id));
      const location = news.location ?? output?.location ?? env.location;
      const tags = yield* desiredTags(id, news.tags);
      const desiredValues = news.configurationGroupValues ?? {};
      const where = {
        subscriptionId,
        resourceGroupName: resourceGroup,
        siteNetworkServiceName: name,
      };
      const get = getService(subscriptionId, resourceGroup, name);
      const label = `AOSM site network service ${name}`;
      // The design version and configuration values are only writable by
      // PUT; changing them redeploys the service.
      const deploymentDiffers = (
        observed: hybridnetwork.GetSiteNetworkServiceResponse,
      ) =>
        !sameArm(
          observed.properties?.networkServiceDesignVersionResourceReference
            ?.id,
          news.networkServiceDesignVersionId,
        ) ||
        !sameIdMap(
          valueRefs(
            observed.properties?.desiredStateConfigurationGroupValueReferences,
          ),
          desiredValues,
        ) ||
        identityDiffers(observed.identity, news.identity);

      // Observe.
      let observed = yield* get;

      // Ensure (and sync the deployment, which is only writable by PUT).
      if (observed === undefined || deploymentDiffers(observed)) {
        yield* retryInProgress(
          hybridnetwork.SiteNetworkServicesCreateOrUpdate({
            ...where,
            location: observed?.location ?? location,
            tags,
            sku: { name: observed?.sku?.name ?? news.sku ?? "Standard" },
            identity: identityRequest(news.identity),
            properties: {
              siteReference: { id: news.siteId },
              networkServiceDesignVersionResourceReference: {
                idType: "Open",
                id: news.networkServiceDesignVersionId,
              },
              desiredStateConfigurationGroupValueReferences: Object.fromEntries(
                Object.entries(desiredValues).map(([k, id]) => [k, { id }]),
              ),
              managedResourceGroupConfiguration:
                observed?.properties?.managedResourceGroupConfiguration ??
                news.managedResourceGroupConfiguration,
            },
          }),
        );
      }
      // Deploying the design runs its templates; allow several minutes.
      observed = yield* waitForProvisioned(
        label,
        get,
        (service) => service.properties?.provisioningState,
        STORE_BUDGET,
      );

      // Sync tags against observed state.
      if (tagsDiffer(observed.tags, tags)) {
        yield* retryInProgress(
          hybridnetwork.UpdateSiteNetworkServiceTags({ ...where, tags }),
        );
        observed = yield* waitForProvisioned(
          label,
          get,
          (service) =>
            tagsDiffer(service.tags, tags)
              ? "Updating"
              : service.properties?.provisioningState,
          STORE_BUDGET,
        );
      }

      return toAttrs(resourceGroup, name, observed);
    }),

    delete: Effect.fn(function* ({ output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      yield* ignoreNotFound(
        hybridnetwork
          .DeleteSiteNetworkService({
            subscriptionId,
            resourceGroupName: output.resourceGroup,
            siteNetworkServiceName: output.siteNetworkServiceName,
          })
          .pipe(retryInProgress),
      );
      yield* waitUntilGone(
        `AOSM site network service ${output.siteNetworkServiceName}`,
        getService(
          subscriptionId,
          output.resourceGroup,
          output.siteNetworkServiceName,
        ),
        STORE_BUDGET,
      );
    }),

    nuke: {
      dependsOn: [
        "Azure.HybridNetwork.ConfigurationGroupValue",
        "Azure.HybridNetwork.NetworkServiceDesignVersion",
        "Azure.HybridNetwork.Site",
        "Azure.Resources.ResourceGroup",
      ],
    },
  });
