name: 'Run Command with Alchemy Environment'
description: 'Runs a command with all standard Alchemy environment variables set'

inputs:
  command:
    description: 'Command to run'
    required: true
  working-directory:
    description: 'Working directory to run the command in'
    required: false
    default: '.'
  aws-region:
    description: 'AWS region to use'
    required: false
    default: 'us-west-2'
  branch-prefix:
    description: 'Branch prefix for resource naming'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Run command with Alchemy environment
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.command }}
      env:
        CI: true
        ALCHEMY_STATE_STORE: cloudflare
        AWS_REGION: ${{ inputs.aws-region }}
        BRANCH_PREFIX: ${{ inputs.branch-prefix }}
        # All secrets loaded from SSM parameter via setup-alchemy action
        # These environment variables are set by the setup-alchemy action
        ALCHEMY_PASSWORD: ${{ env.ALCHEMY_PASSWORD }}
        CLOUDFLARE_ACCOUNT_ID: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_KEY: ${{ env.CLOUDFLARE_API_KEY }}
        CLOUDFLARE_BUCKET_NAME: ${{ env.CLOUDFLARE_BUCKET_NAME }}
        CLOUDFLARE_EMAIL: ${{ env.CLOUDFLARE_EMAIL }}
        OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
        R2_ACCESS_KEY_ID: ${{ env.R2_ACCESS_KEY_ID }}
        R2_SECRET_ACCESS_KEY: ${{ env.R2_SECRET_ACCESS_KEY }}
        STRIPE_API_KEY: ${{ env.STRIPE_API_KEY }}
        NEON_API_KEY: ${{ env.NEON_API_KEY }}
        SECRET_PASSPHRASE: ${{ env.SECRET_PASSPHRASE }}
        UPSTASH_API_KEY: ${{ env.UPSTASH_API_KEY }}
        UPSTASH_EMAIL: sam@alchemy.run
        SENTRY_AUTH_TOKEN: ${{ env.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ env.SENTRY_ORG }}
        VERCEL_ACCESS_TOKEN: ${{ env.VERCEL_ACCESS_TOKEN }} 
        PLANETSCALE_ORG_ID: ${{ env.PLANETSCALE_ORG_ID }}
        PLANETSCALE_API_TOKEN: ${{ env.PLANETSCALE_API_TOKEN }}