/**
 * The AWS (Lambda / Node) recipe of the `alchemy/Serve` runtime bridge —
 * the cloud-specific half of `Serve/Bridge.ts`'s {@link makeBridgeCore},
 * and the helper the generated effectful-Website wrapper entries call
 * (DESIGN §6.2 AWS mechanics):
 *
 * ```js
 * // dist/server/index.mjs (generated by the framework target's finish pass)
 * globalThis.__ALCHEMY_RUNTIME__ = true;
 * import { handler as frameworkFetch } from "./entry.js";
 * import { toLambdaHandler } from "./aws-lambda.mjs";
 * import { lambdaServeBridge } from "./alchemy-effect.mjs"; // prebundle
 * import Site from "./site.mjs";
 * const site = lambdaServeBridge.handlers({ site: Site, routes: ["/api/*"] });
 * export const handler = toLambdaHandler(async (request) =>
 *   (await site.match(request)) ?? frameworkFetch(request));
 * ```
 *
 * Composition always happens **at the fetch layer, before the single
 * `awslambda.streamifyResponse` wrap** — streamed effect responses ride the
 * framework's `toLambdaHandler` pipe untouched
 * ({@link makeFunctionFetchHandler} preserves stream bodies).
 *
 * The recipe carries what is genuinely AWS: the credentials ladder
 * (`Credentials.fromChain()` resolves the Lambda execution-role env AND
 * the developer's ambient profile under `alchemy dev`, where the framework
 * dev server runs this bridge in a plain Node process — or the local floci
 * emulator identity when `ALCHEMY_AWS_ENDPOINT_URL` opts in), the Node
 * platform, the streamify-safe request pipeline, and the internal Lambda
 * extension that buys the SIGTERM Shutdown window. Everything delicate —
 * memoized builds, healing, request scopes, settle — lives once, in the
 * shared core. `waitUntil` never applies here: no mount forwards one, so
 * request scopes settle inline before the response (Lambda semantics).
 */

import { Endpoint } from "@distilled.cloud/aws";
import * as Credentials from "@distilled.cloud/aws/Credentials";
import * as Region from "@distilled.cloud/aws/Region";
import * as NodeServices from "@effect/platform-node/NodeServices";
import * as Effect from "effect/Effect";
import * as Layer from "effect/Layer";
import * as Logger from "effect/Logger";
import * as Redacted from "effect/Redacted";
import * as FetchHttpClient from "effect/unstable/http/FetchHttpClient";
import {
  makeBridgeCore,
  type BridgeRecipe,
  type SiteRuntime,
} from "../../Serve/Bridge.ts";
import { SERVE_BRIDGE_KEY } from "../../Serve/constants.ts";
import { envString, hasStackMarkers } from "../../Serve/Env.ts";
import { DEFAULT_SERVER_ROUTES, matchRoutes } from "../../Serve/Routes.ts";
import type { AnyWebsiteClass } from "../../Serve/Serve.ts";
import { makeFunctionFetchHandler } from "./HttpServer.ts";
import { registerLambdaExtension } from "./RuntimeExtension.ts";

/**
 * Register the internal Lambda extension once, buying the Shutdown phase
 * (SIGTERM + 500 ms) in which the instance scope's finalizers run. Errors
 * are swallowed inside; outside a Lambda sandbox
 * (`AWS_LAMBDA_RUNTIME_API` unset) it no-ops.
 */
let extension: Promise<unknown> | undefined;

const recipe: BridgeRecipe = {
  // Env: the explicit override from the mount, else `process.env` — the
  // Lambda sandbox env (packed markers via collect-only mode) or the
  // dev-server process env `alchemy dev` lowered the same values into.
  resolveEnv: (explicit) =>
    (explicit as Record<string, unknown> | undefined) ??
    (typeof process !== "undefined"
      ? (process.env as Record<string, unknown>)
      : undefined),

  layers: (env) =>
    // Cloud access ladder:
    //  - default: `fromChain()` resolves the Lambda execution-role env
    //    credentials in the sandbox AND the developer's ambient profile
    //    (SSO, ini) when the framework dev server runs this bridge in
    //    plain Node under `alchemy dev` — the AWS dev model: bindings hit
    //    real cloud (capability resources are typically `Alchemy.remote()`
    //    in dev).
    //  - `ALCHEMY_AWS_ENDPOINT_URL` set (opt-in, e.g. via
    //    `server.environment`): capability clients target that local
    //    emulator gateway with the emulator's fixed dummy identity —
    //    mirroring `makeFlociServices` — for sites whose resources live in
    //    the floci emulator. Scoped to this bridge only (a dedicated env
    //    name, never `AWS_*`) so the developer's ambient credentials stay
    //    untouched for their own code in the same dev-server process.
    ((): Layer.Layer<Credentials.Credentials | Region.Region> => {
      const localEndpoint = envString(env.ALCHEMY_AWS_ENDPOINT_URL);
      if (localEndpoint === undefined) {
        return Layer.mergeAll(Credentials.fromChain(), Region.fromEnv());
      }
      const region = "us-east-1" as Region.RegionName;
      return Layer.mergeAll(
        Layer.succeed(Endpoint.Endpoint, Effect.succeed(localEndpoint)),
        Layer.succeed(Region.Region, Effect.succeed(region)),
        Layer.succeed(
          Credentials.Credentials,
          Effect.succeed({
            accessKeyId: Redacted.make("test"),
            secretAccessKey: Redacted.make("test"),
            sessionToken: undefined,
            region,
          }),
        ),
      );
    })(),

  platform: () =>
    Layer.mergeAll(
      NodeServices.layer,
      FetchHttpClient.layer,
      Logger.layer([Logger.consolePretty()]),
    ),

  requestEffect: (request, handler) =>
    makeFunctionFetchHandler(handler)(request),

  // Register before the first layer build so the Shutdown window exists by
  // the time any init-level finalizer is registered.
  init: () => (extension ??= registerLambdaExtension()),
};

const core = makeBridgeCore(recipe);

export interface WebsiteHandlersOptions {
  /**
   * The effectful Website (or Lambda Function) class — the value
   * default-exported by the user's `src/backend.ts`.
   */
  site: AnyWebsiteClass;
  /**
   * Path globs the Effect fetch owns (`server.routes`, exclusion globs
   * supported). A request outside them resolves `undefined` immediately —
   * the framework serves it — without touching the layer build. Inside
   * them the effect fetch is authoritative: its responses (404s included)
   * are final.
   * @default DEFAULT_SERVER_ROUTES (["/api/*"])
   */
  routes?: readonly string[];
  /**
   * Explicit env override. Default: `process.env` (the Lambda sandbox env,
   * or the dev-server process env that `alchemy dev` lowered the packed
   * binding values into).
   */
  env?: Record<string, unknown>;
}

export interface WebsiteHandlers {
  /**
   * Run the effect fetch for this request. Resolves `undefined` ONLY on
   * decline — pathname outside `routes`, no alchemy stack markers in the
   * env (build-time prerender/SSG worlds), or no fetch handler on the
   * impl — so the caller falls through to the framework's fetch. Inside
   * the routes the effect fetch is authoritative: a `RouteNotFound`
   * failure (an `HttpRouter` miss) renders as the effect's own 404
   * response, never delegation.
   */
  match(request: Request): Promise<Response | undefined>;
  /**
   * `match` with a mandatory answer: declined requests are answered by
   * `fallback` when given, else a plain 404.
   */
  fetch(
    request: Request,
    options?: { fallback?: (request: Request) => Promise<Response> },
  ): Promise<Response>;
}

/**
 * The class-carried serve bridge for AWS-hosted Website classes (attached
 * under `SERVE_BRIDGE_KEY` by the effectful AWS Website constructs at
 * class construction). `Serve.make` — and therefore the framework mounts
 * `toRouteHandler` (Next.js) and `toEventHandler` (Nuxt/nitro) —
 * dispatches matched requests here, so the layer recipe carries
 * `Credentials.fromChain()` / `Region.fromEnv()` for SDK-backed capability
 * clients. Its `runtime` seam hands the value-form `createClient` the
 * Lambda/Node-flavored instance runtime (same per-class memo as the fetch
 * path).
 *
 * `Serve.make` owns the `server.routes` gate and only dispatches requests
 * inside the claim — no second gate here.
 */
export const lambdaServeBridge = {
  match: (
    site: object,
    request: Request,
    options?: { env?: unknown },
  ): Promise<Response | undefined> =>
    core.match(site, request, { env: options?.env }),
  dispose: (site: object): Promise<void> => core.dispose(site),
  runtime: (site: object, env: Record<string, unknown>): Promise<SiteRuntime> =>
    core.getRuntime(site, env),
  /** Stamp this bridge on a Website class (the AWS construct class arms). */
  attach: <T>(cls: T): T =>
    Object.assign(cls as object, {
      [SERVE_BRIDGE_KEY]: lambdaServeBridge,
    }) as T,
  /**
   * The generated AWS wrapper entry's site-match half: strict route
   * ownership — the effect fetch serves `routes` (answers final, 404s
   * included), the framework serves everything else.
   */
  handlers: (options: WebsiteHandlersOptions): WebsiteHandlers => {
    globalThis.__ALCHEMY_RUNTIME__ = true;
    void recipe.init!();

    const routes = options.routes ?? DEFAULT_SERVER_ROUTES;

    const match = async (request: Request): Promise<Response | undefined> => {
      const pathname = new URL(request.url).pathname;
      const env = await recipe.resolveEnv(options.env);
      // Cheap pre-gates BEFORE the core touches the layer build: the
      // four-worlds guard and strict route ownership.
      if (!hasStackMarkers(env)) {
        return undefined;
      }
      if (!matchRoutes(routes, pathname)) {
        return undefined;
      }
      return core.match(options.site as object, request, { env });
    };

    return {
      match,
      fetch: async (request, fetchOptions) =>
        (await match(request)) ??
        (fetchOptions?.fallback !== undefined
          ? fetchOptions.fallback(request)
          : new Response("Not Found", { status: 404 })),
    };
  },
};
