/**
 * The AWS (Lambda / Node) shell of the `alchemy/Serve` runtime bridge —
 * the helper the generated effectful-Website wrapper entries call
 * (DESIGN §6.2 AWS mechanics):
 *
 * ```js
 * // dist/server/index.mjs (generated by the framework target's finish pass)
 * globalThis.__ALCHEMY_RUNTIME__ = true;
 * import { handler as frameworkFetch } from "./entry.js";
 * import { toLambdaHandler } from "./aws-lambda.mjs";
 * import { makeWebsiteHandlers } from "./alchemy-effect.mjs"; // prebundle
 * import Site from "./site.mjs";
 * const site = makeWebsiteHandlers({ site: Site, routes: ["/api/*"] });
 * export const handler = toLambdaHandler(async (request) =>
 *   (await site.match(request)) ?? frameworkFetch(request));
 * ```
 *
 * Composition always happens **at the fetch layer, before the single
 * `awslambda.streamifyResponse` wrap** — streamed effect responses ride the
 * framework's `toLambdaHandler` pipe untouched
 * ({@link makeFunctionFetchHandler} preserves stream bodies).
 *
 * This module deliberately does NOT reuse `alchemy/Serve/Bridge.ts` (the
 * Cloudflare-flavored shell): the shared pieces it builds on are the pure
 * serve-core modules (`Serve/Routes.ts` route globs, `Serve/Env.ts`
 * stack-marker guard, `Serve/constants.ts` sentinel) plus the same layer
 * recipe the generated `FunctionBundle` entry uses — Stack identity from
 * the env markers, `Credentials.fromChain()` / `Region.fromEnv()` for
 * SDK-backed capability clients (the chain also resolves the developer's
 * ambient profile under `alchemy dev`, where the framework dev server runs
 * this bridge in a plain Node process), and the reified bound
 * `ConfigProvider`. Importing the Cloudflare shell here would drag the
 * whole `@distilled.cloud/cloudflare` graph into every AWS server bundle.
 */

import { Endpoint } from "@distilled.cloud/aws";
import * as Credentials from "@distilled.cloud/aws/Credentials";
import * as Region from "@distilled.cloud/aws/Region";
import * as NodeServices from "@effect/platform-node/NodeServices";
import * as Redacted from "effect/Redacted";
import * as Cause from "effect/Cause";
import * as ConfigProvider from "effect/ConfigProvider";
import * as Context from "effect/Context";
import * as Effect from "effect/Effect";
import * as Exit from "effect/Exit";
import * as Layer from "effect/Layer";
import * as Logger from "effect/Logger";
import { MinimumLogLevel } from "effect/References";
import * as Scope from "effect/Scope";
import * as FetchHttpClient from "effect/unstable/http/FetchHttpClient";
import { isScopeEjected } from "../../Http.ts";
import {
  makeEntrypointLayer,
  reifyBoundConfigProvider,
} from "../../Runtime.ts";
import type { BaseRuntimeContext } from "../../RuntimeContext.ts";
import { Self } from "../../Self.ts";
import type { SERVE_SENTINEL } from "../../Serve/constants.ts";
import { envString, hasStackMarkers } from "../../Serve/Env.ts";
import { DEFAULT_SERVER_ROUTES, matchRoutes } from "../../Serve/Routes.ts";
import type { AnyWebsiteClass } from "../../Serve/Serve.ts";
import { StackTag as Stack } from "../../StackTag.ts";
import { buildEventTelemetry } from "../../Telemetry.ts";
import { makeFunctionFetchHandler } from "./HttpServer.ts";
import { registerLambdaExtension } from "./RuntimeExtension.ts";

// The wiring-handshake sentinel, written as a literal (type-checked against
// `Serve/constants.ts`) so the exact byte sequence provably survives
// bundling and minification into any server bundle that imports this
// module — the deploy-time sentinel scan (`FunctionBundle.prebuiltCode`)
// greps the shipped directory for it.
const SENTINEL: typeof SERVE_SENTINEL = "__ALCHEMY_SERVE_v1__";
(globalThis as Record<string, any>)[SENTINEL] = true;

/** The instance-lifetime artifacts of one site build. */
interface LambdaSiteRuntime {
  readonly context: Context.Context<any>;
  readonly shape: () => Record<string, any> | undefined;
  readonly telemetry: () => Layer.Layer<never, any, any> | undefined;
}

/**
 * Every live instance-lifetime scope, drained by ONE process-level
 * SIGTERM listener (registered on the first build). One listener — not
 * one per build — so a dev server hot-swapping site classes (a fresh
 * class per edit, each with its own layer build) never accumulates
 * listeners toward `MaxListenersExceededWarning`.
 */
const instanceScopes = new Set<Scope.Closeable>();
let sigtermRegistered = false;

const registerInstanceScope = (scope: Scope.Closeable): void => {
  instanceScopes.add(scope);
  if (sigtermRegistered || typeof process?.on !== "function") {
    return;
  }
  sigtermRegistered = true;
  process.on("SIGTERM", () => {
    for (const live of instanceScopes) {
      void Effect.runPromise(Scope.close(live, Exit.void)).catch(() => {});
    }
    instanceScopes.clear();
  });
};

/**
 * The instance-lifetime scope of each site's build, for
 * {@link disposeWebsiteRuntime}. Keyed by the class (same key as
 * {@link siteBuilds}); registered as soon as the build starts so a
 * dispose during a failing build still closes the scope.
 */
const siteScopes = new WeakMap<object, Scope.Closeable>();

/**
 * Build the instance-lifetime layer stack for a Website/Function class
 * against a resolved env — the same recipe the generated `FunctionBundle`
 * entry uses, with the env injected explicitly (the bridge may be running
 * inside the framework's Lambda sandbox or a Node dev server).
 */
const buildLambdaSiteRuntime = (
  site: object,
  env: Record<string, unknown>,
): Promise<LambdaSiteRuntime> => {
  const tag = Self as any as Context.Service<
    never,
    { RuntimeContext: BaseRuntimeContext }
  >;

  const layer = makeEntrypointLayer(tag, site);

  const platform = Layer.mergeAll(
    NodeServices.layer,
    FetchHttpClient.layer,
    Logger.layer([Logger.consolePretty()]),
  );

  const entryLayer = layer.pipe(
    Layer.provideMerge(
      Layer.succeed(Stack, {
        name: envString(env.ALCHEMY_STACK_NAME) ?? "",
        stage: envString(env.ALCHEMY_STAGE) ?? "",
        bindings: {},
        resources: {},
        actions: {},
      }),
    ),
    // Cloud access ladder:
    //  - default: `fromChain()` resolves the Lambda execution-role env
    //    credentials in the sandbox AND the developer's ambient profile
    //    (SSO, ini) when the framework dev server runs this bridge in
    //    plain Node under `alchemy dev` — the AWS dev model: bindings hit
    //    real cloud (capability resources are typically `Alchemy.remote()`
    //    in dev).
    //  - `ALCHEMY_AWS_ENDPOINT_URL` set (opt-in, e.g. via
    //    `server.environment`): capability clients target that local
    //    emulator gateway with the emulator's fixed dummy identity —
    //    mirroring `makeFlociServices` — for sites whose resources live in
    //    the floci emulator. Scoped to this bridge only (a dedicated env
    //    name, never `AWS_*`) so the developer's ambient credentials stay
    //    untouched for their own code in the same dev-server process.
    Layer.provideMerge(
      ((): Layer.Layer<Credentials.Credentials | Region.Region> => {
        const localEndpoint = envString(env.ALCHEMY_AWS_ENDPOINT_URL);
        if (localEndpoint === undefined) {
          return Layer.mergeAll(Credentials.fromChain(), Region.fromEnv());
        }
        const region = "us-east-1" as Region.RegionName;
        return Layer.mergeAll(
          Layer.succeed(Endpoint.Endpoint, Effect.succeed(localEndpoint)),
          Layer.succeed(Region.Region, Effect.succeed(region)),
          Layer.succeed(
            Credentials.Credentials,
            Effect.succeed({
              accessKeyId: Redacted.make("test"),
              secretAccessKey: Redacted.make("test"),
              sessionToken: undefined,
              region,
            }),
          ),
        );
      })(),
    ),
    Layer.provideMerge(platform),
    Layer.provideMerge(
      Layer.succeed(
        ConfigProvider.ConfigProvider,
        ConfigProvider.orElse(
          ConfigProvider.fromUnknown({ ALCHEMY_PHASE: "runtime" }),
          // Auto-bound `Config` values arrive in `env` as
          // `{"_tag":"Redacted","value":...}` markers; reify them so a
          // `Config` re-read inside a request handler decodes the raw
          // source value instead of the marker JSON.
          reifyBoundConfigProvider(ConfigProvider.fromUnknown(env), env),
        ),
      ),
    ),
    Layer.provideMerge(
      Layer.succeed(MinimumLogLevel, env.DEBUG ? "Debug" : "Info"),
    ),
  );

  // Instance-lifetime scope for the layer build, closed in Lambda's
  // Shutdown window (SIGTERM + 500 ms — bought by the extension
  // registration below) so init-level finalizers run before the sandbox
  // dies. No `process.exit` here: the framework runtime owns the process.
  // The scope registers into the shared SIGTERM drain (one listener per
  // process) and the per-site map (so `disposeWebsiteRuntime` can close
  // it when a dev server retires this class generation).
  const instanceScope = Scope.makeUnsafe();
  registerInstanceScope(instanceScope);
  siteScopes.set(site, instanceScope);
  const memoMap = Layer.makeMemoMapUnsafe();

  return Effect.runPromise(
    Layer.buildWithMemoMap(entryLayer, memoMap, instanceScope).pipe(
      // Strip the build's memo map from the exposed context so a Layer the
      // user `Effect.provide`s inside a handler builds per event instead of
      // sharing one instance across concurrent events.
      Effect.map(Context.omit(Layer.CurrentMemoMap)),
      Effect.flatMap((context) =>
        tag.pipe(
          Effect.map((instance): LambdaSiteRuntime => {
            const runtimeContext = instance.RuntimeContext;
            return {
              context,
              shape: () =>
                runtimeContext.shape?.() as Record<string, any> | undefined,
              telemetry: () => runtimeContext.telemetry,
            };
          }),
          Effect.provideContext(context),
        ),
      ),
    ),
  );
};

/**
 * One instance-lifetime layer build per Website class, lazily created on
 * the first matched request and shared by every subsequent event. Only
 * success is memoized — a transient init failure resets the memo and heals
 * on the next event.
 */
const siteBuilds = new WeakMap<object, Promise<LambdaSiteRuntime>>();

const getLambdaSiteRuntime = (
  site: object,
  env: Record<string, unknown>,
): Promise<LambdaSiteRuntime> => {
  let build = siteBuilds.get(site);
  if (build === undefined) {
    build = buildLambdaSiteRuntime(site, env).catch((error) => {
      siteBuilds.delete(site);
      throw error;
    });
    siteBuilds.set(site, build);
  }
  return build;
};

export interface WebsiteHandlersOptions {
  /**
   * The effectful Website (or Lambda Function) class — the value
   * default-exported by the user's `src/backend.ts`.
   */
  site: AnyWebsiteClass;
  /**
   * Path globs the Effect fetch owns (`server.routes`, exclusion globs
   * supported). A request outside them resolves `undefined` immediately —
   * the framework serves it — without touching the layer build. Inside
   * them the effect fetch is authoritative: its responses (404s included)
   * are final.
   * @default DEFAULT_SERVER_ROUTES (["/api/*"])
   */
  routes?: readonly string[];
  /**
   * Explicit env override. Default: `process.env` (the Lambda sandbox env,
   * or the dev-server process env that `alchemy dev` lowered the packed
   * binding values into).
   */
  env?: Record<string, unknown>;
}

export interface WebsiteHandlers {
  /**
   * Run the effect fetch for this request. Resolves `undefined` ONLY on
   * decline — pathname outside `routes`, no alchemy stack markers in the
   * env (build-time prerender/SSG worlds), or no fetch handler on the
   * impl — so the caller falls through to the framework's fetch. Inside
   * the routes the effect fetch is authoritative: a `RouteNotFound`
   * failure (an `HttpRouter` miss) renders as the effect's own 404
   * response, never delegation.
   */
  match(request: Request): Promise<Response | undefined>;
  /**
   * `match` with a mandatory answer: declined requests are answered by
   * `fallback` when given, else a plain 404.
   */
  fetch(
    request: Request,
    options?: { fallback?: (request: Request) => Promise<Response> },
  ): Promise<Response>;
}

/**
 * Build the site-match half of a generated AWS wrapper entry: strict route
 * ownership — the effect fetch serves `routes` (its answers, 404s
 * included, are final), the framework serves everything else.
 *
 * Runtime-only — constructing the handlers stamps
 * `globalThis.__ALCHEMY_RUNTIME__` (so every `host.bind` guard in the
 * re-imported `src/backend.ts` is a no-op) and registers the internal Lambda
 * extension once, buying the Shutdown phase (SIGTERM + 500 ms) in which
 * the instance scope is closed. Outside a Lambda sandbox the registration
 * is a no-op.
 */
export const makeWebsiteHandlers = (
  options: WebsiteHandlersOptions,
): WebsiteHandlers => {
  globalThis.__ALCHEMY_RUNTIME__ = true;
  // Register before the first layer build so the Shutdown window exists by
  // the time any init-level finalizer is registered. Errors are swallowed
  // inside; outside Lambda (`AWS_LAMBDA_RUNTIME_API` unset) it no-ops.
  const extension = registerLambdaExtension();

  const routes = options.routes ?? DEFAULT_SERVER_ROUTES;

  const resolveEnv = (): Record<string, unknown> | undefined =>
    options.env ??
    (typeof process !== "undefined"
      ? (process.env as Record<string, unknown>)
      : undefined);

  /** One handler run through the shared per-event pipeline. */
  const runHandler = async (
    request: Request,
    handler: Effect.Effect<any, any, any>,
  ): Promise<Response> => {
    const env = resolveEnv();
    await extension;
    const runtime = await getLambdaSiteRuntime(options.site, env!);

    // Per-event outer scope carrying the telemetry exporters (handler
    // finalizers attach to `toHandled`'s internal request scope, which is
    // settled inline — or transferred to a streaming body — inside
    // `makeFunctionFetchHandler`).
    const scope = Scope.makeUnsafe();
    const exit = await makeFunctionFetchHandler(handler)(request).pipe(
      Effect.provide(
        Layer.mergeAll(
          Layer.succeed(Scope.Scope, scope),
          Layer.effectContext(
            buildEventTelemetry(runtime.context, scope, runtime.telemetry()),
          ),
        ).pipe(Layer.provideMerge(Layer.succeedContext(runtime.context))),
      ),
      Effect.runPromiseExit,
    );

    // Settle the request scope inline before returning (Lambda semantics —
    // there is no `waitUntil`; request finalizers block the response tail)
    // — unless a streaming response ejected it, in which case its new
    // owner closes it when the stream finishes.
    if (!isScopeEjected(scope)) {
      await new Promise((resolve) => setTimeout(resolve, 0));
      await Effect.runPromise(Scope.close(scope, Exit.void)).catch(() => {});
    }

    if (exit._tag !== "Success") {
      throw Cause.squash(exit.cause);
    }
    return exit.value as Response;
  };

  const match = async (request: Request): Promise<Response | undefined> => {
    const pathname = new URL(request.url).pathname;
    const env = resolveEnv();
    // The four-worlds guard (DESIGN §5.3): no stack markers means a
    // build-time prerender/SSG world — decline without building layers.
    if (!hasStackMarkers(env)) {
      return undefined;
    }
    // Strict route ownership: outside the claim the framework serves and
    // the effect fetch is never invoked.
    if (!matchRoutes(routes, pathname)) {
      return undefined;
    }
    await extension;
    const runtime = await getLambdaSiteRuntime(options.site, env!);
    const fetchHandler = runtime.shape()?.fetch;
    if (fetchHandler === undefined) {
      return undefined;
    }
    // The effect fetch is authoritative inside the routes: every response
    // — including the 404 `safeHttpEffect` renders for a `RouteNotFound`
    // failure — is the final answer.
    return runHandler(request, fetchHandler);
  };

  return {
    match,
    fetch: async (request, fetchOptions) =>
      (await match(request)) ??
      (fetchOptions?.fallback !== undefined
        ? fetchOptions.fallback(request)
        : new Response("Not Found", { status: 404 })),
  };
};

/**
 * One shell-owned {@link WebsiteHandlers} per Website class — the same
 * per-class memo the layer build underneath uses, so repeated
 * `Serve.make(Site)` mounts share one instance-lifetime runtime.
 */
const shellHandlers = new WeakMap<object, WebsiteHandlers>();

/**
 * The `alchemy/Serve` shell for AWS-hosted Website classes (attached under
 * `SERVE_SHELL_KEY` by the effectful AWS Website constructs at class
 * construction). `Serve.make` — and therefore the framework mounts
 * `toRouteHandler` (Next.js) and `toEventHandler` (Nuxt/nitro) — dispatches
 * matched requests here instead of the Cloudflare-flavored bridge, so the
 * layer recipe carries `Credentials.fromChain()` / `Region.fromEnv()` for
 * SDK-backed capability clients. Env resolves from the explicit override
 * when the mount passes one, else `process.env` — the Lambda sandbox env
 * (packed markers via collect-only mode) or the dev-server process env
 * `alchemy dev` lowered the same values into. `waitUntil` is deliberately
 * ignored: request scopes settle inline before the response (Lambda
 * semantics).
 *
 * `Serve.make` owns the `server.routes` gate and only dispatches requests
 * inside the claim, so the shell's handlers claim everything they receive
 * (`routes: ["/*"]`) — a second gate here would re-apply a default claim
 * over the handle's possibly-broader one.
 */
export const lambdaServeShell = {
  match: (
    site: object,
    request: Request,
    options?: { env?: unknown },
  ): Promise<Response | undefined> => {
    let handlers = shellHandlers.get(site);
    if (handlers === undefined) {
      handlers = makeWebsiteHandlers({
        site: site as AnyWebsiteClass,
        routes: ["/*"],
        ...(options?.env !== undefined && options.env !== null
          ? { env: options.env as Record<string, unknown> }
          : {}),
      });
      shellHandlers.set(site, handlers);
    }
    return handlers.match(request);
  },
  dispose: (site: object): Promise<void> => disposeWebsiteRuntime(site),
  /**
   * The value-form `createClient(Backend)` seam: hand `alchemy/Client`'s
   * in-process dispatch the Lambda/Node-flavored isolate runtime (same
   * per-class memo as the fetch path) so backend methods resolve AWS
   * services (credentials chain, Node platform) instead of dying on the
   * Cloudflare-flavored default bridge.
   */
  runtime: (
    site: object,
    env: Record<string, unknown>,
  ): Promise<LambdaSiteRuntime> => getLambdaSiteRuntime(site, env),
};

/**
 * Tear down the per-class runtime built for `site`: evict the shell and
 * layer-build memos and close the instance-lifetime scope (init-level
 * finalizers run). Idempotent; a never-dispatched class resolves
 * immediately.
 *
 * This is the invalidation half of effect-handler hot reload in dev
 * servers (`Serve.dispose`): a cache-busted re-import produces a fresh
 * class identity whose first matched request lazily builds a fresh layer
 * stack — but the OLD generation's build, scope, and SIGTERM registration
 * would otherwise be retained for the process lifetime (node's module
 * registry pins every re-imported namespace, so `WeakMap` entries keyed
 * by old classes are never reclaimed).
 */
export const disposeWebsiteRuntime = async (site: object): Promise<void> => {
  shellHandlers.delete(site);
  const build = siteBuilds.get(site);
  siteBuilds.delete(site);
  if (build !== undefined) {
    // Settle the in-flight build first so the scope close below observes
    // every registered finalizer (a failed build already cleared itself).
    await build.catch(() => undefined);
  }
  const scope = siteScopes.get(site);
  if (scope !== undefined) {
    siteScopes.delete(site);
    instanceScopes.delete(scope);
    await Effect.runPromise(Scope.close(scope, Exit.void)).catch(() => {});
  }
};
