import * as hsm from "@distilled.cloud/azure/hardwaresecuritymodules";
import * as Effect from "effect/Effect";
import { Unowned } from "../../AdoptPolicy.ts";
import { isResolved } from "../../Diff.ts";
import { createPhysicalName } from "../../PhysicalName.ts";
import * as Provider from "../../Provider.ts";
import { Resource } from "../../Resource.ts";
import {
  desiredTags,
  ensureRegistered,
  hasAnyAlchemyTag,
  ignoreNotFound,
  isOwned,
  orUndefinedIfNotFound,
  requireSinglePage,
  resourceGroupOf,
  tagsDiffer,
  userTags,
  waitForProvisioned,
  waitUntilGone,
} from "../Arm.ts";
import { AzureEnvironment } from "../Environment.ts";
import type { Providers } from "../Providers.ts";

export type CloudHsmClusterSkuName = hsm.CloudHsmClusterSkuName;
export type CloudHsmDomainNameLabelScope =
  hsm.AutoGeneratedDomainNameLabelScope;
export type CloudHsmIdentityType = hsm.ManagedServiceIdentityType;

export interface CloudHsmClusterIdentity {
  /** Managed identity type. */
  type: CloudHsmIdentityType;
  /**
   * ARM resource IDs of user-assigned identities to attach. A user-assigned
   * identity is required for backup and restore.
   */
  userAssignedIdentityIds?: string[];
}

export interface CloudHsmClusterProps {
  /**
   * Resource group the cluster is created in. Changing it replaces the
   * cluster.
   */
  resourceGroup: string;
  /**
   * Cluster name: 3-23 characters. If omitted, a unique name is generated
   * from the app, stage, and logical ID. Changing it replaces the cluster.
   */
  name?: string;
  /**
   * Azure location of the cluster. Changing it replaces the cluster.
   * @default the `Azure.Location` layer, else the profile location, else `eastus`
   */
  location?: string;
  /**
   * SKU of the cluster (family `B`). Changing it replaces the cluster.
   * @default "Standard_B1"
   */
  sku?: CloudHsmClusterSkuName;
  /**
   * Reuse scope of the auto-generated domain name label of the HSM FQDNs.
   * Changing it replaces the cluster.
   * @default Azure's default
   */
  autoGeneratedDomainNameLabelScope?: CloudHsmDomainNameLabelScope;
  /**
   * Public network access. Cloud HSM only supports `Disabled`; reach the
   * cluster through a private endpoint.
   * @default Azure's default
   */
  publicNetworkAccess?: hsm.PublicNetworkAccess;
  /** Managed identity of the cluster (user-assigned for backup/restore). */
  identity?: CloudHsmClusterIdentity;
  /**
   * User tags. Alchemy ownership tags (`alchemy::stack`, `alchemy::stage`,
   * `alchemy::id`) are merged in automatically.
   */
  tags?: Record<string, string>;
}

export interface CloudHsm {
  /** FQDN of the HSM. */
  fqdn: string | undefined;
  /** HSM state, e.g. `Deploying`, `Starting`, `Failed`. */
  state: string | undefined;
  /** HSM state message. */
  stateMessage: string | undefined;
}

export interface CloudHsmCluster extends Resource<
  "Azure.HardwareSecurityModules.CloudHsmCluster",
  CloudHsmClusterProps,
  {
    /** Name of the cluster. */
    cloudHsmClusterName: string;
    /** ARM resource ID of the cluster. */
    cloudHsmClusterId: string;
    /** Resource group that holds the cluster. */
    resourceGroup: string;
    /** Location of the cluster. */
    location: string;
    /** SKU name. */
    sku: string;
    /** Reuse scope of the auto-generated domain name label. */
    autoGeneratedDomainNameLabelScope: string | undefined;
    /** Public network access setting. */
    publicNetworkAccess: string | undefined;
    /**
     * Security domain activation state (`NotDefined`, `NotActivated`,
     * `Activated`). Activation happens customer-side with Azure Cloud HSM
     * tooling.
     */
    activationState: string | undefined;
    /** Cluster status message. */
    statusMessage: string | undefined;
    /** The HSMs of the cluster. */
    hsms: CloudHsm[];
    /** Principal ID of the system-assigned identity, if any. */
    principalId: string | undefined;
    /** Tenant ID of the system-assigned identity, if any. */
    tenantId: string | undefined;
    /** User tags (Alchemy ownership tags stripped). */
    tags: Record<string, string>;
  },
  never,
  Providers
> {}

/**
 * An Azure Cloud HSM cluster — a single-tenant, FIPS 140-3 Level 3
 * validated HSM cluster (three HSM partitions) for PKCS#11, JCE, and
 * OpenSSL workloads. Provisioning takes about 20-30 minutes and is billed
 * per HSM while the cluster exists. After creation the cluster must be
 * activated with the Azure Cloud HSM client tooling over a private
 * endpoint.
 *
 * @see https://learn.microsoft.com/azure/cloud-hsm/overview
 *
 * ### Creating a Cloud HSM Cluster
 * **Example:** Basic cluster
 * ```typescript
 * const group = yield* Azure.Resources.ResourceGroup("hsm");
 * const cluster = yield* Azure.HardwareSecurityModules.CloudHsmCluster("hsm", {
 *   resourceGroup: group.resourceGroupName,
 *   publicNetworkAccess: "Disabled",
 * });
 * ```
 *
 * ### Backup and Restore
 * **Example:** Cluster with a user-assigned identity for backups
 * ```typescript
 * const identity = yield* Azure.ManagedIdentity.UserAssignedIdentity("hsm-backup", {
 *   resourceGroup: group.resourceGroupName,
 * });
 * const cluster = yield* Azure.HardwareSecurityModules.CloudHsmCluster("hsm", {
 *   resourceGroup: group.resourceGroupName,
 *   identity: {
 *     type: "UserAssigned",
 *     userAssignedIdentityIds: [identity.identityId],
 *   },
 * });
 * ```
 *
 * @resource
 */
export const CloudHsmCluster = Resource<CloudHsmCluster>(
  "Azure.HardwareSecurityModules.CloudHsmCluster",
);

type ObservedCluster = hsm.GetCloudHsmClusterResponse;
type ListedCluster = hsm.CloudHsmCluster;

const createClusterName = (id: string) =>
  createPhysicalName({ id, maxLength: 23, lowercase: true, delimiter: "-" });

const getCluster = (
  subscriptionId: string,
  resourceGroupName: string,
  cloudHsmClusterName: string,
) =>
  orUndefinedIfNotFound(
    hsm.GetCloudHsmCluster({
      subscriptionId,
      resourceGroupName,
      cloudHsmClusterName,
    }),
  );

const toAttrs = (
  resourceGroup: string,
  name: string,
  cluster: ObservedCluster | ListedCluster,
): CloudHsmCluster["Attributes"] => {
  const props = cluster.properties;
  return {
    cloudHsmClusterName: name,
    cloudHsmClusterId: cluster.id ?? "",
    resourceGroup,
    location: cluster.location,
    sku: cluster.sku?.name ?? "",
    autoGeneratedDomainNameLabelScope: props?.autoGeneratedDomainNameLabelScope,
    publicNetworkAccess: props?.publicNetworkAccess,
    activationState: props?.activationState,
    statusMessage: props?.statusMessage,
    hsms: (props?.hsms ?? []).map((h) => ({
      fqdn: h.fqdn,
      state: h.state,
      stateMessage: h.stateMessage,
    })),
    principalId: cluster.identity?.principalId,
    tenantId: cluster.identity?.tenantId,
    tags: userTags(cluster.tags),
  };
};

const lower = (value: string | undefined) => value?.toLowerCase();
const normLocation = (value: string | undefined) =>
  lower(value)?.replace(/\s/g, "");

const identityDiffers = (
  observed: ObservedCluster["identity"],
  desired: CloudHsmClusterIdentity | undefined,
) => {
  if (desired === undefined) return false;
  const observedType = (observed?.type ?? "None").replace(/\s/g, "");
  if (
    observedType.toLowerCase() !== desired.type.replace(/\s/g, "").toLowerCase()
  ) {
    return true;
  }
  const have = Object.keys(observed?.userAssignedIdentities ?? {})
    .map((key) => key.toLowerCase())
    .sort()
    .join(",");
  const want = (desired.userAssignedIdentityIds ?? [])
    .map((key) => key.toLowerCase())
    .sort()
    .join(",");
  return have !== want;
};

const toIdentityInput = (identity: CloudHsmClusterIdentity | undefined) =>
  identity === undefined
    ? undefined
    : {
        type: identity.type,
        userAssignedIdentities: identity.userAssignedIdentityIds?.length
          ? Object.fromEntries(
              identity.userAssignedIdentityIds.map((armId) => [armId, {}]),
            )
          : undefined,
      };

/** Provisioning and deletion take ~20-30 minutes. */
const SLOW = { interval: "30 seconds", times: 60 } as const;

export const CloudHsmClusterProvider = () =>
  Provider.succeed(CloudHsmCluster, {
    stables: [
      "cloudHsmClusterName",
      "cloudHsmClusterId",
      "resourceGroup",
      "location",
      "sku",
      "autoGeneratedDomainNameLabelScope",
    ],

    list: Effect.fn(function* () {
      const { subscriptionId } = yield* AzureEnvironment.current;
      const page = yield* hsm
        .ListCloudHsmClusterBySubscription({ subscriptionId })
        .pipe(
          Effect.flatMap((page) =>
            requireSinglePage("ListCloudHsmClusterBySubscription", page),
          ),
        );
      return (page.value ?? []).flatMap((cluster) => {
        const group = resourceGroupOf(cluster.id);
        return hasAnyAlchemyTag(cluster.tags) &&
          group !== undefined &&
          cluster.name !== undefined
          ? [toAttrs(group, cluster.name, cluster)]
          : [];
      });
    }),

    diff: Effect.fn(function* ({ news, output }) {
      if (!isResolved(news) || output === undefined) return undefined;
      if (
        lower(news.resourceGroup) !== lower(output.resourceGroup) ||
        (news.name !== undefined &&
          lower(news.name) !== lower(output.cloudHsmClusterName)) ||
        (news.location !== undefined &&
          normLocation(news.location) !== normLocation(output.location)) ||
        lower(news.sku ?? "Standard_B1") !== lower(output.sku) ||
        (news.autoGeneratedDomainNameLabelScope !== undefined &&
          lower(news.autoGeneratedDomainNameLabelScope) !==
            lower(output.autoGeneratedDomainNameLabelScope))
      ) {
        return { action: "replace" } as const;
      }
      return undefined;
    }),

    read: Effect.fn(function* ({ id, olds, output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      const resourceGroup = output?.resourceGroup ?? olds?.resourceGroup;
      if (resourceGroup === undefined) return undefined;
      const name =
        output?.cloudHsmClusterName ??
        olds?.name ??
        (yield* createClusterName(id));
      const observed = yield* getCluster(subscriptionId, resourceGroup, name);
      if (observed === undefined) return undefined;
      const attrs = toAttrs(resourceGroup, name, observed);
      return (yield* isOwned(id, observed.tags)) ? attrs : Unowned(attrs);
    }),

    reconcile: Effect.fn(function* ({ id, news, output }) {
      const env = yield* AzureEnvironment.current;
      const { subscriptionId } = env;
      yield* ensureRegistered(
        subscriptionId,
        "Microsoft.HardwareSecurityModules",
      );
      const resourceGroup = news.resourceGroup;
      const name =
        news.name ??
        output?.cloudHsmClusterName ??
        (yield* createClusterName(id));
      const location = news.location ?? output?.location ?? env.location;
      const tags = yield* desiredTags(id, news.tags);
      const where = {
        subscriptionId,
        resourceGroupName: resourceGroup,
        cloudHsmClusterName: name,
      };
      const label = `cloud hsm cluster ${name}`;
      const get = getCluster(subscriptionId, resourceGroup, name);
      const waitReady = waitForProvisioned(
        label,
        get,
        (cluster) => cluster.properties?.provisioningState,
        SLOW,
      );

      // Full PUT body: desired values where set, observed values otherwise,
      // so a re-PUT never resets settings the user did not declare.
      const body = (observed: ObservedCluster | undefined) =>
        ({
          ...where,
          location,
          tags,
          sku: { family: "B", name: news.sku ?? "Standard_B1" },
          identity:
            toIdentityInput(news.identity) ??
            (observed?.identity?.type
              ? toIdentityInput({
                  type: observed.identity.type,
                  userAssignedIdentityIds: Object.keys(
                    observed.identity.userAssignedIdentities ?? {},
                  ),
                })
              : undefined),
          properties: {
            autoGeneratedDomainNameLabelScope:
              news.autoGeneratedDomainNameLabelScope ??
              observed?.properties?.autoGeneratedDomainNameLabelScope,
            publicNetworkAccess:
              news.publicNetworkAccess ??
              observed?.properties?.publicNetworkAccess,
          },
        }) satisfies hsm.CloudHsmClustersCreateOrUpdateRequest;

      // Observe.
      let observed = yield* get;

      // Ensure. Creation is a long-running operation (~20-30 minutes).
      if (observed === undefined) {
        yield* hsm.CloudHsmClustersCreateOrUpdate(body(undefined));
      }
      observed = yield* waitReady;

      // Sync: publicNetworkAccess is only settable via PUT; tags and
      // identity go through PATCH.
      if (
        news.publicNetworkAccess !== undefined &&
        lower(observed.properties?.publicNetworkAccess) !==
          lower(news.publicNetworkAccess)
      ) {
        yield* hsm.CloudHsmClustersCreateOrUpdate(body(observed));
        observed = yield* waitReady;
      }
      const tagsChanged = tagsDiffer(observed.tags, tags);
      const identityChanged = identityDiffers(observed.identity, news.identity);
      if (tagsChanged || identityChanged) {
        yield* hsm.UpdateCloudHsmCluster({
          ...where,
          tags: tagsChanged ? tags : undefined,
          identity: identityChanged
            ? toIdentityInput(news.identity)
            : undefined,
        });
        observed = yield* waitReady;
      }

      return toAttrs(resourceGroup, name, observed);
    }),

    delete: Effect.fn(function* ({ output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      yield* ignoreNotFound(
        hsm.DeleteCloudHsmCluster({
          subscriptionId,
          resourceGroupName: output.resourceGroup,
          cloudHsmClusterName: output.cloudHsmClusterName,
        }),
      );
      yield* waitUntilGone(
        `cloud hsm cluster ${output.cloudHsmClusterName}`,
        getCluster(
          subscriptionId,
          output.resourceGroup,
          output.cloudHsmClusterName,
        ),
        SLOW,
      );
    }),

    nuke: { dependsOn: ["Azure.Resources.ResourceGroup"] },
  });
