import * as iothub from "@distilled.cloud/azure/iothub";
import * as Effect from "effect/Effect";
import * as Redacted from "effect/Redacted";
import { Unowned } from "../../AdoptPolicy.ts";
import { isResolved } from "../../Diff.ts";
import * as Provider from "../../Provider.ts";
import { Resource } from "../../Resource.ts";
import {
  desiredTags,
  ensureRegistered,
  hasAnyAlchemyTag,
  ignoreNotFound,
  isOwned,
  requireSinglePage,
  resourceGroupOf,
  tagsDiffer,
  userTags,
  waitForProvisioned,
  waitUntilGone,
} from "../Arm.ts";
import { AzureEnvironment } from "../Environment.ts";
import type { Providers } from "../Providers.ts";
import { createIotHubName, getIotHub, matchesObserved } from "./Common.ts";

export type IotHubSkuName = "F1" | "B1" | "B2" | "B3" | "S1" | "S2" | "S3";

export interface IotHubProps {
  /** Resource group the hub is created in. Changing it replaces the hub. */
  resourceGroup: string;
  /**
   * Globally unique hub name (`{name}.azure-devices.net`): 3-50 letters,
   * digits, and hyphens, not ending with a hyphen. If omitted, a unique name
   * is generated from the app, stage, and logical ID. Changing it replaces
   * the hub.
   */
  name?: string;
  /**
   * Azure location of the hub. Changing it replaces the hub.
   * @default the `Azure.Location` layer, else the profile location, else `eastus`
   */
  location?: string;
  /**
   * Pricing tier. `F1` (free, one per subscription, 8,000 messages/day),
   * `B1`-`B3` (Basic: device-to-cloud only), `S1`-`S3` (Standard: adds
   * cloud-to-device, device twins, and message enrichments). Sizes within a
   * tier and `Basic` → `Standard` upgrades happen in place; moving to or from
   * `F1`, or from `Standard` down to `Basic`, replaces the hub.
   * @default "S1"
   */
  sku?: IotHubSkuName;
  /**
   * Number of IoT Hub units (`F1` allows exactly 1).
   * @default 1
   */
  capacity?: number;
  /**
   * Partitions of the built-in Event Hub-compatible `events` endpoint
   * (`F1`: 2; paid tiers: 2-32). Set only at creation; changing it replaces
   * the hub.
   * @default Azure's default (4, or 2 on `F1`)
   */
  partitionCount?: number;
  /**
   * Days device-to-cloud messages are retained on the built-in `events`
   * endpoint (1-7; `F1` and `Basic` allow 1).
   * @default 1
   */
  retentionTimeInDays?: number;
  /** Cloud-to-device messaging settings (Standard tiers). */
  cloudToDevice?: iothub.CloudToDeviceProperties;
  /**
   * Message routing: custom endpoints (Event Hubs, Service Bus, Storage,
   * Cosmos DB), routes, fallback route, and enrichments. Endpoints that use
   * key-based connection strings are re-sent on every deploy because Azure
   * masks their keys when read back.
   */
  routing?: iothub.RoutingPropertiesInput;
  /**
   * File-upload storage endpoint, keyed by `$default` (the only allowed
   * key).
   */
  storageEndpoints?: Record<string, iothub.StorageEndpointProperties>;
  /**
   * File-upload notification queue settings, keyed by `fileNotifications`.
   */
  messagingEndpoints?: Record<string, iothub.MessagingEndpointProperties>;
  /** Send file-upload notifications to the `fileNotifications` queue. */
  enableFileUploadNotifications?: boolean;
  /**
   * Hub-level shared access policies. When omitted the hub keeps its current
   * policies (the five defaults: `iothubowner`, `service`, `device`,
   * `registryRead`, `registryReadWrite`). Existing keys are preserved for
   * policies whose keys are not given.
   */
  authorizationPolicies?: {
    /** Policy name. */
    keyName: string;
    /** Permissions, e.g. `"RegistryRead, ServiceConnect"`. */
    rights: iothub.SharedAccessSignatureAuthorizationRuleRights;
    /** Primary key. Generated by Azure when omitted. */
    primaryKey?: string;
    /** Secondary key. Generated by Azure when omitted. */
    secondaryKey?: string;
  }[];
  /** Reject hub-scoped SAS tokens (Entra ID only). */
  disableLocalAuth?: boolean;
  /** Reject device-scoped SAS keys. */
  disableDeviceSAS?: boolean;
  /** Reject module-scoped SAS keys. */
  disableModuleSAS?: boolean;
  /** Whether the public endpoint accepts traffic. */
  publicNetworkAccess?: "Enabled" | "Disabled";
  /** Legacy IP filter rules. */
  ipFilterRules?: iothub.IpFilterRule[];
  /** IP network rule set. */
  networkRuleSets?: iothub.NetworkRuleSetProperties;
  /** Restrict egress to `allowedFqdnList`. */
  restrictOutboundNetworkAccess?: boolean;
  /** FQDNs the hub may reach when outbound access is restricted. */
  allowedFqdnList?: string[];
  /**
   * Minimum TLS version (`"1.2"`), supported in selected regions. Set only
   * at creation; changing it replaces the hub.
   */
  minTlsVersion?: string;
  /**
   * Keep data in the hub's region (disables disaster-recovery failover).
   * Set only at creation; changing it replaces the hub.
   */
  enableDataResidency?: boolean;
  /** Optional features, e.g. `"DeviceManagement"`. */
  features?: "None" | "DeviceManagement";
  /** Free-form comments. */
  comments?: string;
  /** Managed identities of the hub (for identity-based routing endpoints). */
  identity?: {
    /** Identity type. */
    type:
      | "None"
      | "SystemAssigned"
      | "UserAssigned"
      | "SystemAssigned, UserAssigned";
    /** ARM IDs of user-assigned identities. */
    userAssignedIdentities?: string[];
  };
  /**
   * User tags. Alchemy ownership tags (`alchemy::stack`, `alchemy::stage`,
   * `alchemy::id`) are merged in automatically.
   */
  tags?: Record<string, string>;
}

export interface IotHub extends Resource<
  "Azure.IoTHub.IotHub",
  IotHubProps,
  {
    /** Name of the hub. */
    iotHubName: string;
    /** ARM resource ID of the hub; use it as a role-assignment scope. */
    iotHubId: string;
    /** Resource group that holds the hub. */
    resourceGroup: string;
    /** Location of the hub. */
    location: string;
    /** Pricing tier, e.g. `S1`. */
    sku: string;
    /** Number of IoT Hub units. */
    capacity: number | undefined;
    /** Device and service endpoint host name, e.g. `{name}.azure-devices.net`. */
    hostName: string | undefined;
    /** Hub state, e.g. `Active`. */
    state: string | undefined;
    /** Event Hub-compatible endpoint of the built-in `events` endpoint (`sb://…`). */
    eventHubEndpoint: string | undefined;
    /** Event Hub-compatible name (entity path) of the built-in `events` endpoint. */
    eventHubPath: string | undefined;
    /** Partition IDs of the built-in `events` endpoint. */
    partitionIds: string[];
    /** Partition count of the built-in `events` endpoint. */
    partitionCount: number | undefined;
    /** Retention of the built-in `events` endpoint in days. */
    retentionTimeInDays: number | undefined;
    /** Principal ID of the system-assigned identity, if enabled. */
    principalId: string | undefined;
    /** Primary key of the `iothubowner` policy. */
    primaryKey: Redacted.Redacted<string> | undefined;
    /**
     * Service connection string of the `iothubowner` policy
     * (`HostName=…;SharedAccessKeyName=iothubowner;SharedAccessKey=…`).
     */
    primaryConnectionString: Redacted.Redacted<string> | undefined;
    /**
     * Event Hub-compatible connection string of the built-in `events`
     * endpoint using the `iothubowner` policy, for Event Hubs consumers.
     */
    eventHubConnectionString: Redacted.Redacted<string> | undefined;
    /** User tags (Alchemy ownership tags stripped). */
    tags: Record<string, string>;
  },
  never,
  Providers
> {}

/**
 * An Azure IoT Hub — the cloud gateway devices connect to for telemetry,
 * cloud-to-device messages, device twins, and file upload. Device-to-cloud
 * messages land on a built-in Event Hub-compatible endpoint (`events`)
 * that any Event Hubs consumer can read.
 *
 * @see https://learn.microsoft.com/azure/iot-hub/iot-concepts-and-iot-hub
 *
 * ### Creating a Hub
 * **Example:** Standard hub
 * ```typescript
 * const group = yield* Azure.Resources.ResourceGroup("app");
 * const hub = yield* Azure.IoTHub.IotHub("devices", {
 *   resourceGroup: group.resourceGroupName,
 * });
 * ```
 *
 * **Example:** Free hub (one per subscription)
 * ```typescript
 * const hub = yield* Azure.IoTHub.IotHub("devices", {
 *   resourceGroup: group.resourceGroupName,
 *   sku: "F1",
 *   partitionCount: 2,
 * });
 * ```
 *
 * ### Messaging Settings
 * **Example:** Cloud-to-device settings and retention
 * ```typescript
 * const hub = yield* Azure.IoTHub.IotHub("devices", {
 *   resourceGroup: group.resourceGroupName,
 *   sku: "S1",
 *   retentionTimeInDays: 3,
 *   cloudToDevice: {
 *     maxDeliveryCount: 20,
 *     defaultTtlAsIso8601: "PT2H",
 *   },
 * });
 * ```
 *
 * ### Reading Telemetry
 * **Example:** Pass the Event Hub-compatible endpoint to a consumer
 * ```typescript
 * const hub = yield* Azure.IoTHub.IotHub("devices", {
 *   resourceGroup: group.resourceGroupName,
 * });
 * const consumers = yield* Azure.IoTHub.ConsumerGroup("analytics", {
 *   resourceGroup: group.resourceGroupName,
 *   iotHub: hub.iotHubName,
 * });
 * // hub.eventHubConnectionString + consumers.consumerGroupName
 * ```
 *
 * @resource
 */
export const IotHub = Resource<IotHub>("Azure.IoTHub.IotHub");

type ObservedHub = iothub.GetIotHubResourceResponse;

const lower = (value: string | undefined) =>
  value?.toLowerCase().replace(/\s/g, "");

const tierOf = (sku: string | undefined) => sku?.[0]?.toUpperCase();

/**
 * Ready once ARM reports `Succeeded` and the hub itself is `Active`;
 * children and updates are rejected while it is still activating.
 */
const readiness = (hub: ObservedHub) => {
  const state = hub.properties?.provisioningState;
  const status = hub.properties?.state;
  if (state === "Succeeded" && status !== undefined && status !== "Active") {
    return status;
  }
  return state;
};

const ownerKey = (keys: iothub.SharedAccessSignatureAuthorizationRule[]) =>
  keys.find((rule) => rule.keyName === "iothubowner")?.primaryKey;

const toAttrs = (
  resourceGroup: string,
  name: string,
  hub: ObservedHub,
  keys: iothub.SharedAccessSignatureAuthorizationRule[] = [],
): IotHub["Attributes"] => {
  const events = hub.properties?.eventHubEndpoints?.events;
  const hostName = hub.properties?.hostName;
  const key = ownerKey(keys);
  return {
    iotHubName: name,
    iotHubId: hub.id ?? "",
    resourceGroup,
    location: hub.location,
    sku: hub.sku.name,
    capacity: hub.sku.capacity,
    hostName,
    state: hub.properties?.state,
    eventHubEndpoint: events?.endpoint,
    eventHubPath: events?.path,
    partitionIds: [...(events?.partitionIds ?? [])],
    partitionCount: events?.partitionCount,
    retentionTimeInDays: events?.retentionTimeInDays,
    principalId: hub.identity?.principalId,
    primaryKey: key ? Redacted.make(key) : undefined,
    primaryConnectionString:
      key && hostName
        ? Redacted.make(
            `HostName=${hostName};SharedAccessKeyName=iothubowner;SharedAccessKey=${key}`,
          )
        : undefined,
    eventHubConnectionString:
      key && events?.endpoint && events.path
        ? Redacted.make(
            `Endpoint=${events.endpoint};SharedAccessKeyName=iothubowner;SharedAccessKey=${key};EntityPath=${events.path}`,
          )
        : undefined,
    tags: userTags(hub.tags),
  };
};

const listKeys = (
  subscriptionId: string,
  resourceGroupName: string,
  resourceName: string,
) =>
  iothub
    .ListIotHubResourceKeys({ subscriptionId, resourceGroupName, resourceName })
    .pipe(Effect.map((result) => [...(result.value ?? [])]));

/** Properties that are only honoured at creation. */
const createOnly = (news: IotHubProps) => ({
  minTlsVersion: news.minTlsVersion,
  enableDataResidency: news.enableDataResidency,
});

/** Mutable properties the user set (undefined = keep observed). */
const mutableProps = (news: IotHubProps) => ({
  cloudToDevice: news.cloudToDevice,
  routing: news.routing,
  storageEndpoints: news.storageEndpoints,
  messagingEndpoints: news.messagingEndpoints,
  enableFileUploadNotifications: news.enableFileUploadNotifications,
  disableLocalAuth: news.disableLocalAuth,
  disableDeviceSAS: news.disableDeviceSAS,
  disableModuleSAS: news.disableModuleSAS,
  publicNetworkAccess: news.publicNetworkAccess,
  ipFilterRules: news.ipFilterRules,
  networkRuleSets: news.networkRuleSets,
  restrictOutboundNetworkAccess: news.restrictOutboundNetworkAccess,
  allowedFqdnList: news.allowedFqdnList,
  features: news.features,
  comments: news.comments,
});

const identityInput = (
  identity: IotHubProps["identity"],
): iothub.ArmIdentityInput | undefined =>
  identity === undefined
    ? undefined
    : {
        type: identity.type,
        userAssignedIdentities: identity.userAssignedIdentities?.length
          ? Object.fromEntries(
              identity.userAssignedIdentities.map((id) => [id, {}]),
            )
          : undefined,
      };

const identityMatches = (
  desired: IotHubProps["identity"],
  observed: iothub.ArmIdentity | undefined,
) => {
  if (desired === undefined) return true;
  if (lower(desired.type) !== lower(observed?.type ?? "None")) return false;
  const want = (desired.userAssignedIdentities ?? []).map((id) =>
    id.toLowerCase(),
  );
  const have = Object.keys(observed?.userAssignedIdentities ?? {}).map((id) =>
    id.toLowerCase(),
  );
  return want.length === have.length && want.every((id) => have.includes(id));
};

/**
 * Desired authorization policies with keys filled in from the observed
 * policies, so a PUT never rotates keys the user did not set.
 */
const desiredPolicies = (
  desired: IotHubProps["authorizationPolicies"],
  observed: iothub.SharedAccessSignatureAuthorizationRule[],
): iothub.SharedAccessSignatureAuthorizationRule[] =>
  desired === undefined
    ? observed
    : desired.map((policy) => {
        const current = observed.find((o) => o.keyName === policy.keyName);
        return {
          keyName: policy.keyName,
          rights: policy.rights,
          primaryKey: policy.primaryKey ?? current?.primaryKey,
          secondaryKey: policy.secondaryKey ?? current?.secondaryKey,
        };
      });

const policiesMatch = (
  desired: IotHubProps["authorizationPolicies"],
  observed: iothub.SharedAccessSignatureAuthorizationRule[],
) =>
  desired === undefined ||
  (desired.length === observed.length &&
    desired.every((policy) => {
      const current = observed.find((o) => o.keyName === policy.keyName);
      return (
        current !== undefined &&
        lower(current.rights) === lower(policy.rights) &&
        (policy.primaryKey === undefined ||
          policy.primaryKey === current.primaryKey) &&
        (policy.secondaryKey === undefined ||
          policy.secondaryKey === current.secondaryKey)
      );
    }));

export const IotHubProvider = () =>
  Provider.succeed(IotHub, {
    stables: [
      "iotHubName",
      "iotHubId",
      "resourceGroup",
      "location",
      "hostName",
      "eventHubEndpoint",
      "eventHubPath",
    ],

    list: Effect.fn(function* () {
      const { subscriptionId } = yield* AzureEnvironment.current;
      const page = yield* iothub
        .ListIotHubResourceBySubscription({ subscriptionId })
        .pipe(
          Effect.flatMap((page) =>
            requireSinglePage("ListIotHubResourceBySubscription", page),
          ),
        );
      return (page.value ?? []).flatMap((hub) => {
        const group = resourceGroupOf(hub.id);
        return hasAnyAlchemyTag(hub.tags) &&
          group !== undefined &&
          hub.name !== undefined
          ? [toAttrs(group, hub.name, hub)]
          : [];
      });
    }),

    diff: Effect.fn(function* ({ news, olds, output }) {
      if (!isResolved(news) || output === undefined) return undefined;
      const newTier = tierOf(news.sku ?? "S1");
      const oldTier = tierOf(output.sku);
      const replace =
        lower(news.resourceGroup) !== lower(output.resourceGroup) ||
        (news.name !== undefined &&
          lower(news.name) !== lower(output.iotHubName)) ||
        (news.location !== undefined &&
          lower(news.location) !== lower(output.location)) ||
        (newTier !== oldTier &&
          (newTier === "F" || oldTier === "F" || newTier === "B")) ||
        (news.partitionCount !== undefined &&
          output.partitionCount !== undefined &&
          news.partitionCount !== output.partitionCount) ||
        (olds !== undefined &&
          (news.minTlsVersion !== olds.minTlsVersion ||
            (news.enableDataResidency ?? false) !==
              (olds.enableDataResidency ?? false)));
      if (!replace) return undefined;
      // F1 is limited to one hub per subscription, and an explicit name is
      // globally unique: the old hub must go before its replacement exists.
      const deleteFirst =
        newTier === "F" ||
        oldTier === "F" ||
        (news.name !== undefined &&
          lower(news.name) === lower(output.iotHubName));
      return { action: "replace", deleteFirst } as const;
    }),

    read: Effect.fn(function* ({ id, olds, output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      const resourceGroup = output?.resourceGroup ?? olds?.resourceGroup;
      // An interrupted create can persist props with unresolved holes;
      // nothing can exist without its resource group.
      if (resourceGroup === undefined) return undefined;
      const name =
        output?.iotHubName ?? olds?.name ?? (yield* createIotHubName(id));
      const observed = yield* getIotHub(subscriptionId, resourceGroup, name);
      if (observed === undefined) return undefined;
      const attrs = toAttrs(resourceGroup, name, observed);
      return (yield* isOwned(id, observed.tags)) ? attrs : Unowned(attrs);
    }),

    reconcile: Effect.fn(function* ({ id, news, output }) {
      const env = yield* AzureEnvironment.current;
      const { subscriptionId } = env;
      yield* ensureRegistered(subscriptionId, "Microsoft.Devices");
      const resourceGroup = news.resourceGroup;
      const name =
        news.name ?? output?.iotHubName ?? (yield* createIotHubName(id));
      const location = news.location ?? output?.location ?? env.location;
      const tags = yield* desiredTags(id, news.tags);
      const sku = { name: news.sku ?? "S1", capacity: news.capacity ?? 1 };
      const desired = mutableProps(news);
      const where = {
        subscriptionId,
        resourceGroupName: resourceGroup,
        resourceName: name,
      };
      const label = `iot hub ${name}`;
      const get = getIotHub(subscriptionId, resourceGroup, name);
      const waitReady = waitForProvisioned(label, get, readiness, {
        interval: "10 seconds",
        times: 60,
      });

      // Observe.
      let observed = yield* get;

      // Ensure. Creation is a long-running operation (~1-3 minutes).
      if (observed === undefined) {
        yield* iothub.IotHubResourceCreateOrUpdate({
          ...where,
          location,
          sku,
          tags,
          identity: identityInput(news.identity),
          properties: {
            ...desired,
            ...createOnly(news),
            authorizationPolicies: news.authorizationPolicies,
            eventHubEndpoints: {
              events: {
                partitionCount: news.partitionCount,
                // An omitted retention is sent as 0 and rejected (IH400017).
                retentionTimeInDays: news.retentionTimeInDays ?? 1,
              },
            },
          },
        });
      }
      observed = yield* waitReady;

      // Sync SKU, identity, and properties against observed state. The hub
      // only accepts full-document PUTs (PATCH is tags-only), so any delta
      // re-sends the observed document with the desired values merged in.
      const props = observed.properties ?? {};
      const events = props.eventHubEndpoints?.events;
      const keys = yield* listKeys(subscriptionId, resourceGroup, name);
      const propsChanged =
        !matchesObserved(desired, props) ||
        !policiesMatch(news.authorizationPolicies, keys) ||
        (news.retentionTimeInDays !== undefined &&
          news.retentionTimeInDays !== events?.retentionTimeInDays);
      const skuChanged =
        observed.sku.name !== sku.name ||
        (observed.sku.capacity ?? 1) !== sku.capacity;
      const identityChanged = !identityMatches(
        news.identity,
        observed.identity,
      );
      const tagsChanged = tagsDiffer(observed.tags, tags);

      if (propsChanged || skuChanged || identityChanged) {
        const defined = Object.fromEntries(
          Object.entries(desired).filter(([, value]) => value !== undefined),
        );
        yield* iothub.IotHubResourceCreateOrUpdate({
          ...where,
          ifMatch: observed.etag,
          etag: observed.etag,
          location: observed.location,
          sku,
          tags,
          identity:
            news.identity !== undefined
              ? identityInput(news.identity)
              : observed.identity?.type
                ? {
                    type: observed.identity.type,
                    userAssignedIdentities: observed.identity
                      .userAssignedIdentities
                      ? Object.fromEntries(
                          Object.keys(
                            observed.identity.userAssignedIdentities,
                          ).map((key) => [key, {}]),
                        )
                      : undefined,
                  }
                : undefined,
          properties: {
            authorizationPolicies: desiredPolicies(
              news.authorizationPolicies,
              keys,
            ),
            disableLocalAuth: props.disableLocalAuth,
            disableDeviceSAS: props.disableDeviceSAS,
            disableModuleSAS: props.disableModuleSAS,
            restrictOutboundNetworkAccess: props.restrictOutboundNetworkAccess,
            allowedFqdnList: props.allowedFqdnList,
            publicNetworkAccess: props.publicNetworkAccess,
            ipFilterRules: props.ipFilterRules,
            networkRuleSets: props.networkRuleSets,
            minTlsVersion: props.minTlsVersion,
            routing: props.routing as iothub.RoutingPropertiesInput | undefined,
            storageEndpoints: props.storageEndpoints,
            messagingEndpoints: props.messagingEndpoints,
            enableFileUploadNotifications: props.enableFileUploadNotifications,
            cloudToDevice: props.cloudToDevice,
            comments: props.comments,
            features: props.features,
            enableDataResidency: props.enableDataResidency,
            ...defined,
            eventHubEndpoints: {
              events: {
                partitionCount: events?.partitionCount,
                retentionTimeInDays:
                  news.retentionTimeInDays ?? events?.retentionTimeInDays,
              },
            },
          },
        });
        observed = yield* waitReady;
      } else if (tagsChanged) {
        yield* iothub.UpdateIotHubResource({ ...where, tags });
        observed = yield* waitReady;
      }

      const finalKeys =
        news.authorizationPolicies === undefined
          ? keys
          : yield* listKeys(subscriptionId, resourceGroup, name);
      return toAttrs(resourceGroup, name, observed, finalKeys);
    }),

    delete: Effect.fn(function* ({ output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      yield* ignoreNotFound(
        iothub.DeleteIotHubResource({
          subscriptionId,
          resourceGroupName: output.resourceGroup,
          resourceName: output.iotHubName,
        }),
      );
      yield* waitUntilGone(
        `iot hub ${output.iotHubName}`,
        getIotHub(subscriptionId, output.resourceGroup, output.iotHubName),
        { interval: "10 seconds", times: 60 },
      );
    }),

    nuke: {
      dependsOn: ["Azure.Resources.ResourceGroup"],
    },
  });
