/**
 * `@alchemy.run/frontend-frameworks/nextjs/aws` — Next.js on AWS Lambda via
 * `@opennextjs/aws`.
 *
 * Unlike the Cloudflare Next.js integration (`./index.ts`, a
 * `Layer<Framework>` over the `@opennextjs/cloudflare` pipeline), this module
 * exports the standalone framework-module contract alchemy's
 * `AWS.Website.Server` resource drives directly: `make(options)` resolves to
 * `{ build, dev }`.
 *
 * - **`build`** drives the *programmatic* `@opennextjs/aws` build pipeline
 *   (`aws-runner.mjs` — no `open-next` CLI binary, no shelled `next build`;
 *   the app is built through the project's own `next/dist/build`) in a
 *   disposable child process — the pipeline mutates cwd-coupled module
 *   state and can `process.exit(1)`, so it must never run in the calling
 *   process. The OpenNext config is synthesized from alchemy props
 *   (`openNext` merged over the streaming `aws-lambda-streaming` default,
 *   so the emitted handler streams on a Lambda Function URL with
 *   `invokeMode: RESPONSE_STREAM`) unless the project has a user-authored
 *   `open-next.config.ts`, which is honored as-is. After the build, the
 *   authoritative `.open-next/open-next.output.json` manifest is read to
 *   verify the default origin is a streaming function.
 * - **`dev`** runs the real `next dev` through Next's documented custom-server
 *   API (`next({ dev: true })` + `prepare()` + `getRequestHandler()` on an
 *   http server we own) — plain Node, which is already the AWS Lambda
 *   programming model. Scoped: closing the Scope stops the app and the server.
 *
 * The OpenNext output topology the alchemy composite (`AWS.Website.Nextjs`)
 * deploys from `.open-next/`:
 *
 * - `server-functions/default/` — the SSR server Lambda (`index.handler`)
 * - `image-optimization-function/` — the image optimizer Lambda (sharp, arm64)
 * - `revalidation-function/` — the ISR revalidation consumer Lambda
 * - `assets/` — static assets for the CDN (`_next/static`, `public/`, BUILD_ID)
 * - `cache/` — the ISR/fetch cache seed (uploaded under the cache prefix)
 * - `dynamodb-provider/` — the tag-cache table seed function
 */
import * as FrameworkCore from "../core/index.ts";
import * as NodeChildProcessSpawner from "@effect/platform-node/NodeChildProcessSpawner";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Layer from "effect/Layer";
import * as Path from "effect/Path";
import type { PlatformError } from "effect/PlatformError";
import type * as Scope from "effect/Scope";
import * as Stream from "effect/Stream";
import * as ChildProcess from "effect/unstable/process/ChildProcess";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import type * as NodeChildProcessModule from "node:child_process";
import type * as NodeNet from "node:net";

const fail = (message: string) => (cause: unknown) =>
  new FrameworkCore.FrameworkError({ framework: "nextjs", message, cause });

/** Options for the Next.js AWS framework module. */
export interface NextjsAwsOptions {
  /** Project root. Defaults to the process working directory. */
  readonly root?: string | undefined;
  /**
   * The deploy target module specifier the caller resolved this module as.
   * This module IS the AWS target — the option is accepted (the
   * `AWS.Website.Server` resource always passes it) and ignored.
   */
  readonly target?: string | undefined;
  /**
   * Path of the OpenNext config, relative to the project root. When the file
   * does not exist (or was generated by alchemy), it is synthesized from
   * {@link NextjsAwsOptions.openNext} merged over the streaming default. A
   * user-authored file is honored as-is.
   * @default "open-next.config.ts"
   */
  readonly configPath?: string | undefined;
  /**
   * OpenNext configuration, expressed as alchemy props. Deep-merged over the
   * streaming default (`default.override.wrapper: "aws-lambda-streaming"`)
   * and written to the synthesized config. JSON-serializable values only —
   * for function-valued overrides, author your own `open-next.config.ts`
   * (a user-authored file takes precedence over this prop).
   */
  readonly openNext?: OpenNextConfigInput | undefined;
  /**
   * Skip the Next.js build and reuse an existing `.next` directory.
   * @default false
   */
  readonly skipNextBuild?: boolean | undefined;
  /**
   * Enable OpenNext debug logging.
   * @default false
   */
  readonly debug?: boolean | undefined;
  /**
   * Proceed when the project's Next.js version is outside OpenNext's
   * supported range.
   * @default false
   */
  readonly dangerouslyUseUnsupportedNextVersion?: boolean | undefined;
}

/**
 * The structural slice of OpenNext's config this module accepts as props.
 * JSON-serializable values only (the config crosses a process boundary);
 * OpenNext's function-valued overrides need a real `open-next.config.ts`.
 */
export interface OpenNextConfigInput {
  /** The default server function's configuration. */
  readonly default?: {
    /**
     * Named overrides (wrapper, converter, incrementalCache, queue,
     * tagCache, ...). Alchemy's default sets
     * `wrapper: "aws-lambda-streaming"` — required by the streaming Lambda
     * Function URL the AWS topology deploys.
     */
    readonly override?: Record<string, unknown>;
    readonly minify?: boolean;
    readonly [key: string]: unknown;
  };
  /** Additional (split) server functions. */
  readonly functions?: Record<string, unknown>;
  /** Image-optimization function configuration. */
  readonly imageOptimization?: Record<string, unknown>;
  /** Middleware configuration. */
  readonly middleware?: Record<string, unknown>;
  /** OpenNext escape hatches (e.g. `disableIncrementalCache`). */
  readonly dangerous?: Record<string, unknown>;
  readonly [key: string]: unknown;
}

/** The default server-module name of the server's Lambda entry (the actual
 * name is derived from `open-next.output.json` after the build). */
export const SERVER_ENTRY_NAME = "server-functions/default/index.mjs";

/**
 * Derive the entry-module name (relative to `.open-next/`) from the output
 * manifest's default origin: `bundle` (e.g. `.open-next/server-functions/
 * default`) plus the file half of `handler` (`index.handler` → `index.mjs`).
 */
export const deriveServerEntryName = (origin: {
  readonly handler?: string;
  readonly bundle?: string;
}): string => {
  const bundle = (origin.bundle ?? ".open-next/server-functions/default")
    .replace(/^\.open-next\//, "")
    .replace(/\/+$/, "");
  const handler = origin.handler ?? "index.handler";
  const file = handler.split(".").slice(0, -1).join(".") || "index";
  return `${bundle}/${file}.mjs`;
};

/**
 * Marker identifying an alchemy-synthesized `open-next.config.ts`. A file
 * carrying it is alchemy-owned and regenerated from props on every build; a
 * file without it is user-authored and honored as-is.
 */
export const GENERATED_CONFIG_MARKER =
  "Generated by @alchemy.run/frontend-frameworks/nextjs/aws";

/**
 * The streaming default the synthesized config starts from: the default
 * (and only) server uses the `aws-lambda-streaming` wrapper so the emitted
 * handler wraps `awslambda.streamifyResponse` and expects a Function URL
 * with `invokeMode: RESPONSE_STREAM`.
 */
export const DEFAULT_OPEN_NEXT_CONFIG_INPUT: OpenNextConfigInput = {
  default: {
    override: {
      wrapper: "aws-lambda-streaming",
    },
  },
};

/** Deep-merge JSON-shaped OpenNext config objects (`overrides` wins;
 * objects merge recursively, everything else replaces). */
export const mergeOpenNextConfig = (
  base: OpenNextConfigInput,
  overrides: OpenNextConfigInput | undefined,
): OpenNextConfigInput => {
  if (overrides === undefined) return base;
  const isPlainObject = (value: unknown): value is Record<string, unknown> =>
    typeof value === "object" && value !== null && !Array.isArray(value);
  const merged: Record<string, unknown> = { ...base };
  for (const [key, value] of Object.entries(overrides)) {
    const existing = merged[key];
    merged[key] =
      isPlainObject(existing) && isPlainObject(value)
        ? mergeOpenNextConfig(existing, value)
        : value;
  }
  return merged;
};

/**
 * Render the synthesized `open-next.config.ts` from the merged config
 * object ({@link DEFAULT_OPEN_NEXT_CONFIG_INPUT} + `openNext` props).
 */
export const renderOpenNextConfig = (config: OpenNextConfigInput): string =>
  `// ${GENERATED_CONFIG_MARKER}.
// Synthesized from alchemy props (openNext) — do not edit, this file is
// regenerated on every build. Delete the marker line above (or replace the
// file) to take ownership; keep the streaming wrapper — the Function URL is
// created with invokeMode: RESPONSE_STREAM.
const config = ${JSON.stringify(config, null, 2)};

export default config;
`;

/** The structural slice of `open-next.output.json` this module reads. */
interface OpenNextOutputManifest {
  readonly origins?: {
    readonly default?: {
      readonly type?: string;
      readonly handler?: string;
      readonly bundle?: string;
      readonly streaming?: boolean;
    };
  };
}

/**
 * Verify `@opennextjs/aws` resolves from the *project's* dependency tree
 * (the runner imports its build modules from there). The package's exports
 * map has only a `"./*" -> "./dist/*"` pattern (no `"."` and no
 * `./package.json` subpath), so the `index.js` subpath is the one stable
 * resolvable path.
 */
const checkOpenNextResolvable = (root: string) =>
  Effect.try({
    try: () => {
      const require = createRequire(`${root.replace(/\/+$/, "")}/package.json`);
      return require.resolve("@opennextjs/aws/index.js");
    },
    catch: fail(
      `Failed to resolve "@opennextjs/aws" from ${root}. ` +
        "It must be installed in your project (it drives the Next.js build).",
    ),
  });

/** Absolute path of the programmatic build runner (`aws-runner.mjs`). */
export const awsRunnerPath = (): string =>
  fileURLToPath(new URL("../nextjs/aws-runner.mjs", import.meta.url));

/** The JSON configuration passed to `aws-runner.mjs` (as `process.argv[2]`). */
interface AwsRunnerConfig {
  readonly appDir: string;
  readonly configPath: string;
  readonly skipNextBuild: boolean;
  readonly debug: boolean;
  readonly dangerouslyUseUnsupportedNextVersion: boolean;
}

/**
 * Run the programmatic `@opennextjs/aws` build pipeline (`aws-runner.mjs`)
 * in a disposable node child process with the project root as cwd. The
 * pipeline mutates cwd-coupled module state and can `process.exit(1)`, so
 * it must never run in the calling process. Output is piped and re-emitted
 * through the parent's own stdout/stderr JS streams (NOT `stdio:
 * "inherit"`) so in-process capture — a test runner's log file — sees the
 * build output.
 */
const runOpenNextBuild = (options: {
  readonly root: string;
  readonly runnerConfig: AwsRunnerConfig;
}) =>
  Effect.scoped(
    Effect.gen(function* () {
      // Always plain `node` (never bun/`process.execPath`) — the AWS Lambda
      // programming model, and the runner's in-process env mutations
      // (NEXT_PRIVATE_STANDALONE) behave uniformly.
      const child = yield* ChildProcess.make(
        "node",
        [awsRunnerPath(), JSON.stringify(options.runnerConfig)],
        {
          cwd: options.root,
          stdin: "ignore",
          stdout: "pipe",
          stderr: "pipe",
        },
      ).pipe(
        Effect.mapError(
          fail(
            "Failed to spawn the OpenNext build runner (is `node` on PATH?)",
          ),
        ),
      );
      const forward = (
        stream: Stream.Stream<Uint8Array, PlatformError>,
        dest: NodeJS.WriteStream,
      ) =>
        Stream.runForEach(stream, (chunk) =>
          Effect.sync(() => dest.write(chunk)),
        );
      const { exitCode } = yield* Effect.all(
        {
          exitCode: child.exitCode,
          stdout: forward(child.stdout, process.stdout),
          stderr: forward(child.stderr, process.stderr),
        },
        { concurrency: "unbounded" },
      ).pipe(
        Effect.mapError(fail("Failed reading the OpenNext build's output")),
      );
      if (exitCode !== 0) {
        return yield* Effect.fail(
          fail(`The OpenNext build exited with code ${exitCode}`)(undefined),
        );
      }
    }),
  );

// ---------------------------------------------------------------------------
// dev — the real `next dev` CLI in a child process
// ---------------------------------------------------------------------------

/**
 * Resolve the *project's* `next` CLI entry (`next/dist/bin/next`). The
 * app's installed copy is the one driven, never a hoisted sibling.
 */
const resolveNextCli = (root: string) =>
  Effect.try({
    try: () => {
      const require = createRequire(`${root.replace(/\/+$/, "")}/package.json`);
      return require.resolve("next/dist/bin/next");
    },
    catch: fail(
      `Failed to resolve "next" from ${root}. ` +
        "It must be installed in your project.",
    ),
  });

/** Bind an ephemeral port and release it, returning the port number. */
const pickEphemeralPort: Effect.Effect<number, FrameworkCore.FrameworkError> =
  Effect.callback((resume) => {
    const net = createRequire(import.meta.url)("net") as typeof NodeNet;
    const server = net.createServer();
    server.once("error", (cause) =>
      resume(Effect.fail(fail("Failed to allocate an ephemeral port")(cause))),
    );
    server.listen(0, "127.0.0.1", () => {
      const address = server.address();
      if (address === null || typeof address === "string") {
        server.close();
        resume(Effect.fail(fail("No TCP address for the port probe")(null)));
        return;
      }
      const port = address.port;
      server.close(() => resume(Effect.succeed(port)));
    });
  });

interface NextDevChild {
  readonly exited: () => boolean;
  readonly output: () => string;
}

/**
 * Spawn `node <next CLI> dev -p <port>` with the project root as cwd,
 * scoped: closing the Scope kills the process tree (SIGTERM, then SIGKILL).
 * Always plain `node` — the AWS Lambda programming model.
 */
const spawnNextDev = (options: {
  readonly root: string;
  readonly cli: string;
  readonly port: number;
  readonly host?: string | undefined;
}): Effect.Effect<NextDevChild, FrameworkCore.FrameworkError, Scope.Scope> =>
  Effect.acquireRelease(
    Effect.try({
      try: () => {
        const cp = createRequire(import.meta.url)(
          "child_process",
        ) as typeof NodeChildProcessModule;
        const child = cp.spawn(
          "node",
          [
            options.cli,
            "dev",
            "-p",
            String(options.port),
            ...(options.host !== undefined ? ["-H", options.host] : []),
          ],
          {
            cwd: options.root,
            stdio: ["ignore", "pipe", "pipe"],
            detached: false,
          },
        );
        let exited = false;
        let output = "";
        const capture = (chunk: unknown) => {
          output += String(chunk);
          if (output.length > 65536) output = output.slice(-32768);
          process.stderr.write(String(chunk));
        };
        child.stdout?.on("data", capture);
        child.stderr?.on("data", capture);
        child.once("exit", () => {
          exited = true;
        });
        return {
          child,
          handle: {
            exited: () => exited,
            output: () => output,
          } satisfies NextDevChild,
        };
      },
      catch: fail("Failed to spawn the next dev CLI (is `node` on PATH?)"),
    }),
    ({ child }) =>
      Effect.callback<void>((resume) => {
        if (child.exitCode !== null) {
          resume(Effect.void);
          return;
        }
        const killTimer = setTimeout(() => child.kill("SIGKILL"), 3000);
        child.once("exit", () => {
          clearTimeout(killTimer);
          resume(Effect.void);
        });
        child.kill("SIGTERM");
      }),
  ).pipe(Effect.map(({ handle }) => handle));

/**
 * Poll the dev server URL until it answers any HTTP response. Fails fast
 * when the child exits before becoming ready.
 */
const awaitNextDevReady = (options: {
  readonly url: string;
  readonly child: NextDevChild;
}): Effect.Effect<void, FrameworkCore.FrameworkError> =>
  Effect.gen(function* () {
    for (let attempt = 0; attempt < 240; attempt++) {
      if (options.child.exited()) {
        return yield* Effect.fail(
          fail(
            `The next dev CLI exited before becoming ready:\n${options.child.output().slice(-4000)}`,
          )(undefined),
        );
      }
      const ready = yield* Effect.tryPromise({
        try: async () => {
          const response = await fetch(options.url, {
            signal: AbortSignal.timeout(2000),
          });
          return response.status < 600;
        },
        catch: () => "not-ready" as const,
      }).pipe(Effect.orElseSucceed(() => false));
      if (ready) return;
      yield* Effect.sleep(500);
    }
    return yield* Effect.fail(
      fail(`Timed out waiting for the next dev server at ${options.url}`)(
        undefined,
      ),
    );
  });

/** The service shape {@link make} resolves to (the framework-module contract
 * `AWS.Website.Server` drives; `serverModules` carries names only — the AWS
 * deploy ships the OpenNext bundles from disk, never in-memory). */
export interface NextjsAwsService {
  readonly build: (
    options?: FrameworkCore.FrameworkBuildOptions,
  ) => Effect.Effect<
    {
      readonly distDirectory: string;
      readonly clientDirectory: string;
      readonly serverModules: Array<{ readonly name: string }>;
    },
    FrameworkCore.FrameworkError
  >;
  readonly dev: (
    options?: FrameworkCore.FrameworkDevOptions,
  ) => Effect.Effect<
    FrameworkCore.FrameworkDevServer,
    FrameworkCore.FrameworkError,
    Scope.Scope
  >;
}

/**
 * Build the Next.js-on-AWS framework service. See the module doc for the
 * `build`/`dev` semantics.
 */
export const make: (
  options?: NextjsAwsOptions,
) => Effect.Effect<NextjsAwsService, never, FileSystem.FileSystem | Path.Path> =
  Effect.fnUntraced(function* (options?: NextjsAwsOptions) {
    const fs = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;

    const fsPathLayer = Layer.merge(
      Layer.succeed(FileSystem.FileSystem)(fs),
      Layer.succeed(Path.Path)(path),
    );
    const spawnerLayer = NodeChildProcessSpawner.layer.pipe(
      Layer.provide(fsPathLayer),
    );

    const resolveRoot = (override: string | undefined) =>
      Effect.sync(() =>
        path.resolve(override ?? options?.root ?? process.cwd()),
      );

    const build: NextjsAwsService["build"] = Effect.fn(function* (
      buildOptions?: FrameworkCore.FrameworkBuildOptions,
    ) {
      const root = yield* resolveRoot(buildOptions?.root);
      const configPath = options?.configPath ?? "open-next.config.ts";

      // Synthesize the OpenNext config from alchemy props unless the user
      // authored one. A missing file — or one carrying the alchemy marker —
      // is (re)generated from `openNext` props merged over the streaming
      // default, so props are the source of truth for alchemy-owned configs.
      // The file lands in the project root (OpenNext resolves it relative to
      // its cwd) and is left in place so subsequent builds — and the memo
      // input hash — see a stable tree.
      const absoluteConfigPath = path.resolve(root, configPath);
      const existingConfig = yield* fs
        .readFileString(absoluteConfigPath)
        .pipe(Effect.orElseSucceed(() => undefined));
      const alchemyOwned =
        existingConfig === undefined ||
        existingConfig.includes(GENERATED_CONFIG_MARKER);
      if (alchemyOwned) {
        const synthesized = renderOpenNextConfig(
          mergeOpenNextConfig(
            DEFAULT_OPEN_NEXT_CONFIG_INPUT,
            options?.openNext,
          ),
        );
        if (existingConfig !== synthesized) {
          yield* fs
            .writeFileString(absoluteConfigPath, synthesized)
            .pipe(
              Effect.mapError(
                fail(
                  `Failed to write the synthesized OpenNext config at ${absoluteConfigPath}`,
                ),
              ),
            );
        }
      }

      yield* checkOpenNextResolvable(root);
      yield* runOpenNextBuild({
        root,
        runnerConfig: {
          appDir: root,
          configPath,
          skipNextBuild: options?.skipNextBuild ?? false,
          debug: options?.debug ?? false,
          dangerouslyUseUnsupportedNextVersion:
            options?.dangerouslyUseUnsupportedNextVersion ?? false,
        },
      }).pipe(Effect.provide(spawnerLayer));

      const distDirectory = path.join(root, ".open-next");
      const clientDirectory = path.join(distDirectory, "assets");

      // The authoritative manifest: verify the topology the composite deploys
      // (a streaming default server function) actually came out of the build.
      const manifestPath = path.join(distDirectory, "open-next.output.json");
      const manifestRaw = yield* fs
        .readFileString(manifestPath)
        .pipe(Effect.mapError(fail(`The build produced no ${manifestPath}`)));
      const manifest = yield* Effect.try({
        try: () => JSON.parse(manifestRaw) as OpenNextOutputManifest,
        catch: fail(`Failed to parse ${manifestPath}`),
      });
      const defaultOrigin = manifest.origins?.default;
      if (defaultOrigin?.type !== "function") {
        return yield* Effect.fail(
          fail(
            `The OpenNext build's default origin is "${defaultOrigin?.type}", not a Lambda function. ` +
              "The AWS deploy target only supports the function topology (no generateDockerfile).",
          )(undefined),
        );
      }
      if (defaultOrigin.streaming !== true) {
        return yield* Effect.fail(
          fail(
            "The OpenNext build's default server does not stream. The Lambda Function URL is " +
              "created with invokeMode: RESPONSE_STREAM, so open-next.config.ts must keep the streaming wrapper: " +
              '`default: { override: { wrapper: "aws-lambda-streaming" } }`.',
          )(undefined),
        );
      }

      const entryName = deriveServerEntryName(defaultOrigin);
      const entryPath = path.join(distDirectory, entryName);
      if (
        !(yield* fs.exists(entryPath).pipe(Effect.orElseSucceed(() => false)))
      ) {
        return yield* Effect.fail(
          fail(`The build produced no server entry at ${entryPath}`)(undefined),
        );
      }

      return {
        distDirectory,
        clientDirectory,
        serverModules: [{ name: entryName }],
      };
    });

    const dev: NextjsAwsService["dev"] = Effect.fn(function* (
      devOptions?: FrameworkCore.FrameworkDevOptions,
    ) {
      const root = yield* resolveRoot(devOptions?.root);
      const port = devOptions?.port ?? (yield* pickEphemeralPort);
      const cli = yield* resolveNextCli(root);
      const host = devOptions?.host;
      const child = yield* spawnNextDev({ root, cli, port, host });
      const url = `http://${host ?? "localhost"}:${port}`;
      yield* awaitNextDevReady({ url, child });
      return { url };
    });

    return { build, dev };
  });

export default make;
