import * as dashboard from "@distilled.cloud/azure/dashboard";
import * as Effect from "effect/Effect";
import * as Redacted from "effect/Redacted";
import * as Schedule from "effect/Schedule";
import { Unowned } from "../../AdoptPolicy.ts";
import { isResolved } from "../../Diff.ts";
import { createPhysicalName } from "../../PhysicalName.ts";
import * as Provider from "../../Provider.ts";
import { Resource } from "../../Resource.ts";
import {
  desiredTags,
  ensureRegistered,
  hasAnyAlchemyTag,
  ignoreNotFound,
  isOwned,
  orUndefinedIfNotFound,
  requireSinglePage,
  resourceGroupOf,
  tagsDiffer,
  userTags,
  waitForProvisioned,
  waitUntilGone,
} from "../Arm.ts";
import { AzureEnvironment } from "../Environment.ts";
import type { Providers } from "../Providers.ts";

export type GrafanaSkuName = "Standard" | "Essential";
export type GrafanaSkuSize = "X1" | "X2";
export type GrafanaToggle = "Enabled" | "Disabled";
export type GrafanaIdentityType =
  | "None"
  | "SystemAssigned"
  | "UserAssigned"
  | "SystemAssigned,UserAssigned";

export interface GrafanaIdentity {
  /** Identity type. `None` removes every identity. */
  type: GrafanaIdentityType;
  /** ARM IDs of user-assigned identities to attach. */
  userAssignedIdentities?: string[];
}

export interface GrafanaSmtp {
  /** Allow Grafana to send email. @default false */
  enabled?: boolean;
  /** SMTP server host with port, e.g. `smtp.example.com:587`. */
  host?: string;
  /** SMTP auth user. */
  user?: string;
  /**
   * SMTP auth password. Azure never returns it, so a change is detected
   * against the previously deployed value.
   */
  password?: Redacted.Redacted<string>;
  /** Sender address. */
  fromAddress?: string;
  /** Sender display name. */
  fromName?: string;
  /** STARTTLS policy. */
  startTLSPolicy?: "OpportunisticStartTLS" | "MandatoryStartTLS" | "NoStartTLS";
  /** Skip TLS certificate verification of the SMTP server. @default false */
  skipVerify?: boolean;
}

export interface GrafanaConfigurations {
  /** Email server settings. */
  smtp?: GrafanaSmtp;
  /** Snapshot settings. */
  snapshots?: {
    /** Allow publishing snapshots to the external snapshot endpoint. */
    externalEnabled?: boolean;
  };
  /** User settings. */
  users?: {
    /** Viewers can use Explore and make temporary panel edits. */
    viewersCanEdit?: boolean;
    /** Editors can administrate dashboards, folders, and teams they create. */
    editorsCanAdmin?: boolean;
  };
  /** Security settings. */
  security?: {
    /** Run the CSRF check even without a login cookie. */
    csrfAlwaysCheck?: boolean;
  };
  /** Unified alerting screenshot settings. */
  unifiedAlertingScreenshots?: {
    /** Capture screenshots in unified alerts. */
    captureEnabled?: boolean;
  };
}

export interface WorkspaceProps {
  /**
   * Resource group the workspace is created in. Changing it replaces the
   * workspace.
   */
  resourceGroup: string;
  /**
   * Workspace name: 2-23 letters, digits, and hyphens, starting with a
   * letter. If omitted, a unique name is generated from the app, stage, and
   * logical ID. Changing it replaces the workspace.
   */
  name?: string;
  /**
   * Azure location of the workspace. Changing it replaces the workspace.
   * @default the `Azure.Location` layer, else the profile location, else `eastus`
   */
  location?: string;
  /**
   * Pricing tier. `Essential` is retired for new workspaces. Changing it
   * replaces the workspace.
   * @default "Standard"
   */
  sku?: GrafanaSkuName;
  /**
   * Capacity of a `Standard` workspace.
   * @default Azure's default (`X1`)
   */
  size?: GrafanaSkuSize;
  /** Managed identity of the workspace (used by Azure data sources). */
  identity?: GrafanaIdentity;
  /**
   * Whether the Grafana endpoint accepts public traffic.
   * @default Azure's default (`Enabled`)
   */
  publicNetworkAccess?: GrafanaToggle;
  /**
   * Zone redundancy. Only settable at creation: changing it replaces the
   * workspace.
   * @default Azure's default (`Disabled`)
   */
  zoneRedundancy?: GrafanaToggle;
  /**
   * Whether Grafana API keys and service accounts may be created.
   * @default Azure's default (`Disabled`)
   */
  apiKey?: GrafanaToggle;
  /**
   * Grant the deploying principal the Grafana Admin role. Requires
   * permission to create role assignments on the workspace.
   * @default Azure's default
   */
  creatorCanAdmin?: GrafanaToggle;
  /**
   * Use deterministic outbound IPs (listed in `outboundIPs`).
   * @default Azure's default (`Disabled`)
   */
  deterministicOutboundIP?: GrafanaToggle;
  /**
   * Scope of the hash in the generated endpoint name. Changing it replaces
   * the workspace.
   */
  autoGeneratedDomainNameLabelScope?: "TenantReuse";
  /** ARM IDs of Azure Monitor workspaces to connect as data sources. */
  azureMonitorWorkspaceIntegrations?: string[];
  /** Grafana server configuration (SMTP, snapshots, users, security). */
  grafanaConfigurations?: GrafanaConfigurations;
  /**
   * IDs of extra Grafana plugins to install. When set, it is the complete
   * list.
   */
  grafanaPlugins?: string[];
  /**
   * Major Grafana version to run, e.g. `"11"`. Upgrades only.
   * @default Azure's default
   */
  grafanaMajorVersion?: string;
  /**
   * User tags. Alchemy ownership tags (`alchemy::stack`, `alchemy::stage`,
   * `alchemy::id`) are merged in automatically.
   */
  tags?: Record<string, string>;
}

export interface Workspace extends Resource<
  "Azure.Grafana.Workspace",
  WorkspaceProps,
  {
    /** Name of the workspace. */
    workspaceName: string;
    /** ARM resource ID of the workspace. */
    workspaceId: string;
    /** Resource group that holds the workspace. */
    resourceGroup: string;
    /** Location of the workspace. */
    location: string;
    /** Pricing tier. */
    sku: string;
    /** Capacity of the workspace, if reported. */
    size: string | undefined;
    /** Grafana URL, e.g. `https://{name}-{hash}.{region}.grafana.azure.com`. */
    endpoint: string | undefined;
    /** Running Grafana version. */
    grafanaVersion: string | undefined;
    /** Running Grafana major version. */
    grafanaMajorVersion: string | undefined;
    /** Outbound IPs when `deterministicOutboundIP` is enabled. */
    outboundIPs: string[];
    /** Principal ID of the system-assigned identity, if any. */
    principalId: string | undefined;
    /** Tenant ID of the system-assigned identity, if any. */
    tenantId: string | undefined;
    /** Whether zone redundancy is enabled. */
    zoneRedundancy: string | undefined;
    /** User tags (Alchemy ownership tags stripped). */
    tags: Record<string, string>;
  },
  never,
  Providers
> {}

/**
 * An Azure Managed Grafana workspace — a fully managed Grafana instance with
 * Microsoft Entra ID sign-in and built-in Azure Monitor data sources.
 *
 * Standard workspaces bill hourly (about $0.07/hour for X1) plus a fee per
 * active user. Provisioning takes a few minutes.
 *
 * @see https://learn.microsoft.com/azure/managed-grafana/overview
 *
 * ### Creating a Workspace
 * **Example:** Standard workspace with a system-assigned identity
 * ```typescript
 * const group = yield* Azure.Resources.ResourceGroup("observability");
 * const grafana = yield* Azure.Grafana.Workspace("grafana", {
 *   resourceGroup: group.resourceGroupName,
 *   identity: { type: "SystemAssigned" },
 * });
 * // grafana.endpoint is the Grafana URL
 * ```
 *
 * ### Connecting Data Sources
 * **Example:** Workspace wired to an Azure Monitor workspace (Prometheus)
 * ```typescript
 * const metrics = yield* Azure.Monitor.Workspace("metrics", {
 *   resourceGroup: group.resourceGroupName,
 * });
 * const grafana = yield* Azure.Grafana.Workspace("grafana", {
 *   resourceGroup: group.resourceGroupName,
 *   identity: { type: "SystemAssigned" },
 *   azureMonitorWorkspaceIntegrations: [metrics.workspaceId],
 * });
 * ```
 *
 * ### Configuring Grafana
 * **Example:** API keys, SMTP, and extra plugins
 * ```typescript
 * const grafana = yield* Azure.Grafana.Workspace("grafana", {
 *   resourceGroup: group.resourceGroupName,
 *   apiKey: "Enabled",
 *   grafanaConfigurations: {
 *     smtp: {
 *       enabled: true,
 *       host: "smtp.example.com:587",
 *       user: "grafana",
 *       password: Redacted.make(smtpPassword),
 *       fromAddress: "grafana@example.com",
 *     },
 *   },
 *   grafanaPlugins: ["grafana-polystat-panel"],
 * });
 * ```
 *
 * @resource
 */
export const Workspace = Resource<Workspace>("Azure.Grafana.Workspace");

type ObservedGrafana = dashboard.GetGrafanaResponse;

export const createGrafanaName = Effect.fn(function* (
  id: string,
  maxLength = 23,
) {
  const name = yield* createPhysicalName({
    id,
    maxLength,
    lowercase: true,
    delimiter: "-",
  });
  const cleaned = name.replace(/[^a-z0-9-]/g, "").replace(/-+$/, "");
  return /^[a-z]/.test(cleaned)
    ? cleaned
    : `g${cleaned}`.slice(0, maxLength).replace(/-+$/, "");
});

export const getGrafana = (
  subscriptionId: string,
  resourceGroupName: string,
  workspaceName: string,
) =>
  orUndefinedIfNotFound(
    dashboard.GetGrafana({ subscriptionId, resourceGroupName, workspaceName }),
  );

const lower = (value: string | undefined) => value?.toLowerCase();

const toAttrs = (
  resourceGroup: string,
  name: string,
  grafana: ObservedGrafana | dashboard.ManagedGrafana,
): Workspace["Attributes"] => {
  const props = grafana.properties;
  return {
    workspaceName: name,
    workspaceId: grafana.id ?? "",
    resourceGroup,
    location: grafana.location ?? "",
    sku: grafana.sku?.name ?? "",
    size: grafana.sku?.size,
    endpoint: props?.endpoint,
    grafanaVersion: props?.grafanaVersion,
    grafanaMajorVersion: props?.grafanaMajorVersion,
    outboundIPs: [...(props?.outboundIPs ?? [])],
    principalId: grafana.identity?.principalId,
    tenantId: grafana.identity?.tenantId,
    zoneRedundancy: props?.zoneRedundancy,
    tags: userTags(grafana.tags),
  };
};

/** Wire shape of the desired Grafana configuration (password as given). */
const toWireConfigurations = (
  config: GrafanaConfigurations,
): dashboard.GrafanaConfigurations => ({ ...config });

/**
 * Whether every value set in `desired` equals the observed value. Write-only
 * fields (the SMTP password) are skipped.
 */
const subsetMatches = (desired: unknown, observed: unknown): boolean => {
  if (desired === undefined) return true;
  if (
    desired !== null &&
    typeof desired === "object" &&
    !Array.isArray(desired)
  ) {
    const have =
      observed !== null && typeof observed === "object"
        ? (observed as Record<string, unknown>)
        : {};
    return Object.entries(desired as Record<string, unknown>).every(
      ([key, value]) =>
        key === "password" || subsetMatches(value, have[key]),
    );
  }
  return desired === observed;
};

const sameIdSet = (
  desired: ReadonlyArray<string>,
  observed: ReadonlyArray<string>,
) => {
  const want = new Set(desired.map((id) => id.toLowerCase()));
  const have = new Set(observed.map((id) => id.toLowerCase()));
  return want.size === have.size && [...want].every((id) => have.has(id));
};

const toIdentity = (
  identity: GrafanaIdentity,
): dashboard.CreateGrafanaRequestIdentity => ({
  type: identity.type,
  userAssignedIdentities:
    identity.userAssignedIdentities === undefined ||
    identity.userAssignedIdentities.length === 0
      ? undefined
      : Object.fromEntries(
          identity.userAssignedIdentities.map((id) => [id, {}]),
        ),
});

const identityMatches = (
  desired: GrafanaIdentity | undefined,
  observed: ObservedGrafana["identity"],
) => {
  if (desired === undefined) return true;
  const observedType = observed?.type ?? "None";
  if (
    lower(desired.type)?.replaceAll(" ", "") !==
    lower(observedType)?.replaceAll(" ", "")
  ) {
    return false;
  }
  return sameIdSet(
    desired.userAssignedIdentities ?? [],
    Object.keys(observed?.userAssignedIdentities ?? {}),
  );
};

const passwordOf = (config: GrafanaConfigurations | undefined) => {
  const password = config?.smtp?.password;
  return password === undefined
    ? undefined
    : Redacted.isRedacted(password)
      ? Redacted.value(password)
      : (password as string);
};

/**
 * Compute the PATCH body for the observed state, or `undefined` when the
 * workspace already matches. `passwordChanged` forces the configuration out
 * because Azure never returns the SMTP password.
 */
const computeDelta = (
  news: WorkspaceProps,
  observed: ObservedGrafana,
  tags: Record<string, string>,
  passwordChanged: boolean,
) => {
  const props = observed.properties ?? {};
  const properties: dashboard.ManagedGrafanaPropertiesUpdateParametersInput =
    {};
  for (const key of [
    "publicNetworkAccess",
    "apiKey",
    "creatorCanAdmin",
    "deterministicOutboundIP",
  ] as const) {
    const value = news[key];
    if (value !== undefined && lower(props[key]) !== lower(value)) {
      properties[key] = value;
    }
  }
  if (
    news.grafanaMajorVersion !== undefined &&
    props.grafanaMajorVersion !== news.grafanaMajorVersion
  ) {
    properties.grafanaMajorVersion = news.grafanaMajorVersion;
  }
  if (
    news.azureMonitorWorkspaceIntegrations !== undefined &&
    !sameIdSet(
      news.azureMonitorWorkspaceIntegrations,
      (props.grafanaIntegrations?.azureMonitorWorkspaceIntegrations ?? [])
        .map((integration) => integration.azureMonitorWorkspaceResourceId)
        .filter((id): id is string => id !== undefined),
    )
  ) {
    properties.grafanaIntegrations = {
      azureMonitorWorkspaceIntegrations:
        news.azureMonitorWorkspaceIntegrations.map((id) => ({
          azureMonitorWorkspaceResourceId: id,
        })),
    };
  }
  if (
    news.grafanaConfigurations !== undefined &&
    (passwordChanged ||
      !subsetMatches(news.grafanaConfigurations, props.grafanaConfigurations))
  ) {
    properties.grafanaConfigurations = toWireConfigurations(
      news.grafanaConfigurations,
    );
  }
  if (
    news.grafanaPlugins !== undefined &&
    !sameIdSet(news.grafanaPlugins, Object.keys(props.grafanaPlugins ?? {}))
  ) {
    properties.grafanaPlugins = Object.fromEntries(
      news.grafanaPlugins.map((id) => [id, {}]),
    );
  }
  const size =
    news.size !== undefined && lower(observed.sku?.size) !== lower(news.size)
      ? news.size
      : undefined;
  const identity = identityMatches(news.identity, observed.identity)
    ? undefined
    : toIdentity(news.identity!);
  const tagsChanged = tagsDiffer(observed.tags, tags);
  if (
    Object.keys(properties).length === 0 &&
    size === undefined &&
    identity === undefined &&
    !tagsChanged
  ) {
    return undefined;
  }
  return {
    properties: Object.keys(properties).length > 0 ? properties : undefined,
    sku:
      size === undefined
        ? undefined
        : { name: news.sku ?? observed.sku?.name ?? "Standard", size },
    identity,
    tags: tagsChanged ? tags : undefined,
  };
};

/** Creating a workspace takes a few minutes; deleting it about as long. */
const BUDGET = { interval: "10 seconds", times: 90 } as const;

export const WorkspaceProvider = () =>
  Provider.succeed(Workspace, {
    stables: [
      "workspaceName",
      "workspaceId",
      "resourceGroup",
      "location",
      "endpoint",
      "zoneRedundancy",
    ],

    list: Effect.fn(function* () {
      const { subscriptionId } = yield* AzureEnvironment.current;
      const page = yield* orUndefinedIfNotFound(
        dashboard.ListGrafana({ subscriptionId }),
      );
      if (page === undefined) return [];
      yield* requireSinglePage("ListGrafana", page);
      return (page.value ?? []).flatMap((grafana) => {
        const group = resourceGroupOf(grafana.id);
        return hasAnyAlchemyTag(grafana.tags) &&
          group !== undefined &&
          grafana.name !== undefined
          ? [toAttrs(group, grafana.name, grafana)]
          : [];
      });
    }),

    diff: Effect.fn(function* ({ news, output }) {
      if (!isResolved(news) || output === undefined) return undefined;
      if (
        lower(news.resourceGroup) !== lower(output.resourceGroup) ||
        (news.name !== undefined &&
          lower(news.name) !== lower(output.workspaceName)) ||
        (news.location !== undefined &&
          lower(news.location)?.replaceAll(" ", "") !==
            lower(output.location)?.replaceAll(" ", "")) ||
        lower(news.sku ?? "Standard") !== lower(output.sku) ||
        lower(news.zoneRedundancy ?? "Disabled") !==
          lower(output.zoneRedundancy ?? "Disabled")
      ) {
        return { action: "replace" } as const;
      }
      return undefined;
    }),

    read: Effect.fn(function* ({ id, olds, output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      const resourceGroup = output?.resourceGroup ?? olds?.resourceGroup;
      if (resourceGroup === undefined) return undefined;
      const name =
        output?.workspaceName ?? olds?.name ?? (yield* createGrafanaName(id));
      const observed = yield* getGrafana(subscriptionId, resourceGroup, name);
      if (observed === undefined) return undefined;
      const attrs = toAttrs(resourceGroup, name, observed);
      return (yield* isOwned(id, observed.tags)) ? attrs : Unowned(attrs);
    }),

    reconcile: Effect.fn(function* ({ id, news, olds, output }) {
      const env = yield* AzureEnvironment.current;
      const { subscriptionId } = env;
      yield* ensureRegistered(subscriptionId, "Microsoft.Dashboard");
      const resourceGroup = news.resourceGroup;
      const name =
        news.name ?? output?.workspaceName ?? (yield* createGrafanaName(id));
      const location = news.location ?? output?.location ?? env.location;
      const tags = yield* desiredTags(id, news.tags);
      const where = {
        subscriptionId,
        resourceGroupName: resourceGroup,
        workspaceName: name,
      };
      const get = getGrafana(subscriptionId, resourceGroup, name);
      const label = `Grafana workspace ${name}`;

      // Observe.
      let observed = yield* get;

      // Ensure. Creation is a long-running operation.
      if (observed === undefined) {
        yield* dashboard.CreateGrafana({
          ...where,
          location,
          sku: { name: news.sku ?? "Standard", size: news.size },
          identity:
            news.identity === undefined
              ? undefined
              : toIdentity(news.identity),
          tags,
          properties: {
            publicNetworkAccess: news.publicNetworkAccess,
            zoneRedundancy: news.zoneRedundancy,
            apiKey: news.apiKey,
            creatorCanAdmin: news.creatorCanAdmin,
            deterministicOutboundIP: news.deterministicOutboundIP,
            autoGeneratedDomainNameLabelScope:
              news.autoGeneratedDomainNameLabelScope,
            grafanaMajorVersion: news.grafanaMajorVersion,
            grafanaIntegrations:
              news.azureMonitorWorkspaceIntegrations === undefined
                ? undefined
                : {
                    azureMonitorWorkspaceIntegrations:
                      news.azureMonitorWorkspaceIntegrations.map((id) => ({
                        azureMonitorWorkspaceResourceId: id,
                      })),
                  },
            grafanaConfigurations:
              news.grafanaConfigurations === undefined
                ? undefined
                : toWireConfigurations(news.grafanaConfigurations),
            grafanaPlugins:
              news.grafanaPlugins === undefined
                ? undefined
                : Object.fromEntries(
                    news.grafanaPlugins.map((id) => [id, {}]),
                  ),
          },
        });
      }
      observed = yield* waitForProvisioned(
        label,
        get,
        (grafana) => grafana.properties?.provisioningState,
        BUDGET,
      );

      // Sync each mutable aspect against observed state; PATCH only deltas.
      // A freshly created workspace already carries the password.
      const passwordChanged =
        passwordOf(news.grafanaConfigurations) !==
        passwordOf(olds?.grafanaConfigurations);
      const delta = computeDelta(news, observed, tags, passwordChanged);
      if (delta !== undefined) {
        yield* dashboard.UpdateGrafana({ ...where, ...delta });
        observed = yield* waitForProvisioned(
          label,
          get,
          (grafana) =>
            computeDelta(news, grafana, tags, false) !== undefined
              ? "Updating"
              : grafana.properties?.provisioningState,
          BUDGET,
        );
      }

      return toAttrs(resourceGroup, name, observed);
    }),

    delete: Effect.fn(function* ({ output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      // A workspace still busy with an earlier operation rejects the delete
      // with a conflict; wait it out.
      const deleteOnce = ignoreNotFound(
        dashboard
          .DeleteGrafana({
            subscriptionId,
            resourceGroupName: output.resourceGroup,
            workspaceName: output.workspaceName,
          })
          .pipe(
            Effect.retry({
              while: (e) => e._tag === "Conflict" || e._tag === "ResourceConflict",
              schedule: Schedule.spaced("15 seconds"),
              times: 16,
            }),
          ),
      );
      yield* deleteOnce;
      // Deletion runs ~5-12 minutes. Its status reads hit occasional 5xx
      // bursts, and a failed background delete returns the workspace to
      // `Succeeded` — re-issue the delete then.
      const poll = getGrafana(
        subscriptionId,
        output.resourceGroup,
        output.workspaceName,
      ).pipe(
        Effect.retry({
          while: (e) =>
            e._tag === "InternalServerError" ||
            e._tag === "ServiceUnavailable" ||
            e._tag === "BadGateway" ||
            e._tag === "GatewayTimeout" ||
            e._tag === "TooManyRequests",
          schedule: Schedule.spaced("10 seconds"),
          times: 6,
        }),
        Effect.tap((grafana) =>
          grafana !== undefined &&
          grafana.properties?.provisioningState !== "Deleting"
            ? deleteOnce
            : Effect.void,
        ),
      );
      yield* waitUntilGone(
        `Grafana workspace ${output.workspaceName}`,
        poll,
        BUDGET,
      );
    }),

    nuke: { dependsOn: ["Azure.Resources.ResourceGroup"] },
  });
