/**
 * `@alchemy.run/web-frameworks/nextjs/aws` — Next.js on AWS Lambda via
 * `@opennextjs/aws`.
 *
 * Unlike the Cloudflare Next.js integration (`./index.ts`, a
 * `Layer<Framework>` over the `@opennextjs/cloudflare` pipeline), this module
 * exports the standalone framework-module contract alchemy's
 * `AWS.Website.Server` resource drives directly: `make(options)` resolves to
 * `{ build, dev }`.
 *
 * - **`build`** drives the `@opennextjs/aws` build CLI (resolved from the
 *   *project's* dependency tree) in a disposable child process — the pipeline
 *   mutates cwd-coupled module state, spawns `next build`, and can
 *   `process.exit(1)`, so it must never run in the calling process. When the
 *   project has no `open-next.config.ts`, a minimal default is generated with
 *   the `aws-lambda-streaming` wrapper so the emitted handler streams on a
 *   Lambda Function URL (`invokeMode: RESPONSE_STREAM`). After the build, the
 *   authoritative `.open-next/open-next.output.json` manifest is read to
 *   verify the default origin is a streaming function.
 * - **`dev`** runs the real `next dev` through Next's documented custom-server
 *   API (`next({ dev: true })` + `prepare()` + `getRequestHandler()` on an
 *   http server we own) — plain Node, which is already the AWS Lambda
 *   programming model. Scoped: closing the Scope stops the app and the server.
 *
 * The OpenNext output topology the alchemy composite (`AWS.Website.Nextjs`)
 * deploys from `.open-next/`:
 *
 * - `server-functions/default/` — the SSR server Lambda (`index.handler`)
 * - `image-optimization-function/` — the image optimizer Lambda (sharp, arm64)
 * - `revalidation-function/` — the ISR revalidation consumer Lambda
 * - `assets/` — static assets for the CDN (`_next/static`, `public/`, BUILD_ID)
 * - `cache/` — the ISR/fetch cache seed (uploaded under the cache prefix)
 * - `dynamodb-provider/` — the tag-cache table seed function
 */
import * as FrameworkCore from "../core/index.ts";
import * as NodeChildProcessSpawner from "@effect/platform-node/NodeChildProcessSpawner";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Layer from "effect/Layer";
import * as Path from "effect/Path";
import type { PlatformError } from "effect/PlatformError";
import type * as Scope from "effect/Scope";
import * as Stream from "effect/Stream";
import * as ChildProcess from "effect/unstable/process/ChildProcess";
import type * as NodeHttp from "node:http";
import { createRequire } from "node:module";
import type * as NodeNet from "node:net";

const fail = (message: string) => (cause: unknown) =>
  new FrameworkCore.FrameworkError({ framework: "nextjs", message, cause });

/** Options for the Next.js AWS framework module. */
export interface NextjsAwsOptions {
  /** Project root. Defaults to the process working directory. */
  readonly root?: string | undefined;
  /**
   * The deploy target module specifier the caller resolved this module as.
   * This module IS the AWS target — the option is accepted (the
   * `AWS.Website.Server` resource always passes it) and ignored.
   */
  readonly target?: string | undefined;
  /**
   * Path of the OpenNext config, relative to the project root. When the file
   * does not exist, a minimal default with the `aws-lambda-streaming` wrapper
   * is generated ({@link DEFAULT_OPEN_NEXT_CONFIG}).
   * @default "open-next.config.ts"
   */
  readonly configPath?: string | undefined;
  /**
   * Extra CLI arguments appended to `open-next build` (e.g.
   * `["--dangerously-use-unsupported-next-version"]`).
   */
  readonly buildArgs?: ReadonlyArray<string> | undefined;
}

/** The server-module name of the default server's Lambda entry. */
export const SERVER_ENTRY_NAME = "server-functions/default/index.mjs";

/**
 * The minimal `open-next.config.ts` generated when the project has none:
 * the default (and only) server uses the `aws-lambda-streaming` wrapper so
 * the emitted handler wraps `awslambda.streamifyResponse` and expects a
 * Function URL with `invokeMode: RESPONSE_STREAM`.
 */
export const DEFAULT_OPEN_NEXT_CONFIG = `// Generated by @alchemy.run/web-frameworks/nextjs/aws.
// The default OpenNext config for the AWS topology alchemy deploys: the
// server streams its response on a Lambda Function URL. Edit freely, but
// keep the streaming wrapper — the Function URL is created with
// invokeMode: RESPONSE_STREAM.
const config = {
  default: {
    override: {
      wrapper: "aws-lambda-streaming",
    },
  },
};

export default config;
`;

/** The structural slice of `open-next.output.json` this module reads. */
interface OpenNextOutputManifest {
  readonly origins?: {
    readonly default?: {
      readonly type?: string;
      readonly handler?: string;
      readonly bundle?: string;
      readonly streaming?: boolean;
    };
  };
}

/**
 * Resolve the `@opennextjs/aws` CLI entry (`dist/index.js`, the `open-next`
 * bin) from the *project's* dependency tree. The package's exports map has
 * only a `"./*" -> "./dist/*"` pattern (no `"."` and no `./package.json`
 * subpath), so the `index.js` subpath is the one stable resolvable path.
 */
const resolveOpenNextCli = (root: string) =>
  Effect.try({
    try: () => {
      const require = createRequire(`${root.replace(/\/+$/, "")}/package.json`);
      return require.resolve("@opennextjs/aws/index.js");
    },
    catch: fail(
      `Failed to resolve "@opennextjs/aws" from ${root}. ` +
        "It must be installed in your project (it drives the Next.js build).",
    ),
  });

/**
 * Run `open-next build` in a disposable node child process with the project
 * root as cwd. Output is piped and re-emitted through the parent's own
 * stdout/stderr JS streams (NOT `stdio: "inherit"`) so in-process capture —
 * a test runner's log file — sees the build output.
 */
const runOpenNextBuild = (options: {
  readonly root: string;
  readonly cli: string;
  readonly configPath: string;
  readonly extraArgs: ReadonlyArray<string>;
}) =>
  Effect.scoped(
    Effect.gen(function* () {
      // Always plain `node` (never bun/`process.execPath`): the OpenNext CLI
      // mutates its own process.env (NEXT_PRIVATE_STANDALONE,
      // NEXT_PRIVATE_OUTPUT_TRACE_ROOT) before exec'ing `next build`, and
      // those mutations do not reliably reach execSync children under bun.
      const child = yield* ChildProcess.make(
        "node",
        [
          options.cli,
          "build",
          "--config-path",
          options.configPath,
          ...options.extraArgs,
        ],
        {
          cwd: options.root,
          stdin: "ignore",
          stdout: "pipe",
          stderr: "pipe",
        },
      ).pipe(
        Effect.mapError(
          fail(
            "Failed to spawn the @opennextjs/aws build CLI (is `node` on PATH?)",
          ),
        ),
      );
      const forward = (
        stream: Stream.Stream<Uint8Array, PlatformError>,
        dest: NodeJS.WriteStream,
      ) =>
        Stream.runForEach(stream, (chunk) =>
          Effect.sync(() => dest.write(chunk)),
        );
      const { exitCode } = yield* Effect.all(
        {
          exitCode: child.exitCode,
          stdout: forward(child.stdout, process.stdout),
          stderr: forward(child.stderr, process.stderr),
        },
        { concurrency: "unbounded" },
      ).pipe(
        Effect.mapError(fail("Failed reading the OpenNext build's output")),
      );
      if (exitCode !== 0) {
        return yield* Effect.fail(
          fail(`The OpenNext build exited with code ${exitCode}`)(undefined),
        );
      }
    }),
  );

// ---------------------------------------------------------------------------
// dev — the real `next dev` through the documented custom-server API
// ---------------------------------------------------------------------------

type RequestHandler = (
  req: NodeHttp.IncomingMessage,
  res: NodeHttp.ServerResponse,
) => Promise<void>;

/** The subset of `NextCustomServer` (the public custom-server API) we drive. */
interface NextDevApp {
  prepare(): Promise<void>;
  getRequestHandler(): RequestHandler;
  close(): Promise<void>;
}

type CreateNextServer = (options: {
  dev: boolean;
  dir: string;
  hostname: string;
  port: number;
}) => NextDevApp;

/**
 * Resolve the *project's* `next` (public entry, CJS) — the app's installed
 * copy is the one driven, never a hoisted sibling. Unwrap the ESM-interop
 * `default` nesting to the `createServer` function.
 */
const loadNext = (
  root: string,
): Effect.Effect<CreateNextServer, FrameworkCore.FrameworkError> =>
  FrameworkCore.loadProjectModule<Record<string, unknown>>(root, "next").pipe(
    Effect.mapError((error) =>
      fail(`Failed to load "next" from ${root}`)(error.cause),
    ),
    Effect.flatMap((module_) => {
      let candidate: unknown = module_;
      for (let i = 0; i < 3 && typeof candidate !== "function"; i++) {
        candidate = (candidate as Record<string, unknown> | undefined)?.default;
      }
      return typeof candidate === "function"
        ? Effect.succeed(candidate as CreateNextServer)
        : Effect.fail(
            fail(
              `The "next" package resolved from ${root} has no callable default export`,
            )(undefined),
          );
    }),
  );

interface HttpServerHandle {
  readonly port: number;
  readonly setHandler: (handler: RequestHandler) => void;
}

/**
 * Listen before Next starts: the actual port must be known when the app is
 * created (`port` seeds Turbopack's HMR/asset URLs), so the server binds
 * first (503 until the handler is wired) and the ephemeral port feeds
 * `next({ port })`. The HMR websocket upgrade is auto-wired by
 * `getRequestHandler()` through `req.socket.server` on the first request.
 */
const acquireHttpServer = (
  hostname: string,
  port: number | undefined,
): Effect.Effect<HttpServerHandle, FrameworkCore.FrameworkError, Scope.Scope> =>
  Effect.acquireRelease(
    Effect.callback<
      HttpServerHandle & {
        readonly server: NodeHttp.Server;
        readonly sockets: Set<NodeNet.Socket>;
      },
      FrameworkCore.FrameworkError
    >((resume) => {
      let handler: RequestHandler | undefined;
      const sockets = new Set<NodeNet.Socket>();
      // Lazy CJS require keeps `node:http` out of workerd bundles that may
      // statically scan this module's imports.
      const http = createRequire(import.meta.url)("http") as typeof NodeHttp;
      const server = http.createServer((req, res) => {
        if (handler !== undefined) {
          void handler(req, res);
        } else {
          res.statusCode = 503;
          res.end("Next.js dev server is starting");
        }
      });
      server.on("connection", (socket) => {
        sockets.add(socket);
        socket.on("close", () => sockets.delete(socket));
      });
      server.once("error", (cause) =>
        resume(
          Effect.fail(
            fail(`Failed to listen on ${hostname}:${port ?? 0}`)(cause),
          ),
        ),
      );
      server.listen(port ?? 0, hostname, () => {
        const address = server.address();
        if (address === null || typeof address === "string") {
          resume(
            Effect.fail(fail("The dev server has no TCP address")(address)),
          );
          return;
        }
        resume(
          Effect.succeed({
            server,
            sockets,
            port: address.port,
            setHandler: (h) => {
              handler = h;
            },
          }),
        );
      });
    }),
    ({ server, sockets }) =>
      Effect.callback<void>((resume) => {
        // Destroy live (keep-alive / HMR websocket) sockets so close() never
        // hangs on an idle connection.
        for (const socket of sockets) socket.destroy();
        server.close(() => resume(Effect.void));
      }),
  );

/** The service shape {@link make} resolves to (the framework-module contract
 * `AWS.Website.Server` drives; `serverModules` carries names only — the AWS
 * deploy ships the OpenNext bundles from disk, never in-memory). */
export interface NextjsAwsService {
  readonly build: (
    options?: FrameworkCore.FrameworkBuildOptions,
  ) => Effect.Effect<
    {
      readonly distDirectory: string;
      readonly clientDirectory: string;
      readonly serverModules: Array<{ readonly name: string }>;
    },
    FrameworkCore.FrameworkError
  >;
  readonly dev: (
    options?: FrameworkCore.FrameworkDevOptions,
  ) => Effect.Effect<
    FrameworkCore.FrameworkDevServer,
    FrameworkCore.FrameworkError,
    Scope.Scope
  >;
}

/**
 * Build the Next.js-on-AWS framework service. See the module doc for the
 * `build`/`dev` semantics.
 */
export const make: (
  options?: NextjsAwsOptions,
) => Effect.Effect<NextjsAwsService, never, FileSystem.FileSystem | Path.Path> =
  Effect.fnUntraced(function* (options?: NextjsAwsOptions) {
    const fs = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;

    const spawnerLayer = NodeChildProcessSpawner.layer.pipe(
      Layer.provide(
        Layer.merge(
          Layer.succeed(FileSystem.FileSystem)(fs),
          Layer.succeed(Path.Path)(path),
        ),
      ),
    );

    const resolveRoot = (override: string | undefined) =>
      Effect.sync(() =>
        path.resolve(override ?? options?.root ?? process.cwd()),
      );

    const build: NextjsAwsService["build"] = Effect.fn(function* (
      buildOptions?: FrameworkCore.FrameworkBuildOptions,
    ) {
      const root = yield* resolveRoot(buildOptions?.root);
      const configPath = options?.configPath ?? "open-next.config.ts";

      // Generate the minimal streaming config when the project has none. The
      // file lands in the project root (OpenNext resolves the config relative
      // to its cwd) and is left in place so subsequent builds — and the memo
      // input hash — see a stable tree.
      const absoluteConfigPath = path.resolve(root, configPath);
      const hasConfig = yield* fs
        .exists(absoluteConfigPath)
        .pipe(Effect.orElseSucceed(() => false));
      if (!hasConfig) {
        yield* fs
          .writeFileString(absoluteConfigPath, DEFAULT_OPEN_NEXT_CONFIG)
          .pipe(
            Effect.mapError(
              fail(
                `Failed to write the default OpenNext config at ${absoluteConfigPath}`,
              ),
            ),
          );
      }

      const cli = yield* resolveOpenNextCli(root);
      yield* runOpenNextBuild({
        root,
        cli,
        configPath,
        extraArgs: options?.buildArgs ?? [],
      }).pipe(Effect.provide(spawnerLayer));

      const distDirectory = path.join(root, ".open-next");
      const clientDirectory = path.join(distDirectory, "assets");

      // The authoritative manifest: verify the topology the composite deploys
      // (a streaming default server function) actually came out of the build.
      const manifestPath = path.join(distDirectory, "open-next.output.json");
      const manifestRaw = yield* fs
        .readFileString(manifestPath)
        .pipe(Effect.mapError(fail(`The build produced no ${manifestPath}`)));
      const manifest = yield* Effect.try({
        try: () => JSON.parse(manifestRaw) as OpenNextOutputManifest,
        catch: fail(`Failed to parse ${manifestPath}`),
      });
      const defaultOrigin = manifest.origins?.default;
      if (defaultOrigin?.type !== "function") {
        return yield* Effect.fail(
          fail(
            `The OpenNext build's default origin is "${defaultOrigin?.type}", not a Lambda function. ` +
              "The AWS deploy target only supports the function topology (no generateDockerfile).",
          )(undefined),
        );
      }
      if (defaultOrigin.streaming !== true) {
        return yield* Effect.fail(
          fail(
            "The OpenNext build's default server does not stream. The Lambda Function URL is " +
              "created with invokeMode: RESPONSE_STREAM, so open-next.config.ts must keep the streaming wrapper: " +
              '`default: { override: { wrapper: "aws-lambda-streaming" } }`.',
          )(undefined),
        );
      }

      const entryPath = path.join(distDirectory, SERVER_ENTRY_NAME);
      if (
        !(yield* fs.exists(entryPath).pipe(Effect.orElseSucceed(() => false)))
      ) {
        return yield* Effect.fail(
          fail(`The build produced no server entry at ${entryPath}`)(undefined),
        );
      }

      return {
        distDirectory,
        clientDirectory,
        serverModules: [{ name: SERVER_ENTRY_NAME }],
      };
    });

    const dev: NextjsAwsService["dev"] = Effect.fn(function* (
      devOptions?: FrameworkCore.FrameworkDevOptions,
    ) {
      const root = yield* resolveRoot(devOptions?.root);
      const hostname = "localhost";

      // Bind our http server first so the real port can seed `next({ port })`.
      const http = yield* acquireHttpServer(hostname, devOptions?.port);

      const createNext = yield* loadNext(root);
      const app = yield* Effect.acquireRelease(
        Effect.tryPromise({
          try: async () => {
            const app = createNext({
              dev: true,
              dir: root,
              hostname,
              port: http.port,
            });
            await app.prepare();
            return app;
          },
          catch: fail("Failed to start the Next.js dev server"),
        }),
        (app) => Effect.promise(() => app.close().catch(() => undefined)),
      );
      http.setHandler(app.getRequestHandler());

      return { url: `http://${hostname}:${http.port}` };
    });

    return { build, dev };
  });

export default make;
