import * as Console from "effect/Console";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Path from "effect/Path";
import { Argument, Command, Flag } from "effect/unstable/cli";

import { readStagesMeta } from "../../Stack.ts";

import { importStack, instrumentCommand } from "./_shared.ts";

const out = Flag.file("out").pipe(
  Flag.withDescription(
    "Output path for the generated declaration file. Defaults to .alchemy/types.d.ts.",
  ),
  Flag.withDefault(".alchemy/types.d.ts"),
);

const main = Argument.file("main", { mustExist: true }).pipe(
  Argument.withDescription(
    "Stack file to inspect. Defaults to alchemy.run.ts.",
  ),
  Argument.withDefault("alchemy.run.ts"),
);

const renderDeclaration = (stages: readonly string[]) => {
  const members = stages
    .map((s) => `    ${JSON.stringify(s)}: true;`)
    .join("\n");
  // `export {}` keeps this a module so `declare module "alchemy" {...}` is
  // treated as augmentation rather than an ambient redefinition.
  return `// Auto-generated by \`alchemy types\`. Do not edit by hand.
// Re-run the command after changing the \`stages\` array on Alchemy.Stack(...).
export {};

declare module "alchemy" {
  interface Stages {
${members}
  }
}
`;
};

const renderEmptyDeclaration = () =>
  `// Auto-generated by \`alchemy types\`. Do not edit by hand.
// No \`stages\` array was declared on Alchemy.Stack(...), so Stage falls back to \`string\`.
export {};
`;

export const _internal = { renderDeclaration, renderEmptyDeclaration };

export const typesCommand = Command.make(
  "types",
  { main, out },
  instrumentCommand("types", (a: { main: string; out: string }) => ({
    "alchemy.main": a.main,
    "alchemy.out": a.out,
  }))(
    Effect.fnUntraced(function* ({ main, out }) {
      const fs = yield* FileSystem.FileSystem;
      const path = yield* Path.Path;
      const stackEffect = yield* importStack(main);
      const meta = readStagesMeta(stackEffect);
      const stages = meta?.stages;
      const target = path.resolve(process.cwd(), out);

      yield* fs.makeDirectory(path.dirname(target), { recursive: true });

      if (stages && stages.length > 0) {
        yield* fs.writeFileString(target, renderDeclaration(stages));
        yield* Console.log(
          `Wrote ${out} (${stages.length} stage${stages.length === 1 ? "" : "s"}: ${stages.map((s) => `"${s}"`).join(", ")}).`,
        );
      } else {
        yield* fs.writeFileString(target, renderEmptyDeclaration());
        yield* Console.log(
          `Wrote ${out} with no stage augmentation. Add \`stages: [...] as const\` to Alchemy.Stack(...) to narrow \`yield* Stage\`.`,
        );
      }
    }),
  ),
);
