import * as Data from "effect/Data";
import type * as Effect from "effect/Effect";
import type * as HttpClientError from "effect/unstable/http/HttpClientError";

/**
 * Shared types and tagged errors for the Vercel Blob data plane
 * (`https://blob.vercel-storage.com`).
 *
 * The Blob data plane is not part of Vercel's management OpenAPI, so these
 * errors are hand-typed from the live-verified wire protocol (see
 * processes/Vercel/PROBES.md, "Blob data-plane + connect probes") rather
 * than generated by distilled — the same manual-spec gap noted for the
 * Queues data plane in `Queues/QueueApi.ts`.
 */

/** The env var Vercel injects into every project connected to a Blob store. */
export const BLOB_TOKEN_ENV = "BLOB_READ_WRITE_TOKEN";

/**
 * Metadata row returned by `list` — the data plane's list rows carry no
 * content type/disposition.
 */
export interface BlobListItem {
  /** Canonical blob URL (`https://{store}.{access}.blob.vercel-storage.com/{pathname}`). */
  readonly url: string;
  /** The blob URL with `?download=1` (forces attachment disposition). */
  readonly downloadUrl: string;
  /** Pathname of the blob within the store. */
  readonly pathname: string;
  /** Size in bytes. */
  readonly size: number;
  /** Upload timestamp. */
  readonly uploadedAt: Date;
  /** Quoted entity tag (e.g. `"ad314f..."`) — pass to `ifMatch` for CAS. */
  readonly etag: string;
}

/** Full metadata returned by `head`. */
export interface BlobObject extends BlobListItem {
  /** Content type recorded at upload. */
  readonly contentType?: string | undefined;
  /** Content disposition served with the blob. */
  readonly contentDisposition?: string | undefined;
  /** Cache-control policy served with the blob. */
  readonly cacheControl?: string | undefined;
}

/** Result of a successful `put`. */
export interface PutBlobResult {
  /** Canonical blob URL. */
  readonly url: string;
  /** The blob URL with `?download=1`. */
  readonly downloadUrl: string;
  /** Pathname of the blob within the store. */
  readonly pathname: string;
  /** Content type recorded at upload. */
  readonly contentType?: string | undefined;
  /** Content disposition served with the blob. */
  readonly contentDisposition?: string | undefined;
  /** Quoted entity tag of the NEW content — the CAS handle for the next write. */
  readonly etag: string;
}

/** Options for `put`. */
export interface PutBlobOptions {
  /** Content type stored and served with the blob. */
  readonly contentType?: string | undefined;
  /**
   * Compare-and-swap: only write if the blob's current etag matches (the
   * quoted etag returned by `put`/`head`/`list`). A mismatch fails with the
   * typed {@link BlobPreconditionFailed} (wire: 412 `precondition_failed`).
   */
  readonly ifMatch?: string | undefined;
  /**
   * Set `false` for a conditional CREATE: the write fails with the typed
   * {@link BlobAlreadyExists} if the pathname already exists (wire:
   * `x-allow-overwrite: 0` → 400). The client default is `true`
   * (overwrite) — note the data plane's WIRE default with the header
   * absent is to refuse overwrites, so the client always sends the
   * header explicitly.
   * @default true
   */
  readonly allowOverwrite?: boolean | undefined;
}

/** Options for `list`. */
export interface ListBlobsOptions {
  /** Only list blobs whose pathname starts with this prefix. */
  readonly prefix?: string | undefined;
  /** Page size. */
  readonly limit?: number | undefined;
  /** Continuation cursor from a previous page. */
  readonly cursor?: string | undefined;
}

/** One page of `list` results. */
export interface ListBlobsResult {
  readonly blobs: BlobListItem[];
  readonly hasMore: boolean;
  readonly cursor?: string | undefined;
}

/** Result of `get` — buffered content plus the served metadata. */
export interface GetBlobResult {
  /** Pathname of the blob within the store. */
  readonly pathname: string;
  /** Canonical blob URL the content was fetched from. */
  readonly url: string;
  /** Content type served with the blob. */
  readonly contentType?: string | undefined;
  /** Quoted entity tag served with the content. */
  readonly etag?: string | undefined;
  /** Size in bytes. */
  readonly size: number;
  /** The blob's content. */
  readonly bytes: Uint8Array;
  /** The content decoded as UTF-8. */
  readonly text: Effect.Effect<string>;
  /** The content parsed as JSON. */
  readonly json: <T = unknown>() => Effect.Effect<T, BlobInternalError>;
}

// ─────────────────────────────────────────────────────────────────────────────
// Tagged errors (live-verified wire codes)
// ─────────────────────────────────────────────────────────────────────────────

/** 401 — the data-plane token was rejected. */
export class BlobUnauthorized extends Data.TaggedError(
  "Vercel.Blob.Unauthorized",
)<{
  readonly message: string;
  readonly operation: string;
}> {}

/** 403 — the token is not allowed to perform the operation (or an unauthenticated private read). */
export class BlobForbidden extends Data.TaggedError("Vercel.Blob.Forbidden")<{
  readonly message: string;
  readonly operation: string;
}> {}

/** 404 `not_found` — the blob does not exist. */
export class BlobNotFound extends Data.TaggedError("Vercel.Blob.NotFound")<{
  readonly message: string;
  readonly pathname: string;
}> {}

/**
 * 400 `bad_request` "This blob already exists…" — a conditional create
 * (`allowOverwrite: false`) hit an existing pathname.
 */
export class BlobAlreadyExists extends Data.TaggedError(
  "Vercel.Blob.AlreadyExists",
)<{
  readonly message: string;
  readonly pathname: string;
}> {}

/** 412 `precondition_failed` — the `ifMatch` etag no longer matches. */
export class BlobPreconditionFailed extends Data.TaggedError(
  "Vercel.Blob.PreconditionFailed",
)<{
  readonly message: string;
  readonly pathname: string;
}> {}

/** Any other 400 from the data plane (e.g. access-mode mismatch on a put). */
export class BlobBadRequest extends Data.TaggedError("Vercel.Blob.BadRequest")<{
  readonly message: string;
  readonly operation: string;
}> {}

/** 429 — data-plane rate limit. */
export class BlobRateLimited extends Data.TaggedError(
  "Vercel.Blob.RateLimited",
)<{
  readonly message: string;
  readonly operation: string;
  readonly retryAfterSeconds?: number | undefined;
}> {}

/** Unexpected data-plane failure (5xx / unmapped status / body decode). */
export class BlobInternalError extends Data.TaggedError(
  "Vercel.Blob.InternalError",
)<{
  readonly message: string;
  readonly operation: string;
  readonly status?: number | undefined;
}> {}

/** Statuses every data-plane operation can produce. */
export type BlobCommonError =
  | BlobUnauthorized
  | BlobForbidden
  | BlobBadRequest
  | BlobRateLimited
  | BlobInternalError
  | HttpClientError.HttpClientError;

/** Errors of `head`/`get` (the blob may not exist). */
export type BlobReadError = BlobNotFound | BlobCommonError;

/** Errors of `list`. */
export type BlobListError = BlobCommonError;

/** Errors of `put` (CAS + conditional create are typed). */
export type BlobPutError =
  | BlobAlreadyExists
  | BlobPreconditionFailed
  | BlobCommonError;

/** Errors of `del` (idempotent — deleting a missing blob succeeds). */
export type BlobDeleteError = BlobCommonError;

/** Body shapes accepted by `put`. */
export type PutBlobBody = string | Uint8Array | ArrayBuffer | Blob;
