import * as Effect from "effect/Effect";
import * as Binding from "../../Binding.ts";
import type { RuntimeContext } from "../../RuntimeContext.ts";
import type { Database } from "./Database.ts";

/**
 * Bind a {@link Database} to a Worker for opt-in schema discovery.
 *
 * **Example:** Inspecting a D1 schema
 * ```typescript
 * const inspector = yield* Cloudflare.D1.IntrospectDatabase(MyDatabase);
 * const schema = yield* inspector.schema;
 * ```
 *
 * @binding
 * @product D1
 * @category Storage & Databases
 */
export interface IntrospectDatabase extends Binding.Service<
  IntrospectDatabase,
  "Cloudflare.D1.IntrospectDatabase",
  (database: Database) => Effect.Effect<IntrospectDatabaseClient>
> {}

export const IntrospectDatabase = Binding.Service<IntrospectDatabase>(
  "Cloudflare.D1.IntrospectDatabase",
);

export interface IntrospectDatabaseClient {
  /** Discover the database's tables, views, columns, and foreign keys. */
  schema: Effect.Effect<DatabaseSchema, never, RuntimeContext>;
}

export interface DatabaseSchema {
  /** User-defined tables and views, ordered by name. */
  tables: DatabaseTable[];
}

export interface DatabaseTable {
  /** Table or view name. */
  name: string;
  /** SQLite object type. */
  type: "table" | "view";
  /** Original CREATE statement, when SQLite exposes one. */
  sql: string | null;
  /** Columns in declaration order. */
  columns: DatabaseColumn[];
}

export interface DatabaseColumn {
  /** Column name. */
  name: string;
  /** Declared SQLite type. */
  datatype: string;
  /** SQL default expression, or `null` when absent. */
  defaultValue: string | null;
  /** Whether the column participates in the primary key. */
  primaryKey: boolean;
  /** Whether the column is generated by SQLite. */
  computed: boolean;
  /** Whether SQLite reports the column as nullable. */
  nullable: boolean;
  /** Foreign-key targets declared for this column. */
  foreignKeys: Array<{ table: string; column: string }>;
}
