import * as orbitalplanetarycomputer from "@distilled.cloud/azure/orbitalplanetarycomputer";
import * as Effect from "effect/Effect";
import * as Schedule from "effect/Schedule";
import { Unowned } from "../../AdoptPolicy.ts";
import { isResolved } from "../../Diff.ts";
import { createPhysicalName } from "../../PhysicalName.ts";
import * as Provider from "../../Provider.ts";
import { Resource } from "../../Resource.ts";
import {
  desiredTags,
  ensureRegistered,
  hasAnyAlchemyTag,
  ignoreNotFound,
  isOwned,
  orUndefinedIfNotFound,
  requireSinglePage,
  resourceGroupOf,
  tagsDiffer,
  userTags,
  waitForProvisioned,
  waitUntilGone,
} from "../Arm.ts";
import { AzureEnvironment } from "../Environment.ts";
import type { Providers } from "../Providers.ts";

/**
 * Microsoft.Orbital/geoCatalogs only supports user-assigned identities;
 * `SystemAssigned` is rejected with 400 "does not support creation of
 * 'SystemAssigned' resource identity".
 */
export type GeoCatalogIdentityType = "None" | "UserAssigned";

export interface GeoCatalogIdentity {
  /** Kind of managed identity attached to the GeoCatalog. */
  type: GeoCatalogIdentityType;
  /**
   * ARM resource IDs of user-assigned identities (required when `type`
   * is `UserAssigned`). Used to read ingestion sources.
   */
  userAssignedIdentities?: string[];
}

export type GeoCatalogDomainNameLabelScope =
  | "NoReuse"
  | "TenantReuse"
  | "SubscriptionReuse"
  | "ResourceGroupReuse";

export interface GeoCatalogProps {
  /**
   * Resource group of the GeoCatalog. Changing it replaces the catalog.
   */
  resourceGroup: string;
  /**
   * Name of the GeoCatalog: 3-24 lowercase letters, digits, and hyphens.
   * If omitted, a unique name is generated from the app, stage, and
   * logical ID. Changing it replaces the catalog.
   */
  name?: string;
  /**
   * Azure region. Planetary Computer Pro is available in a subset of
   * regions (e.g. `eastus`, `northcentralus`, `westeurope`,
   * `canadacentral`, `uksouth`). Changing it replaces the catalog.
   * @default the stack's Azure location
   */
  location?: string;
  /**
   * Tier of the catalog. Cannot be changed after creation; changing it
   * replaces the catalog.
   * @default "Basic"
   */
  tier?: "Basic";
  /**
   * Scope within which the auto-generated domain name label of
   * `catalogUri` is reused. Changing it replaces the catalog.
   * @default "TenantReuse"
   */
  autoGeneratedDomainNameLabelScope?: GeoCatalogDomainNameLabelScope;
  /**
   * Managed identity of the catalog, used to read ingestion sources such
   * as Blob Storage containers.
   * @default no identity
   */
  identity?: GeoCatalogIdentity;
  /** User tags. Alchemy ownership tags are merged in. */
  tags?: Record<string, string>;
}

export interface GeoCatalog extends Resource<
  "Azure.PlanetaryComputer.GeoCatalog",
  GeoCatalogProps,
  {
    /** Name of the GeoCatalog. */
    catalogName: string;
    /** ARM resource ID of the GeoCatalog. */
    catalogId: string;
    /** Resource group of the GeoCatalog. */
    resourceGroup: string;
    /** Region of the GeoCatalog. */
    location: string;
    /** Tier of the GeoCatalog. */
    tier: string | undefined;
    /** Scope of the auto-generated domain name label. */
    autoGeneratedDomainNameLabelScope: string | undefined;
    /**
     * URI of the catalog's STAC API and management UI, e.g.
     * `https://{name}.{label}.{region}.geocatalog.spatio.azure.com`.
     */
    catalogUri: string | undefined;
    /**
     * Principal ID of a system-assigned identity. GeoCatalogs only support
     * user-assigned identities, so this is normally `undefined`.
     */
    principalId: string | undefined;
    /** Provisioning state reported by ARM. */
    provisioningState: string | undefined;
    /** User tags (ownership tags stripped). */
    tags: Record<string, string>;
  },
  never,
  Providers
> {}

/**
 * A Microsoft Planetary Computer Pro GeoCatalog: a managed STAC catalog
 * for ingesting, indexing, and serving geospatial data. Billing is usage
 * based (storage, data operations, ingestion vCPU-hours), so an empty
 * catalog costs next to nothing.
 *
 * @see https://learn.microsoft.com/azure/planetary-computer/
 *
 * ### Creating a GeoCatalog
 * **Example:** Basic GeoCatalog in East US
 * ```typescript
 * const group = yield* Azure.Resources.ResourceGroup("geo", {
 *   location: "eastus",
 * });
 * const catalog = yield* Azure.PlanetaryComputer.GeoCatalog("catalog", {
 *   resourceGroup: group.resourceGroupName,
 * });
 * yield* Console.log(catalog.catalogUri);
 * ```
 *
 * ### Identity
 * **Example:** User-assigned identity for ingestion sources
 * ```typescript
 * const identity = yield* Azure.ManagedIdentity.UserAssignedIdentity("geo-id", {
 *   resourceGroup: group.resourceGroupName,
 * });
 * const catalog = yield* Azure.PlanetaryComputer.GeoCatalog("catalog", {
 *   resourceGroup: group.resourceGroupName,
 *   identity: {
 *     type: "UserAssigned",
 *     userAssignedIdentities: [identity.identityId],
 *   },
 * });
 * ```
 *
 * @resource
 */
export const GeoCatalog = Resource<GeoCatalog>(
  "Azure.PlanetaryComputer.GeoCatalog",
);

type ObservedGeoCatalog = orbitalplanetarycomputer.GetGeoCatalogResponse;

const createCatalogName = (id: string) =>
  createPhysicalName({ id, maxLength: 24, lowercase: true, delimiter: "-" });

const getCatalog = (
  subscriptionId: string,
  resourceGroupName: string,
  catalogName: string,
) =>
  orUndefinedIfNotFound(
    orbitalplanetarycomputer.GetGeoCatalog({
      subscriptionId,
      resourceGroupName,
      catalogName,
    }),
  );

const lower = (value: string | undefined) =>
  value?.toLowerCase().replaceAll(" ", "");

const toAttrs = (
  resourceGroup: string,
  name: string,
  observed: ObservedGeoCatalog,
): GeoCatalog["Attributes"] => ({
  catalogName: name,
  catalogId: observed.id ?? "",
  resourceGroup,
  location: observed.location,
  tier: observed.properties?.tier,
  autoGeneratedDomainNameLabelScope:
    observed.properties?.autoGeneratedDomainNameLabelScope,
  catalogUri: observed.properties?.catalogUri,
  principalId: observed.identity?.principalId,
  provisioningState: observed.properties?.provisioningState,
  tags: userTags(observed.tags),
});

const toRequestIdentity = (identity: GeoCatalogIdentity | undefined) =>
  identity === undefined
    ? { type: "None" }
    : {
        type: identity.type,
        userAssignedIdentities:
          identity.userAssignedIdentities === undefined
            ? undefined
            : Object.fromEntries(
                identity.userAssignedIdentities.map((id) => [id, {}]),
              ),
      };

const identityInSync = (
  desired: GeoCatalogIdentity | undefined,
  observed: ObservedGeoCatalog["identity"],
) => {
  if (lower(desired?.type ?? "None") !== lower(observed?.type ?? "None")) {
    return false;
  }
  const want = (desired?.userAssignedIdentities ?? [])
    .map((id) => id.toLowerCase())
    .sort();
  const have = Object.keys(observed?.userAssignedIdentities ?? {})
    .map((id) => id.toLowerCase())
    .sort();
  return want.length === have.length && want.every((id, i) => id === have[i]);
};

/** Creation was observed to take longer than 15 minutes. */
const PROVISION_BUDGET = { interval: "30 seconds", times: 120 } as const;

/**
 * Microsoft.Orbital rejects a write while another operation on the same
 * catalog is running (409 `InvalidResourceOperation`, "... is
 * active/in-progress"); wait for it to settle.
 */
const retryWhileBusy = <A, E extends { readonly _tag: string }, R>(
  effect: Effect.Effect<A, E, R>,
) =>
  effect.pipe(
    Effect.retry({
      while: (e) => e._tag === "HybridNetworkOperationInProgress",
      schedule: Schedule.spaced("10 seconds"),
      times: 60,
    }),
  );

/**
 * GeoCatalog deletion runs for a long time in the background while GET
 * still reports `Succeeded` (observed > 30 minutes). A DELETE rejected because another DELETE is
 * already running has, in effect, been accepted.
 */
const DELETE_BUDGET = { interval: "30 seconds", times: 150 } as const;

const deleteCatalog = (where: {
  subscriptionId: string;
  resourceGroupName: string;
  catalogName: string;
}) =>
  orbitalplanetarycomputer.DeleteGeoCatalog(where).pipe(
    Effect.asVoid,
    Effect.catchIf(
      (e) =>
        e._tag === "HybridNetworkOperationInProgress" &&
        (e.message ?? "").includes("'DELETE'"),
      () => Effect.void,
    ),
    retryWhileBusy,
  );

export const GeoCatalogProvider = () =>
  Provider.succeed(GeoCatalog, {
    stables: ["catalogName", "catalogId", "resourceGroup", "location"],

    list: Effect.fn(function* () {
      const { subscriptionId } = yield* AzureEnvironment.current;
      const page = yield* orbitalplanetarycomputer
        .ListGeoCatalogBySubscription({ subscriptionId })
        .pipe(
          Effect.flatMap((page) =>
            requireSinglePage("ListGeoCatalogBySubscription", page),
          ),
        );
      return (page.value ?? []).flatMap((catalog) => {
        const group = resourceGroupOf(catalog.id);
        return hasAnyAlchemyTag(catalog.tags) &&
          group !== undefined &&
          catalog.name !== undefined
          ? [toAttrs(group, catalog.name, catalog)]
          : [];
      });
    }),

    diff: Effect.fn(function* ({ news, output }) {
      if (!isResolved(news) || output === undefined) return undefined;
      if (
        lower(news.resourceGroup) !== lower(output.resourceGroup) ||
        (news.name !== undefined &&
          lower(news.name) !== lower(output.catalogName)) ||
        (news.location !== undefined &&
          lower(news.location) !== lower(output.location)) ||
        (news.tier !== undefined &&
          output.tier !== undefined &&
          lower(news.tier) !== lower(output.tier)) ||
        (news.autoGeneratedDomainNameLabelScope !== undefined &&
          output.autoGeneratedDomainNameLabelScope !== undefined &&
          lower(news.autoGeneratedDomainNameLabelScope) !==
            lower(output.autoGeneratedDomainNameLabelScope))
      ) {
        return { action: "replace" } as const;
      }
      return undefined;
    }),

    read: Effect.fn(function* ({ id, olds, output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      const resourceGroup = output?.resourceGroup ?? olds?.resourceGroup;
      if (resourceGroup === undefined) return undefined;
      const name =
        output?.catalogName ?? olds?.name ?? (yield* createCatalogName(id));
      const observed = yield* getCatalog(subscriptionId, resourceGroup, name);
      if (observed === undefined) return undefined;
      const attrs = toAttrs(resourceGroup, name, observed);
      return (yield* isOwned(id, observed.tags)) ? attrs : Unowned(attrs);
    }),

    reconcile: Effect.fn(function* ({ id, news, output }) {
      const env = yield* AzureEnvironment.current;
      const { subscriptionId } = env;
      yield* ensureRegistered(subscriptionId, "Microsoft.Orbital");
      const resourceGroup = news.resourceGroup;
      const name =
        news.name ?? output?.catalogName ?? (yield* createCatalogName(id));
      const location = news.location ?? output?.location ?? env.location;
      const tags = yield* desiredTags(id, news.tags);
      const where = {
        subscriptionId,
        resourceGroupName: resourceGroup,
        catalogName: name,
      };
      const label = `GeoCatalog ${name}`;
      const get = getCatalog(subscriptionId, resourceGroup, name);

      // Observe.
      let observed = yield* get;

      // Ensure. Creation is a long-running operation.
      if (observed === undefined) {
        yield* orbitalplanetarycomputer.CreateGeoCatalog({
          ...where,
          location,
          tags,
          identity:
            news.identity === undefined
              ? undefined
              : toRequestIdentity(news.identity),
          properties: {
            tier: news.tier,
            autoGeneratedDomainNameLabelScope:
              news.autoGeneratedDomainNameLabelScope,
          },
        });
      }
      observed = yield* waitForProvisioned(
        label,
        get,
        (catalog) => catalog.properties?.provisioningState,
        PROVISION_BUDGET,
      );

      // Sync identity and tags against observed state.
      const identityChanged = !identityInSync(news.identity, observed.identity);
      const tagsChanged = tagsDiffer(observed.tags, tags);
      if (identityChanged || tagsChanged) {
        yield* orbitalplanetarycomputer
          .UpdateGeoCatalog({
            ...where,
            tags: tagsChanged ? tags : undefined,
            identity: identityChanged
              ? toRequestIdentity(news.identity)
              : undefined,
          })
          .pipe(retryWhileBusy);
        observed = yield* waitForProvisioned(
          label,
          get,
          (catalog) => catalog.properties?.provisioningState,
          PROVISION_BUDGET,
        );
      }

      return toAttrs(resourceGroup, name, observed);
    }),

    delete: Effect.fn(function* ({ output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      yield* ignoreNotFound(
        deleteCatalog({
          subscriptionId,
          resourceGroupName: output.resourceGroup,
          catalogName: output.catalogName,
        }),
      );
      yield* waitUntilGone(
        `GeoCatalog ${output.catalogName}`,
        getCatalog(subscriptionId, output.resourceGroup, output.catalogName),
        DELETE_BUDGET,
      );
    }),

    nuke: { dependsOn: ["Azure.Resources.ResourceGroup"] },
  });
