name: Publish Preview Package
on:
  push:
    branches: [main]
  pull_request:
  pull_request_target:

jobs:
  pkg-pr:
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) ||
      (github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository) ||
      (github.event_name == 'push')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run --filter alchemy build

      # pkr.pr.new relies on pnpm-workspace.yaml for the `--pnpm` flag
      # which we need to resolve `catalog:` dependencies prior to publishing
      - name: Prepare Publish
        run: bun ./scripts/generate-pnpm-workspace.yaml.ts

      - run: bun add -D pnpm && bunx pkg-pr-new publish --pnpm ./alchemy
