name: Publish Preview Website

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

# Ensure only one workflow runs at a time per PR
concurrency:
  group: "pr-preview-${{ github.event.pull_request.number }}"
  cancel-in-progress: false

jobs:
  deploy-preview:
    if: ${{ github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Alchemy Environment
        uses: ./.github/actions/setup-alchemy
        with:
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Deploy Website Preview
        id: deploy
        run: |
          echo "Deploying website preview for PR #${{ github.event.pull_request.number }}"
          cd alchemy-web
          bun run deploy 2>&1 | tee deploy.log
        env:
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
          BRANCH_PREFIX: pr-${{ github.event.pull_request.number }}
          ALCHEMY_STATE_STORE: cloudflare
          ALCHEMY_STATE_TOKEN: ${{ env.ALCHEMY_STATE_TOKEN }}
          AWS_REGION: us-west-2
          # Pass GitHub token for GitHubComment resource
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # All secrets loaded from SSM parameter
          ALCHEMY_PASSWORD: ${{ env.ALCHEMY_PASSWORD }}
          CLOUDFLARE_ACCOUNT_ID: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_KEY: ${{ env.CLOUDFLARE_API_KEY }}
          CLOUDFLARE_EMAIL: ${{ env.CLOUDFLARE_EMAIL }}

  cleanup-preview:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Alchemy Environment
        uses: ./.github/actions/setup-alchemy
        with:
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Cleanup Website Preview
        run: |
          echo "Cleaning up website preview for PR #${{ github.event.pull_request.number }}"
          # Change to alchemy-web directory to run the same alchemy.run.ts with --destroy flag
          cd alchemy-web
          bun run alchemy.run.ts --destroy
        env:
          PULL_REQUEST: ${{ github.event.pull_request.number }}
          BRANCH_PREFIX: pr-${{ github.event.pull_request.number }}
          ALCHEMY_STATE_STORE: cloudflare
          ALCHEMY_STATE_TOKEN: ${{ env.ALCHEMY_STATE_TOKEN }}
          AWS_REGION: us-west-2
          # Pass GitHub token for GitHubComment resource
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # All secrets loaded from SSM parameter
          ALCHEMY_PASSWORD: ${{ env.ALCHEMY_PASSWORD }}
          CLOUDFLARE_ACCOUNT_ID: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_KEY: ${{ env.CLOUDFLARE_API_KEY }}
          CLOUDFLARE_EMAIL: ${{ env.CLOUDFLARE_EMAIL }}
