name: Publish Website

on:
  push:
    branches: [main]

# Ensure only one workflow runs at a time
concurrency:
  group: "publish"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4

      - name: Cache VitePress cache and OG images
        uses: actions/cache@v4
        with:
          path: |
            alchemy-web/.vitepress/cache
            alchemy-web/public/og-images
          key: ${{ runner.os }}-vitepress-cache

      - name: Setup Alchemy Environment
        uses: ./.github/actions/setup-alchemy
        with:
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Check Types
        run: bun run check

      - name: Publish docs
        uses: ./.github/actions/run-with-alchemy-env
        with:
          command: bun run deploy:website
